### ISSUE TITLE
Service Unavailable from AdBlock Plus

### ISSUE THREAD

**Issue by IamBramer** [barbajs/barba#270]
So I know this is probably more on AdBlock Plus than it is Barba.js but lately whenever I try to navigate to any other page after the initial load my browser returns a Service Unavailable page if AdBlock Plus is enabled. Just wanted to point this out as I'm sure many users have that plugin/addon installed for Chrome or Firefox, so anyone with that enabled won't be able to navigate around the website.

https://iambramer.com/

**Comment by IamBramer** [comment]
These are the errors Chrome will give (on Chrome the pages will still load but it will be a hard load and not an ajax load). If I disable AdBlock Plus everything will work as expected.

barba.min.js:2 GET https://iambramer.com/projects/ 0 ()
xhr @ VM229 barba.min.js:2
load @ VM229 barba.min.js:2
onStateChange @ VM229 barba.min.js:2
goTo @ VM229 barba.min.js:2
onLinkClick @ VM229 barba.min.js:2
(index):1 Uncaught (in promise) undefined
Promise.then (async)
init @ VM229 barba.min.js:2
onStateChange @ VM229 barba.min.js:2
goTo @ VM229 barba.min.js:2
onLinkClick @ VM229 barba.min.js:2
(index):1 Uncaught (in promise) undefined
Promise.then (async)
onStateChange @ VM229 barba.min.js:2
goTo @ VM229 barba.min.js:2
onLinkClick @ VM229 barba.min.js:2

**Comment by S1SYPHOS** [comment]
It’s common for people with adblockers (myself included) that JavaScript powered websites stop working as expected. With uBlock Origin however, I never had such a problem with barbaJS :confused:

**Comment by IamBramer** [comment]
Yeah, I know AdBlockers can really screw with things. I've been working with easylist to try and resolve what's going on as I don't think it is the fault of barbaJS. I think it might have something to do with the combination of the way barbaJS is working with my service worker that it is getting blocked.

Everything works amazing as soon as the add-on is removed. (Love barbaJS btw, my favorite JS library I have ever used.)

**Comment by luruke** [comment]
Thanks for the report @IamBramer , are you sure the problem is due adblockers? never had such problem myself...

**Comment by thierrymichel** [comment]
Please, feel free to reopen if you need more informations.
