### ISSUE TITLE
does it support bootstrap, i want to know how it support responsive and did you have any classes for creating new elements in responsive?

### ISSUE THREAD

**Issue by dheerajsharmasept** [barbajs/barba#333]

**Comment by c0mrx** [comment]
If we're talking solely bootstrap CSS, then I don't see why it wouldn't be compatible. As for mixing in the JS, you'll have to do a bit of work to get them working together. I've never used bootstrap, but this is true for most JS plugins being used in tandem with barba, as AJAX doesn't reevaluate any javascript.

As for responsiveness, most of that can be done with CSS, so I'm not sure what exactly you're trying to ask here. Barba will work with whatever you throw at it, so it's up to you to code how the site reacts to different screen sizes.

If you could provide an example of what it is you're trying to accomplish, I could perhaps assist you further.

**Comment by thierrymichel** [comment]
Please, feel free to reopen if you still having problems…
