### ISSUE TITLE
Text is not appearing on inner images, after reload text will display and after this when i close that part or click on back button, then text stick on screen.

### ISSUE THREAD

**Issue by dheerajsharmasept** [barbajs/barba#334]
http://test.krishnafurnishings.com/  - SEE THIS LINK

Click on Interior - No text will be displayed
Reload the page - Text will be displayed
Click on close button of image or click on back button - Text stick on screen

**Comment by c0mrx** [comment]
Your ```.kff_body_bottom_slider_one``` div is not in the barba wrapper, therefore it's not being loaded when you click on a link.

**Comment by dheerajsharmasept** [comment]
okay. i do some changes. But now problem is bottom container show also on inner pages and when i click on back button, bottom container automatically shift on top, and barba container shift on bottom, why ?
please tell me some css changes so i can fix this issue.

**LINK :** http://krishnafurnishings.com/barba/barbajs.org/demo/grid/index.html

**Comment by c0mrx** [comment]
@dheerajsharmasept It seems that your barba container and wrapper are inconsistent. They should always be structured and every page as follows:

```
<header>
  <!-- 

    THIS WILL NOT GET LOADED AGAIN WHEN THE PAGE TRANSITIONS
    Here's where your navigation and header should be
    
  -->
</header>

<main id="barba-wrapper"> <!-- This tells barba where the barba container is so it can sub it out -->
    <div class="barba-container" data-namespace="namespace">
      <!-- 

        EVERYTHING IN HERE WILL CHANGE WHEN THE PAGE TRANSITIONS
        Here's where you're content will go
        
      -->
  </div>
</main>

<footer>
  <!-- 

    THIS WILL NOT GET LOADED AGAIN WHEN THE PAGE TRANSITIONS
    Here's where your footer should be
    
  -->
</footer>
```

Everything inside of the barba container will get subbed out for the new content. If this is inconsistant on every page, you're going to get duplicated content.

**Comment by thierrymichel** [comment]
Please, feel free to reopen if you still having problems…
