### ISSUE TITLE
transitions for different pages

### ISSUE THREAD

**Issue by esseifforte** [barbajs/barba#336]
hello, congratulations for this script!

I wanted to know if it is possible to create specific transitions for each page.
Let me explain better, I read 'views' using namespaces.
I would like to create an animation from the home page for all the pages, and another animation between the internal pages of the site.

It's possible?

Thanks in advance.

**Comment by 19h47** [comment]
Hi @esseifforte!

You can hook into (Pjax.getTransition)[https://github.com/luruke/barba.js/blob/master/src/Pjax/Pjax.js#L289] to achieve different transition.

**Comment by thierrymichel** [comment]
Please, feel free to reopen if you still having problems…
