### ISSUE TITLE
How to create smooth transitions with barba js

### ISSUE THREAD

**Issue by developerkaushik** [barbajs/barba#339]
I have added some text in my HTML 5 but transitions are not smooth after adding some text also i want to know that how to create section in barba js i'm using div to create an new section it's not appering at the front please help me out as soon as possible link: http://krishnafurnishings.com/kff/

**Comment by thierrymichel** [comment]
Please, use the [issue template](https://github.com/barbajs/barba/blob/master/.github/ISSUE_TEMPLATE.md) or use the [Slack channel](https://barbajs.slack.com)…
