### ISSUE TITLE
Fade transition and carousel visibility

### ISSUE THREAD

**Issue by illycz** [barbajs/barba#344]
I'm using fade transition from example. When I'm reinit slick carousel in Views onEnter, visibility:hidden on newContainer is not respected and carousel is visible at time when oldContainer faded out. Do you have any experience with this?

onEnterCompleted function is late for me, because oldContainer is behave like modal and carousel on newContainer must look like before.

Thanks

**Comment by xavierfoucrier** [comment]
Hi @illycz!

Do you have any codepen demo or code sample showing what you are doing in the `onEnter` barba view?

Thx :wink:

**Comment by illycz** [comment]
Thanks @xavierfoucrier I will prepare something...

**Comment by thierrymichel** [comment]
Please, feel free to reopen if you still have problems.
