### ISSUE TITLE
We made free wordpress theme with your library. Could you add it to your collection?

### ISSUE THREAD

**Issue by leapincorp** [barbajs/barba#346]
First of all, thank you for providing an awesome library and I'm a big fan of Barba.js.

I saw the examples on your page(http://barbajs.org/examples.html) and i would like you to add our Wordpress Free Theme(GPL license) to the examples if you get to like it:)

Our website is here.
https://leap-in.com

![pjax-blog-seamless-transition mp4](https://user-images.githubusercontent.com/42055102/52129901-1adcf800-267c-11e9-954b-a0b28083715f.gif)

![demo_transitions mov](https://user-images.githubusercontent.com/42055102/52130505-b884f700-267d-11e9-8d72-52d236264da9.gif)
**We declare your copyright on readme file in theme folder.

Thank you for taking your time:)

**Comment by thierrymichel** [comment]
Hi @leapincorp,

Thanks for using barba !
For the moment, we are pushing the v2 and, by the way, there will be a brand new website.
I will keep your link for the "showcase" page…
