### ISSUE TITLE
Going to a link via function with delay - Not working with barba

### ISSUE THREAD

**Issue by smallio** [barbajs/barba#352]
Hi all,

Very excited to see v2 out!

Just wondering what's the best way transition to another page via a function? 

I'd like to achieve something like this, but it won't work with barba. Probably a stupid mistake my end, but I've never done this in ajax without actually clicking links.

```
function goToAboutPageWithDelay () {
  setTimeout(function() {
    window.location.href = "about.html";
  }, 500);
}

  var clickAndHoldTL = new TimelineMax({
    paused:true,
    onComplete: goToAboutPageWithDelay();
 });

```

Cheers!

**Comment by luruke** [comment]
Hello @smallio ,
check the `.go` method:
https://barba.js.org/docs/v2/api/classes/core.core-1.html#go

**Comment by thierrymichel** [comment]
Hi @smallio,

Do not hesitate to [join the Slack channel](https://join.slack.com/t/barbajs/shared_invite/enQtNTU3NTAyMjkxMzAyLTI1NDIxZDZmMGJjMDlmNzFkODZmMmVmN2U2ODg2Y2M3MzczMDdjZTk5ODQwNWZkYWVlMDM5NGZiODJmMWVhODk) for questions about how to use barba.js. :)

- With barba `2.x`, you have [`barba.go()`](https://barba.js.org/docs/v2/api/classes/core.core-1.html#go)
- With barba `1.x`, you have [`Barba.Pjax.goTo()`](https://barba.js.org/v1/docs/Barba.Pjax.html#.goTo)
