### ISSUE TITLE
Contributors list styling

### ISSUE THREAD

**Issue by thierrymichel** [barbajs/barba#353]
Github sanitizes markdown and removes inline styles.
We should go back to `all-contributors` default markup/styles…

**Comment by teambeauvoir** [comment]
Hi Thierry,

Thanks to you and all collaborators for your hard work. Very happy to see the v2 is now released and can't wait to step in and test it. One thing the documentation doesn't seem to mention, is pjax still mandatory to use the v2 or did you create a stand alone version?

Thank you!

**Comment by luruke** [comment]
hey @teambeauvoir , what you exactly mean by that?
The v2 still uses push state api in order to change the "url" without page refresh.
You can look at the "browser support" section in https://barba.js.org/docs/v2/user/

If you have other question open a new issue or join on the slack channel

**Comment by thierrymichel** [comment]
Fixed in https://github.com/barbajs/barba/commit/b587762cdf682e8662ccf33c252509095b41a7b4
