### ISSUE TITLE
!not a bug! - trying to access the slack channel

### ISSUE THREAD

**Issue by magicspon** [barbajs/barba#358]
heyo...

I'm trying to access the slack channel, but it appears you need to be invited. 

```
Don't have an account on this workspace yet?
Contact the workspace administrator for an invitation
```

keen to say hello and get involved! barba 2.0. wooooot!!

**Comment by thierrymichel** [comment]
@magicspon have you tried the “invite link to slack channel” from the README?

**Comment by magicspon** [comment]
Ha!.... not sure how i missed that!

Cheers
