### ISSUE TITLE
jQuery .off() won't fire upon barbajs page reload

### ISSUE THREAD

**Issue by pmascis** [barbajs/barba#361]
Hi all,
Firstly, loving what I can do with barba.js so far.
Secondly, sorry for the vague/incorrectly worded description.

This isn't really a bug nor an issue, more a lack of JavaScript/jQuery/aJax understanding on my behalf, so sorry about that, but some assistance would be greatly appreciated.

Upon clicking a certain link, I don't want a mouseleave to fire.
Research suggests I should use .off()
The below code works on page load, selecting the .clicky link won't fire the mouseout and I am taken to a new page, however when I select another link to take me back to the original page, selecting .clicky again will trigger the undesired mouseleave.

`	$(.clicky).unbind().on({
		mouseenter: function () {
			console.log('mouseenter');
		},
		mouseleave: function () {
			console.log('mouseleave');
		},
		click: function () {
			console.log('click');
			$(.clicky).unbind().off("mouseleave");
		}
	});`

Any insights would be greatly appreciated, as this has got me stuck in my current project.
Thanks in advance!

**Comment by thierrymichel** [comment]
@pmascis you probably need to use `views` or a global hook/event (depending on barba.js version used) or a jQuery context (like `$(document).on('mouseenter', '.clicky', … )`).

You will have better support on the [Barba Slack].(https://join.slack.com/t/barbajs/shared_invite/enQtNTU3NTAyMjkxMzAyLTI1NDIxZDZmMGJjMDlmNzFkODZmMmVmN2U2ODg2Y2M3MzczMDdjZTk5ODQwNWZkYWVlMDM5NGZiODJmMWVhODk).
