### ISSUE TITLE
change data-namespace

### ISSUE THREAD

**Issue by nadoaa** [barbajs/barba#363]
Hi
I need to use OOP to extend view in barba.js for specific page but How can I change data-namespace container when navigate to another page?

**Comment by luruke** [comment]
Hello @nadoaa ,
first of all, what version of barba.js are you using?

What you mean by changing `data-namespace` when navigate to another page?

**Comment by nadoaa** [comment]
I have common view to execute my code but I want to execute a specific code for a specific page to avoid uncaught error occurred. 
ex:
position().top;
Cannot read property 'top' of undefined at Object.onEnterCompleted error occur in pages which don't have an element I get it's top and this error is increase while I navigate between pages

So I tried to change data-namespace for page which has this element and put my code inside another view
https://codepen.io/rakan49/pen/OqeGLN

**Comment by luruke** [comment]
Hello @nadoaa ,
that's what the `Views` are used for.

Few things:
– If it's a new project, I suggest you to try to use the v2
– I see in your code you're manually changing the history. Barba does that for you
```
Barba.Dispatcher.on('transitionCompleted', function(currentStatus, prevStatus) {
		  history.replaceState(currentStatus, null, currentStatus.url);
		});
```

I'm closing the issue, don't hesitate to jump on the [slack channel](https://join.slack.com/t/barbajs/shared_invite/enQtNTU3NTAyMjkxMzAyLTI1NDIxZDZmMGJjMDlmNzFkODZmMmVmN2U2ODg2Y2M3MzczMDdjZTk5ODQwNWZkYWVlMDM5NGZiODJmMWVhODk) if you have other questions

**Comment by nadoaa** [comment]
Thank you for your response
I'm beginner in barba.js and I need your help.
This is my website link: https://wneet.com/demo/tihama
I changed version of barba.js but I have some problems, If you do not mind
can you check index.js file and my code.
My problems are:
1-  barba.BaseTransition.extend doesn't work, I don't know why!
2- Because barba.BaseTransition.extend doesn't work the preloader
(tl.restart﻿();
and t2.restart﻿(); ) doesn't work after transition between page.
3- I need to change data-barba-namespace in product.php page to run
specific code just for this page which make download button fixed after
scrolling (this code is in index.js after //product.php code to fixed
download button)
4- How can I specific data-barba-namespace for some pages and run code just
for this page or for only one page.


Thanks alot..

**Comment by thierrymichel** [comment]
@nadoaa :
- https://github.com/barbajs/barba#main-changes-tldr
- https://barba.js.org/docs/v2/user/

**Comment by nadoaa** [comment]
Thank you very much for your help

**Comment by nadoaa** [comment]
Hi
I changed barba to latest version.
My website works in localhost but after upload it to server the navigate
doesn't work (this is website url: https://wneet.com/demo/tihama/).
We are still working on it  so we don't want anyone to see it before upload
it.
please tell me where is the problem and how can I solve it?
