### ISSUE TITLE
prefetch with <script> tag

### ISSUE THREAD

**Issue by jake-101** [barbajs/barba#369]
I am trying to use barba js 2.0 by putting script tags linking to unpkg @next for both core and prefetch.
I tried to use the sample code on your new docs but it says prefetch is not defined. I am not using webpack so I wasn't able to import them. Here is some sample code, I just followed what you guys posted minus the imports.

```js
barba.use(prefetch);

  barba.init({
    debug: true,
    prefetchIgnore: false,
    logLevel: "debug",
    transitions:...
```

**Comment by thierrymichel** [comment]
@jake-101 with unpkg, plugins are prefixed: `barba.use(barbaPrefetch);`.
Do not know if it's a good idea but I found weird to expose globally `router`, `prefetch`, …

Documentation needs to be updated.

**Comment by thierrymichel** [comment]
Closed by https://github.com/barbajs/barba/commit/952c6707a36f914edf8bfc98656bf273702176e7
