### ISSUE TITLE
SecurityError: Blocked attempt to use history.pushState()

### ISSUE THREAD

**Issue by NasKadir123** [barbajs/barba#370]
Hello!
I've been trying to decide this error maybe for one week,
so now I'm done. Can you help me, please?
I just wanted simple page transition between two pages,
did all right, I actually checked 100 times.
But my url doesn't work, here it shows in console:
SecurityError: Blocked attempt to use history.pushState() to change session history URL from file:///Users/user/Desktop/page-transition%202/about.html to file:///Users/user/Desktop/page-transition%202/index.html. Paths and fragments must match for a sandboxed document.

url is absolutely right, if I delete barba.js so it works.

What should I do? I'm really want this transition on my website.
Thanks.

**Comment by thierrymichel** [comment]
Hi @NasKadir123, thanks for using barba.js.
Web is all about `http` (not `file`).
You need to run your website through a web server…

**Comment by NasKadir123** [comment]
> Hi @NasKadir123, thanks for using barba.js.
> Web is all about `http` (not `file`).
> You need to run your website through a web server…

Thanks a lot, I expected this, but wasn't sure, so it helped!
