### ISSUE TITLE
es6 arrow function usage causes "this" to lose reference to barba

### ISSUE THREAD

**Issue by OksanaRomaniv** [barbajs/barba#372]
## The problem

If a callback function for Barba hook is defined using arrow function - "this" becomes undefined.

## Description

For example, when you follow the example for v2 documentation inside the transition definition object: 

```
// `this.async()` style
    leave: (data) => {
      const done = this.async();

      callbackAnimation(data.current.container, {
        onComplete: () => {
          done();
        },
      });
    },
```
this.async() causing error: can't read async of undefined. 

If you specify the callback as a normal function declaration: 

```
// `this.async()` style
    leave: function (data) {
      const done = this.async();

      callbackAnimation(data.current.container, {
        onComplete: () => {
          done();
        },
      });
    },
```
everything works as expected. Shoudn't barba instance be bound to the callbacks to refference 'this' after using arrow function? 

## Environment

- Barba version that exhibits the issue: "@barba/core": "^2.1.1-next.106",
- Browser OS/version used: Ubuntu 18.04, Chrome
- Build : webpack (via laravel mix 4.0) and "@babel/preset-env": "^7.2.3"

**Comment by thierrymichel** [comment]
@OksanaRomaniv good catch! :+1:
I will update the documentation (waiting for a possible clean solution, although the context must remain the transition object itself).
