### ISSUE TITLE
Block appears between page transition

### ISSUE THREAD

**Issue by NasKadir123** [barbajs/barba#374]
Hello!
I'm using simple page transition like on your website, I just have an image covering whole page and URL and haven't any scroll on each page,
It works good,
but when I click on URL to the next page, there is appear scroll and white block below.
Can you help me, please?

**Comment by luruke** [comment]
Hello @NasKadir123 ,
Do you have a link/repo where we can reproduce this?
What version of barba are you using?

Please use the issue template, otherwise it will be hard to help you

**Comment by NasKadir123** [comment]
Sorry, but I haven't any links.
I'm using old version, uploaded here in github barba.min.js file,
is it bad?
Should I try with new version?

**Comment by NasKadir123** [comment]
> Hello @NasKadir123 ,
> Do you have a link/repo where we can reproduce this?
> What version of barba are you using?
> 
> Please use the issue template, otherwise it will be hard to help you

Sorry, but I haven't any links.
I'm using old version, uploaded here in github barba.min.js file,
is it bad?
Should I try with new version?

**Comment by luruke** [comment]
@NasKadir123 , you can use the v1, but we don't continue the development – so if it's a new project, I would advice to use the v2.

In any case, if you can't add more information or share the code, we can't help you.

**Comment by NasKadir123** [comment]
> @NasKadir123 , you can use the v1, but we don't continue the development – so if it's a new project, I would advice to use the v2.
> 
> In any case, if you can't add more information or share the code, we can't help you.

I read about new version, so I think my question is not necessary,
I will try new version, thanks for your answers!
