### ISSUE TITLE
Barba caching preventing ScrollReveal calls

### ISSUE THREAD

**Issue by chadwickellis** [barbajs/barba#376]
## The problem

With cacheIgnore set as false (the default value) and after the initially loaded page has been cached, upon revisiting this page ScrollReveal cannot be called. Naturally, this issue can be alleviated by setting cacheIgnore as true, however, it would be beneficial to enable Barba caching for the reasons mentioned in the documentation.

I have attempted to implement all of ScrollReveal's methods — clean, destroy, reveal and sync — on this initially loaded page to no avail. In addition to this, I have looked into implementing ScrollReveal's delegate method as mentioned in a [previous issue](https://github.com/scrollreveal/scrollreveal/issues/473) from ScrollReveal's repository, again with no success.

## Environment

- Barba version that exhibits the issue: "@barba/core": "^2.1.1-next.112"
- Build used:
  - [ ] module (esm/)
  - [X] browser (dist/)
  - [ ] main (lib/)
- Browser OS/version used: Firefox (Version 66.0.2), Chrome (Version 73.0.3683.86) and Safari (Version 12.0.2)

**Comment by thierrymichel** [comment]
Hi @chadwickellis,

Cache avoid to re-fetch your content so you do not have unnecessary server calls.
But it "just" stores the page content (html). No scripts "external" are (re)executed after page transition.

If you need to (re)execute some code for specific pages, you need to use [views](https://barba.js.org/docs/v2/user/core.html#view-object).
If you want to run code before/after all transitions, you can use a ["global" hook](https://barba.js.org/docs/v2/user/core.html#transition-object) via `barba.hooks`.

I think using ScrollReveal's delegate method is the best option. Just run it on first page load and delegate to the right element.
If it doesn't work, in your case, the second option should do the job!

NB: `cacheIgnore` option shouldn't change anything…

**Comment by chadwickellis** [comment]
Thank you very much for getting back to me with regard to this. I understand Barba's caching principles and how scripts need to be reinitialised using either hooks or transitions. I have reinitialised ScrollReveal through a shared enter transition:

`export const defaultEnter = () => { ScrollReveal().reveal('.reveal', revealConfig) };`

This works on _all_ pages except for the initially loaded page. Removing this ScrollReveal call from the transition, of course, prevents the scroll animations from firing and shows that the initially loaded page is cached with ScrollReveals `data-sr-id` tags on the reveal elements. This would suggest that the page is being cached after initial script execution. I'm going to open an issue on the ScrollReveal repository to seek help with regard to the `data-sr-id` tags. Thank you for your time.
