### ISSUE TITLE
i.barba.dom.getUrl is not a function with barba.use(barbaPrefetch);

### ISSUE THREAD

**Issue by OksanaRomaniv** [barbajs/barba#380]
---

## The problem

Getting this error on each page transition when enabling barbaPrefetch. [http://i.imgur.com/OOjGAOr.png](http://i.imgur.com/OOjGAOr.png)

### Details

After adding this:

```
// tells barba to use the prefetch module
import barbaPrefetch from '@barba/prefetch';
barba.use(barbaPrefetch);
```
before barba.init() call, I started to receive the console error on each page transition, so I'm not sure the prefetch functionality works in my case :)

## Environment

- Barba version that exhibits the issue: 
  "@barba/core": "^2.1.1-next.106",
  "@barba/prefetch": "^2.1.0",
- Build used:
  - webpack (via laravel mix)
- Browser OS/version used: Ubuntu 18.04, Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by luruke** [comment]
Hey @OksanaRomaniv , are you sure you're running the latest version of `@barba/prefetch`? I think there is a `next` version also for that package.

Have some patience, soon this `next` "madness" will be over :)

**Comment by OksanaRomaniv** [comment]
Hi @luruke, 

I removed the version I had and installed the @next update, but now I'm getting a different error:

[http://i.imgur.com/igvB0ca.png](http://i.imgur.com/igvB0ca.png)

P.S can't wait for the v2 full release. barba.js is awesome :)

**Comment by thierrymichel** [comment]
@OksanaRomaniv still not sure you are using the latest version…
To get rid of those `@next` confusing stuff, we decided to publish in the "normal" way.
In addition, I've added a "version log".

Can you try with a fresh `npm i @barba/core @barba/prefetch` ?
Thanks!
