### ISSUE TITLE
Barba container append/prepend option ?

### ISSUE THREAD

**Issue by OksanaRomaniv** [barbajs/barba#381]
## The problem

When using barba, the barba-container is prepended to the outer element that causes the other elements to change position before the container in contrary to positioning after container as they were initially.

## Description

I'm working on implementing barba.js on the WordPress website and I've set the barba-container as the inner wrapper of the website inside the <body> element (body element is excluded from Barba container). 

After navigating between pages, the barba-container is prepended to body, that causes all the <script> tags at top of the body, instead of at the bottom. 

Structure before:

[http://i.imgur.com/yiSHP8n.png](http://i.imgur.com/yiSHP8n.png)

Structure after:

[http://i.imgur.com/edij0bR.png](http://i.imgur.com/edij0bR.png)

## Q

Is there a way to define if the container should be prepended or appended? Should I include the script tags to the container also? 

Thanks

**Comment by thierrymichel** [comment]
Hi @OksanaRomaniv,

A few thought:
1. Does it "visually" change something? ;)
2. In case of a prepend option, your new container will be added before your `.ya-main.nav-slider`. Not sure it's better…
3. I've never used `data-barba="wrapper"` directly on the `body`… May be you can use an extra tag for the wrapper (`main`, `div`, …)? Can it be a solution?

Beside that, we could replace `append` to wrapper by `insertAfter` current container (ping @luruke)
We will consider it.

Thanks for your involvement!

**Comment by OksanaRomaniv** [comment]
It’s true that page visually doesn’t change and works as expected, but
after countless of hours of speed optimization for WP websites and
struggling with deferring/moving scripts to website footer, these tags at
top of the page make me tilted :)

I think it would add even more flexibility in building barba applications
if you could define the insertion point.

Thanks for considering!
