### ISSUE TITLE
About barba events

### ISSUE THREAD

**Issue by NasKadir123** [barbajs/barba#382]
Hi! I'm a beginner.
I used barba js for page transition and when I went to the next page my javascript didn't work. 
So I read in issues about events and add - transitionCompleted, so everything gets worked nice.
But If I refresh this page, my javascript will not work, and in console appears this: Error: Barba.js: DOM not ready!

Can you help me, please?

**Comment by thierrymichel** [comment]
Hi @NasKadir123,

You should probably wait for your DOM is ready.
Try to use some `DOMContentLoaded` event before executing your code or put your `script` tag before the end of the body…

**Comment by NasKadir123** [comment]
> Hi @NasKadir123,
> 
> You should probably wait for your DOM is ready.
> Try to use some `DOMContentLoaded` event before executing your code or put your `script` tag before the end of the body…

I put the script tag before the end of the body many times, but nothing happens)
But after your message I put, so it gets worked! Thanks a lot!
