### ISSUE TITLE
Transition wait for the load

### ISSUE THREAD

**Issue by FANATIC1868** [barbajs/barba#386]
Hello, I'm using barbajs a short time ago.
I would like the transition to last until the content of my new view is loaded (images and videos).

I have tried with

$ (window) .on ('load', function () {
});

but since barba does not reload the page it does not work.

I would greatly appreciate your help, thank you.

**Comment by thierrymichel** [comment]
Hi @FANATIC1868,

You need to implement it by yourself. This can help :
- https://imagesloaded.desandro.com/
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loadeddata_event
