### ISSUE TITLE
Equivalents to Events from v1

### ISSUE THREAD

**Issue by 3oax** [barbajs/barba#388]
What are the equivalents to the events "transitionCompleted", "initStateChange", "newPageReady"? I want to update my newest application to v2. 

in my older projects I had a global method that executes on every newpageready, another global function on transitioncompleted and another on initstatechange (google analytics etc).

i dont want to add these functions on every view.

edit: okay, think i got it.

// defines a global hook
barba.hooks.page((data) => {
 // do whatever
});

**Comment by thierrymichel** [comment]
Yep :+1:
https://barba.js.org/docs/v2/api/modules/typings_core.html#hooksafter
