### ISSUE TITLE
Using @barba/css throws an error: this.logger.print is not a function

### ISSUE THREAD

**Issue by mensch** [barbajs/barba#390]
## The problem

I'm trying to use @barba/css but the current version throws an error when I try to use it. It seems it tries to print an error, but fails, because the logger isn't available somehow: ```Uncaught TypeError: this.logger.print is not a function```

The error seems to be introduced in 2.1.3, because it isn't present in @barba/css@2.1.2

### Details

Barba tries to print an error, but fails, due to the unavailable Logger class.

### Expected behaviour

If there's an error it should be printed, otherwise there maybe should be a check for the availability of the logger.

### Actual behaviour

Barba cannot find the logger and fails to initialize.

### Code To Reproduce Issue
I'm using the example code, albeit in its own class:

```js

import barba from '@barba/core';
import barbaCss from '@barba/css';

export default {
  init() {
    barba.use(barbaCss);
    barba.init({
      transitions:[
        {
          from: { namespace: 'over-verwonderzoek' },
          to: { namespace: 'contact' },
          name: 'slide-up',
        },
      ],
    });
  },
};

```

## Environment

- Barba version that exhibits the issue: @barba/css@2.1.3 and onwards
- Build used:
  - [x] module (esm/)
  - [x] browser (dist/)
  - [ ] main (lib/)
- Browser OS/version used: N/A

**Comment by thierrymichel** [comment]
Hi @mensch, thanks for using barba.js.
You should probably also update `@barba/core` (https://github.com/barbajs/barba/blob/master/packages/core/CHANGELOG.md#213-2019-04-13)

**Comment by mensch** [comment]
Thanks for the pointers! I thought I was already at the latest version for ```@barba/core```. Should have checked, because the error is resolved now.
