### ISSUE TITLE
How to reinit the page javascript

### ISSUE THREAD

**Issue by freshface** [barbajs/barba#392]
Hi

I placed my javascript inside the barba container, but it does not reinit.
What is the best practice to do this.

**Comment by freshface** [comment]
Ps: i am using barba v2

**Comment by xavierfoucrier** [comment]
Hi @freshface,

Can you please fill in the issue template or at least give us a code sample to reproduce the issue?
It's better to understand your needs.

Thanks :wink:

**Comment by thisanimus** [comment]
I break the js I need to re-init with each pageload into functions, then load those functions in the "afterEnter(){}" event.

**Comment by xavierfoucrier** [comment]
@freshface @thisanimus , you mean when the requested page contains inline javascript, it is not properly reloaded?

**Comment by freshface** [comment]
Sorry for the delay, i provided an example  https://codepen.io/frederik-heyninck/project/editor/XLbrRy My main question/problem is, where do i put my main.js to reinit on every load. Also on the contact page i loaded a script to autosize the textarea. This does not work if i navigatie to the contact page.

**Comment by xavierfoucrier** [comment]
Ok.

First of all, if you are new to Barba, start with the **legacy example** here: https://barba.js.org/docs/v2/user/legacy.html

Next, define a namespace on each page, see the documentation here: https://barba.js.org/docs/v2/user/core.html#namespace.

> Note that your namespaces are the same on every page: you need to define **a different namespace for each page** in your project

Finally, Barba will use those namespaces for `Views` and execute actions depending on the page you are visiting, see the documentation here: https://barba.js.org/docs/v2/user/core.html#view-object.

Hope this help! :wink:

**Comment by freshface** [comment]
Hi Xavier

This helps. I changed my code to do a function after a view is loaded.
I need to load the same function on each page so i gave al my pages the same namespace.

My init() function in main.js gets called every time, but this particular part is not executing:


``` document.getElementById("loaded").innerHTML = "Injected with javascript i should be visible on each page";  ```

**Comment by xavierfoucrier** [comment]
Hi @freshface,

You probably have a problem with the two `body` tag in your web page: be careful!

**Comment by freshface** [comment]
Indeed, i fixed it but no result :(

**Comment by xavierfoucrier** [comment]
It's because you are sibling the element with an `id`. As Barba is using another container to load the next page, your selector grab the first one, not the next one: `document.querySelectorAll('#loaded').length` returns 2 into the init() method.

**Comment by freshface** [comment]
Okay, i understand, what could be the best way to deal with this?

**Comment by xavierfoucrier** [comment]
It depends on your needs... but if you just want to update a paragraph depending on the page, it's better to put the paragraph outside the barba wrapper, use an id and update the content using getElementById or querySelector to target the element.

**Comment by dngraphisme** [comment]
> Ok.
> 
> First of all, if you are new to Barba, start with the **legacy example** here: https://barba.js.org/docs/v2/user/legacy.html
> 
> Next, define a namespace on each page, see the documentation here: https://barba.js.org/docs/v2/user/core.html#namespace.
> 
> > Note that your namespaces are the same on every page: you need to define **a different namespace for each page** in your project
> 
> Finally, Barba will use those namespaces for `Views` and execute actions depending on the page you are visiting. Use the appropriate view `hook` to do this, see the documentation here: https://barba.js.org/docs/v2/user/core.html#view-object.
> 
> Hope this help! 😉

I followed your tutorial but impossible to run my script of my form or I also have a beug on another function that I do not understand with scrollamgic and swiper :/
