### ISSUE TITLE
Using barbaCSS seems to ignore JS transition animations

### ISSUE THREAD

**Issue by iamkoa** [barbajs/barba#394]
First off, I absolutely love Barba!!!

I can't figure out how use CSS transitions (like fading in/out the data container, for example) without seeming to kill (or ignore) the custom transitions shown below.

How do I use both CSS transitions and the transitions below?

Thank you for the help!

```javascript
barba.use(barbaCss); // Adding this line causes the below transitions to be ignored?!
barba.init({
    transitions: [{
        leave(data) {
            return new Promise(resolve => {
                blob_handler.start().finished.then(function() {
                    window.scrollTo(0, 0);
                    if (isNavOpen() === true) { toggleNav(); }
                    resolve();
                });
            })
        },
        enter(data) {
            return new Promise(resolve => {
                resolve();
                blob_handler.end().finished.then(function() {
                    // Do something
                });
            })
        }
    }],
    views: [{
        namespace: "home",
        afterEnter(data) {
            letsType();
        },
    }, {
        namespace: "blog",
        afterEnter(data) {}
    }]
});
```

**Comment by thierrymichel** [comment]
Hi @iamkoa and thanks for trying v2.
I didn't test `@barba/css` with JS and it can cause some issues.
Actually, main hooks (appear, leave, enter) are replaced with CSS.

It should be possible to keep and execute them but duration will still based on the CSS transition…
Should it fix your issue?

**Comment by iamkoa** [comment]
@thierrymichel Thank you for your response!

If I understand correctly, using CSS will kill the ability to set durations in JS. Ideally I'd like to use JS animations in combination with CSS fades without having to manually set class names. Was hoping that this was baked into Barba but no problem!

Thanks again for the help 👍

**Comment by thierrymichel** [comment]
#412
