### ISSUE TITLE
Buttons, links outside data-barba="wrapper" - Barba V2

### ISSUE THREAD

**Issue by ProdesignerAgency** [barbajs/barba#395]
Hello, Barba fans. I'm creating my first project on Barba V2 based on WordPress and I think it's the best library I've seen in many years. Everything works within data-barba="wrapper", but I have a problem to understand how can i use buttons outside the wrapper -> like browser next and previous buttons, and links in the menu in which classes change to active ( if is current page) both refresh and click event. Please help.

I checked the links below, 

https://github.com/barbajs/barba/issues/43
https://github.com/barbajs/barba/issues/223

but I have no idea how to use it in version 2.
(excuse my weak English)

Best!

**Comment by xavierfoucrier** [comment]
Hi @ProdesignerAgency,

If I understand well, you want to know how to update your components outside the Barba wrapper, like navigation, menu, etc..

You can use one of the available **transition hook**, for example to properly update the active menu item between two pages you can do the following:

```js
barba.init({
  transitions: [{
    name: 'default',
    before: ({ current, next, trigger }) => {

      // get the menu element
      let menu = document.querySelector('.menu');
      
      // select the menu item depending on the next URL (you can do that in many ways)
      let nextItem = menu.querySelector(`a[href="${next.url.href}"]`);
      
      // reset the active menu item and set the next item as "active" (if there is one)
      if (nextItem !== null) {
        menu.querySelector('.item-active').classList.remove('item-active');
        nextItem.classList.add('item-active');
      }
    }
  }]
});
```

> See https://barba.js.org/docs/v2/user/core.html#hooks for detail documentation

Hope this help! :wink:

**Comment by ProdesignerAgency** [comment]
Thank U :)
