### ISSUE TITLE
Some unnecessary delay between 'enter' and inserting content to barbaContainer

### ISSUE THREAD

**Issue by sergey-pimenov** [barbajs/barba#396]
Hi, thank you very much for the library! I have such a problem.

Suppose I have this code:

```javascript
{
  name: 'fromHomepageToProject',
  from: {
    namespace: ['homepage'],
  },
  to: {
    namespace: ['project'],
  },
  leave: function() {
    let done = this.async();

    // Some animation in 300 ms

    setTimeout(done, 300);
  },
  enter: function() {
     // Some animation
     ...

     // Set some listeners for new content in barbaContainer
     project.setListeners();
  },
```

The problem: there is a delay between calling the 'enter' function and inserting new content into the `barbaContainer`. Delay no more than 50ms. I don't understand why it exists. For me, this is critical, because after inserting new content into barbaContainer, I create some event listeners for new DOM elements in `barbaContainer` and I need to know exactly when I have new content in DOM.

Now I'm solving this problem in a very stupid way:

```javascript
{
  enter: () => {
     // Some animation
     ...

     // Set some listeners for new content in barbaContainer
    setTimeout(() => {
         project.setListeners();
    }, 50);
  },
```

But it looks terrible of course. I'm already desperate. Tried to rewrite in promise style, but the result is the same, there is still a delay.

I really need your help

P.S. It's not matter what i use - 'afterEnter' or even 'after'. Result the same :(

**Comment by oguilleux** [comment]
Have you tried calling `this.async();` juste before `project.setListeners();` like so :

```
{
  enter: function() {
    this.async();
    project.setListeners();
  },
}
```

**Comment by thierrymichel** [comment]
Feel free to re-open if you still have the problem…
