### ISSUE TITLE
Window.scrollBy() doesn't execute if page is loaded through Barba

### ISSUE THREAD

**Issue by alexpi** [barbajs/barba#398]
Hello,

I have a page with a link that when clicked, scrolls down a bit. I used the window.scrollBy() function for that. When the page is loaded through a Barba transition, the scroll isn't happening. If I go straight to the page or reload it, it works as expected.

Any ideas?

**Comment by xavierfoucrier** [comment]
I seems to work as expected for me. Do you have any codepen or code sample for this use case?

Thanks :wink:

**Comment by alexpi** [comment]
The page I wanted to scroll, that was loaded with Barba, was absolutely positioned and didn't have any height past the window height to scroll. Sorry!

**Comment by xavierfoucrier** [comment]
I got an answer by mail but that is not displayed here: is the problem solved? Thx

**Comment by alexpi** [comment]
The problem is not solved, but it is specific to the way I did my layout. It is not Barba related. Sorry for the confusion!

**Comment by xavierfoucrier** [comment]
Ok, so I close the issue 😉
