### ISSUE TITLE
Barba js add the height of the page to the body tag

### ISSUE THREAD

**Issue by krishna-wac** [barbajs/barba#401]
Hi Everyone,

I'm using Barba js in my project. I have tried to do smooth scrolling. so I want to add the page height to the body tag. When I refresh for the first time it will take the page height correctly. when I click it's not working. Can anyone help me to sort it out? 

This is the plugin I have used in my Barba project <https://codepen.io/osublake/pen/QqPqbN>. In this, they add total height to the body tag. Likewise, I need to add in my body tag by using Barba js. please help me

Thanks

**Comment by c0mrx** [comment]
Hi @krishna-wac,

You'll need to run the `onLoad()` function after barba has loaded the new page.

On barba v1: 
```
Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container) {
  onLoad();
});
```

on barba v2:
```
barba.hooks.afterEnter( ( data ) => {
  onLoad();
} );
```

**Comment by krishna-wac** [comment]
> Hi @krishna-wac,
> 
> You'll need to run the `onLoad()` function after barba has loaded the new page.
> 
> On barba v1:
> 
> ```
> Barba.Dispatcher.on('newPageReady', function(currentStatus, oldStatus, container) {
>   onLoad();
> });
> ```
> 
> on barba v2:
> 
> ```
> barba.hooks.afterEnter( ( data ) => {
>   onLoad();
> } );
> ```

**Comment by krishna-wac** [comment]
Hi @c0mrx,

Thanks for your reply will try and check. (Y)
