### ISSUE TITLE
Add demos with v2

### ISSUE THREAD

**Issue by hugobqd** [barbajs/barba#402]
That could be very useful for non-JS-experts to have some demos for the v2.
I found that repo https://github.com/barbajs/barba/tree/v2-examples but this is actually the demo of the v1.
Thanks !

**Comment by c0mrx** [comment]
Hi @hugobqd,

@thierrymichel has some on his Codepen page. You can find them [here](https://codepen.io/thierrymichel/projects/public/)!

You can also [join the slack channel](https://join.slack.com/t/barbajs/shared_invite/enQtNTU3NTAyMjkxMzAyLTI1NDIxZDZmMGJjMDlmNzFkODZmMmVmN2U2ODg2Y2M3MzczMDdjZTk5ODQwNWZkYWVlMDM5NGZiODJmMWVhODk) if you need help.

Cheers!

**Comment by hugobqd** [comment]
Nice, I discovers Github Project Editor in the same time !

**Comment by thierrymichel** [comment]
@hugobqd I am currently rewriting v1 examples to v2.
It should be done at the end of the week… 🤞
