### ISSUE TITLE
Anchor to the same url trigger the page transition

### ISSUE THREAD

**Issue by Liroo** [barbajs/barba#404]
## Description

Hey Barba,
It might be an issue with some format of url containing anchor link.
Clicking a link such as `https://toto.com/about/#anchor` coming from `https://toto.com/about` will reload the page.

It is simple to fix checking the trailing slash at the end of the url of the current page or the slash before the next anchor but it might be tricky.
It is not an important bug but in fact, I spent some time to know why there was such this behavior.

### Details

In this use case, when you check the data in an hook:
- `current.url.path !== next.url.path`

Where we can get

- current.url.path === `/toto/about`
- next.url.path === `/toto/about/`

Be careful about the trailing slash, this small difference made trigger the transition.

When I will get time, I will check in the source of barba for a fix.

### Expected behaviour

Handling the anchor natively.

### Actual behaviour

An unexpected page transition handled by Barba. 

### Steps to reproduce issue [ Good To Have ]

Made a page with an anchor somewhere (let's say we are in `about` page with an anchor such as `contact`).
In the nav, set two links:
- `/about`
- `/about/#contact`

Clicking between links reload the page.

## Environment

- Barba version that exhibits the issue: 2.3.9
- Build used:
    + browser (dist/)
- Browser OS/version used: os (10.14.5 (18F132)), chrome (Version 74.0.3729.169)

**Comment by oguilleux** [comment]
Have you tried just using the anchor in the link ? Like so :

`<a href="#anchor">My link</a>`

**Comment by Liroo** [comment]
This is not possible, the anchor is itself an item of the menu and link to a specific page

**Comment by c0mrx** [comment]
What I usually will do is create my own scroll to anchor function. Something like in the answer on [this page](https://stackoverflow.com/questions/25987451/javascript-smooth-scroll-explained).

Another option would be to have barba ignore links that contain anchors.

**Comment by Liroo** [comment]
No that's not really the problem. I've made my own anchor function on the scroll is fine now.

The bug is that barba does a differentiation between url WITH and WITHOUT the trailing slash. That's not a big deal as you just have to care about the trailing slash in URL but that was a pain when I didn't knew where it came from. :)

**Comment by c0mrx** [comment]
@Liroo Ahh I understand! Sorry about that.

**Comment by jonasfeige** [comment]
I have a similar issue with a simple scroll-to-top-button.
The scrolling actually takes place but I still get a page transition during the process.

Any chance if @Liroo ’s fix going live soon?

**Comment by oguilleux** [comment]
Hi there,

I'm having a problem now with this kind of link : `<a href="#anchor">My link</a>`. It triggers the page animation as well as scrolling to the appropriate element.

Thanks for your help.
