### ISSUE TITLE
Google Analytics not tracking after initial page

### ISSUE THREAD

**Issue by ajc2019** [barbajs/barba#405]
Using the latest GA tracking code on a site using Barbajs but cant seem to get it to track past the first page.

It will track each page if you refresh after load but not when just moving through the pages, ie the user path.

Any fixes out there?

**Comment by JackThomas** [comment]
Thats down the the way Barba gets/sets the page. Its never reloading fully so the analytics code is never re-run.

You will need to create and send a new analytics page view with javascript on Barba state change.

This should help - https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications
