### ISSUE TITLE
Problems with barba.js V1 and smooth-scrollbar.js

### ISSUE THREAD

**Issue by pjguzloz** [barbajs/barba#406]
Hello,

First of all, thank you for the bookshop that you created Barba.js.

I am new in this world and I feel that my English is so bad.

I'm having problems making a web with beard.js and smooth-scrollbar.js. The problems are:

1. Go back to the previous or next page through the buttons of the browser, I do not do the animation as in your demos / examples from the web barbajs.org or webs built with your library. I read a lot about your subjects, but nothing! And I see many websites that do not have more code added than me, even less! (And I tried things from slacks in slack / here and nothing, they do not go!)
2. When going from one page to another that uses the plugin "smooth-scrollbar.js" it does not load (both use the plugin), while from one that does not use the plugin to another that uses it is loaded without problems .

Thank,

**Comment by bezgodov** [comment]
I was having a small problem with these combinations. There problem was my main container didn't have fixed sizes and therefore there was no scroll with smooth-scrollbar library.

This is a quote from https://idiotwu.github.io/smooth-scrollbar/
> Likes the native scrollbars, a scrollable area means the content insides it is larger than the container itself, for example, a 500*500 area with a content which size is 1000*1000:

I didn't get your problem exactly, maybe this will help, maybe not :)

**Comment by pjguzloz** [comment]
Thank you very much @bezgodov,

I'll try to solve it from there, but I think that problem solves it.

First problem solved!

The second: is that between the transition of the pages that have enabled the "smooth-scroll.js" (having all "barba.js" V1) activates the plugins only in the first one that entered, but if the next page to the that transit tb has those plugins ("smooth-scroll.js"), "smooth-scroll.js" is not activated. For this I have to perform a reload of that page.

I hope you have explained me well.

Greetings and thank you!

**Comment by bezgodov** [comment]
> The second: is that between the transition of the pages that have enabled the "smooth-scroll.js" (having all "barba.js" V1) activates the plugins only in the first one that entered, but if the next page to the that transit tb has those plugins ("smooth-scroll.js"), "smooth-scroll.js" is not activated. For this I have to perform a reload of that page.

Are u sure u reinitialise smooth-scroll after transition is finished?
Cause it needs to recalculate 'viewport' of your next page
