### ISSUE TITLE
Namespaced transition to only shows when animation is complete

### ISSUE THREAD

**Issue by lmartins** [barbajs/barba#407]
Hi, first things first, thank you so much for this library. I've been keeping on eye on it since v1, and super excited to work with it on my projects from now on.

I am however struggling with two unrelated aspects:

**1. Page does not show until animejs complete promise is returned**
I have a simple setup, based on your Codepen examples, where I run a transition based on namespace declarations. It looks like this:

```js
barba.init({
        debug: true,
        transitions: [
          {
            sync: true,
            name: 'landingpage',
            enter: ({ next }) => appear(next.container),
            appear: ({ current }) => appear(current.container),
            to: {
              namespace: ['landing']
            }
          }
        ]
      });
```

My understanding is that the appear animation would run the same way either I reload the landing namespaced page, or when I navigate from a different page to this one. However, what I'm seeing is that the animation is shown when I reloading the landing page, however if I navigate from a different page to this one the loading takes a second or so, and when the page is finally revealed the animation is already complete, so I think it is waiting for the animation to complete before transitioning.

Am I misinterpreting this?

The second issue, and I apologise as it is unrelated but perhaps something simple, do I need to  dispatch the DOM content loaded manually for libraries to kick-in?

**Comment by thierrymichel** [comment]
Hi @lmartins, thanks for giving a try to the beta! :)

I tried to reproduce your scenario. Here is my code:

```js
import barba from '@barba/core';
import anime from 'animejs';

barba.init({
  debug: true,
  transitions: [{
    sync: true,
    to: {
      namespace: ['landing'],
    },
    appear({
      current,
    }) {
      const targets = current.container;
      const a = anime({
        targets,
        opacity: [0, 1],
        duration: 1500,
        easing: 'linear',
      });

      return a.finished;
    },
    enter({
      next,
    }) {
      const targets = next.container;
      const a = anime({
        targets,
        opacity: [0, 1],
        duration: 1500,
        easing: 'linear',
      });

      return a.finished;
    },
  }],
});
```

I didn't notice any issue.
What's expected:
- When loading the page for the first time, your transition is found and `appear` is used.
- When going to another page (namespace is different from `landing`), no transition is found, containers are switched.
- When going to a page with namespace `landing` (or going back), your transition is found and `enter` is applied.

Note that, as there is no `leave` hook, during the last step (going to `landing`), `current` container still visible/displayed during the `enter` transition of the `next` container.
So you should probably add "something" within a `leave` hook…

For the second issue, it's always a good idea, when your code is supposed to manipulate DOM elements (like barba.js does), to be sure that those elements are available…

Hope it helps.

**Comment by lmartins** [comment]
Hey @thierrymichel, thanks so much for the detailed answer.
I think I need to get CodePen pro or something to be better at setting up a test case for these things. Thanks so much for testing it though.

That does help clear things, I was misinterpreting the role for each hook, and I was reading `leave` as the animation to be applied when `landing` would be leaving the screen.

As for the second question, I meant for code I don't have control that relies on things like jQuery's document ready. What I've found was that they don't run when we switch routes, I'm guessing no easy way around that one right?

**Comment by thierrymichel** [comment]
You should use `views` to init code related to the pages...

**Comment by lmartins** [comment]
@thierrymichel I am, its just that in this case I don't have control over the lifecycle of those components. This is a WordPress build running jQuery code from plugins, and that's where it's failing. Thanks so much for all the feedback Thierry, much appreciated. I'll try find a workaround.
