### ISSUE TITLE
Problems using `@barba/css` with JS hooks

### ISSUE THREAD

**Issue by lmartins** [barbajs/barba#412]
Hi,

I’m having trouble get a simple page transition to happen and I’ve tried every hook available without getting it to work. I assume I’m misinterpreting they way the library is supposed to work, I would love your help in order to determine whether or not that is the case.

I’m trying to animate the transition between pages of the same namespace, and for that I have the following code:

```js

      barba.init({
        debug: true,
        transitions: [
          {
            name: 'navigate-single-views',
            from: {
              namespace: ['layoutC']
            },
            to: {
              namespace: ['layoutC']
            },
            beforeLeave({ current }) {
              const targets = current.container.querySelectorAll('.wp-block-layout-lodging-single > div');
              const a = anime({
                targets,
                opacity: [1, 0],
                translateY: [0, -100],
                duration: 400,
                easing: 'linear',
                delay: anime.stagger(100)
              });
              return a.finished;
            },
            appear({ current }) {
              const targets = current.container.querySelectorAll('.wp-block-layout-lodging-single > div');
              const a = anime({
                targets,
                opacity: [0, 1],
                duration: 500,
                easing: 'linear'
              });
              return a.finished;
            }
          }
        ]
      });

```

The out transition runs fine, but for the life of me I can’t get it to render a enter animation as I would have hoped for.

I’ve tried several of the available hooks, replaced `current` with `next` on the data passed to the hook, nothing seemed to work. 

Can you help please?

**Comment by luruke** [comment]
Hello @lmartins , can you share a live link/codepen/example?

It might just be a CSS issue, make sure your containers are "overlapping", if you want to achieve a cross-fade effect.

**Comment by lmartins** [comment]
@luruke thank you for reaching out. 
From what you describe, I assume at some point both the previous and next pages are on the DOM at the same time, is that the case.

I’ve tried to reduce a test case in codesanbox to have transitions between pages but that isn’t quite working:
https://codesandbox.io/s/vibrant-rosalind-350mr?fontsize=14

Perhaps you could let me know why on the following code I see the logs for both all hooks except for `enter`:

```
            beforeLeave({ current }) {
              console.log('BEFORE LEAVE');
              const targets = current.container.querySelectorAll('.wp-block-sundance-layout-lodging-single > div');
              const a = anime({
                targets,
                opacity: [1, 0],
                translateY: [0, -100],
                duration: 400,
                easing: 'linear',
                delay: anime.stagger(100)
              });
              return a.finished;
            },
            beforeEnter({ next }) {
              console.log('BEFORE ENTER');
              next.container.classList.add('is-loading');
            },
            enter({ next }) {
              console.log('ENTER');
            },
            afterEnter({ next }) {
              console.log('AFTER ENTER');
              next.container.classList.remove('is-loading');
              const targets = next.container.querySelectorAll('.wp-block-sundance-layout-lodging-single > div');
              const a = anime({
                targets,
                opacity: [0, 1],
                translateY: [100, 0],
                duration: 400,
                easing: 'linear',
                delay: anime.stagger(100)
              });
              return a.finished;
            }
```

**Comment by thierrymichel** [comment]
Hi @lmartins,

I will check this. Unfortunately, with your codesandbox, I get a `406` error :)
Quick question : are you using `@barba/css`?

**Comment by lmartins** [comment]
Hey @thierrymichel sorry about that. Let me try setup a better demo.
I am indeed using `@barba/css`. Idea was to setup a default transition for when no `namespace` matches the current navigation.

**Comment by thierrymichel** [comment]
@lmartins I think the problem comes from using both "JS" transitions with `@barba/css`.
TBH, I didn't foresee this scenario… 😄

Actually, when using `@barba/css`, `leave` and `enter` JS hooks are "replaced".
The reason is that we need to use CSS `transitionEnd` instead of a promise based duration.
That's why `enter` is not called…
I've already tried to "override" them but without success (execution context problems leading to some ugly implementation, as I remember).

A solution could be to add some "resolution" param (like `namespace` or `route`): 
```
transitions: [{
  css: true, // or a string to be used as a prefix `.prefix-leave-xxx`, probably better
}]
```
Keeping a "sync" execution of `leave` and `enter` hooks.
It should be quite easy to implement.

Do you think it could solve your "use case"?

**Comment by lmartins** [comment]
@thierrymichel ahhh, that probably explains the trouble I was getting to getting the hooks to fire. Let me run a few tests and I'll confirm. Thanks so much for helping with this Thierry!

**Comment by thierrymichel** [comment]
Just to be clear, the `css` doesn’t exist (yet).
But could be a feature request... 😊
