### ISSUE TITLE
Remove version messages on the console

### ISSUE THREAD

**Issue by takamoso** [barbajs/barba#415]
By default, option `debug` is `false`. But the following messages appears on the console in Chrome DevTools.

```
[@barba/prefetch]  2.1.5
[@barba/core]  2.3.12
```

It seems to me like a bug. Are there any ways to remove this messages?

**Comment by luruke** [comment]
Hello @takamoso ,
in effect the version is always displayed.

@thierrymichel @xavierfoucrier – what you guys think about it?

**Comment by xavierfoucrier** [comment]
Hi @luruke,

I have already discussed that point with other **Barbas** on Slack, but for now, @thierrymichel has setup the `core` to print the version as "_unremovable log_" in the console, see https://github.com/barbajs/barba/commit/24dd2eac6556d54c21663bf7f10efb3d0d6628d4.

From my point of view, **no message should be displayed in a production environment**. For development purpose, it is gracefully accepted.

But... may be there is a specific goal behind this decision.

**Comment by luruke** [comment]
I see @xavierfoucrier , thanks!
I'll keep this ticket open as reminder to change this behaviour
