### ISSUE TITLE
Multiple containers, page transitions and overlays

### ISSUE THREAD

**Issue by jeroenbraspenning** [barbajs/barba#416]
I'm working on a project and was planning to use Barba.js, but i've stumbled upon an implementation issue and i was wondering what your thoughts are.

I want to use barba.js for both regular page transition but also for "overlay" layers.
The overlay layers are triggered by specific links which will be opened in a layer on top of the rest of the content. My idea was to use two barba containers, in which one of the two was used as the overlay container and use the namespace and "prevent" methodology to differentiate which barba instance should react. 

Sadly the prevent function does not receive the namespace.

Now i am planning  to use barba.js for the page transition and built something custom for the overlays but just wanted to post this issue here in case someone else has a better understanding of barba and knows a workaround.

**Comment by luruke** [comment]
Hello @jeroenbraspenning ,
by design, the library works as progressive enhancement, that being said, this overlay you want to open is a "real" page being served from the web browser?

**Comment by jeroenbraspenning** [comment]
Hello @luruke,

Yeah it can be any page of the current website, which will be overlayed partly with a black transparent backdrop.
The problem with using the main barba container is that "previous" page container will be removed, and i'd like to keep the previous page visible through the backdrop.

**Comment by luruke** [comment]
I see @jeroenbraspenning , what do you expect when the user reload the page, or access directly on that URL?

Still the overlay, or just the new page "fullscreen"?

**Comment by jeroenbraspenning** [comment]
When you refresh the page or visit the url directly you just get the "new" page fullscreen.

**Comment by luruke** [comment]
I see, I believe @gfnool did something similar with barba v1, maybe he can help you...

At the moment the solution I see is to prevent the link and manually show the "layer" and update the URL.

**Comment by jeroenbraspenning** [comment]
Yeah, i probably create a seperate module for loading and caching the pages and use it to populate the overlay.

Many thanks for your help!
