### ISSUE TITLE
Uncaught TypeError: Cannot read property 'baseVal' of null

### ISSUE THREAD

**Issue by xavierfoucrier** [barbajs/barba#418]
It seems that `@barba/prefetch` throw an exception when trying to prefetch `<a>` in-viewport elements that does not contain `href` attribute. Those links should be ignored by the module.

Here is the stack trace:
```js
barba.umd.js?:formatted:489 Uncaught TypeError: Cannot read property 'baseVal' of null
    at A.getHref (barba.umd.js?:formatted:489)
    at eval (barba-prefetch.umd.js:1)
    at NodeList.forEach (<anonymous>)
    at t.timeout (barba-prefetch.umd.js:1)
```

:coffee: :wink:

**Comment by thierrymichel** [comment]
Fixed: https://github.com/barbajs/barba/commit/e434ecb299ad0f9ca12f687981c2201a0bc85565

**Comment by xavierfoucrier** [comment]
Oh yeah! Thanks for the fix. :tada:
