### ISSUE TITLE
Updating current menu item's class breaks transitions

### ISSUE THREAD

**Issue by Leisors** [barbajs/barba#419]
## The problem

Howdy, everyone.
I've stumbled on the strangest bug.

The bug is triggered when adding a class to an element (external to Barba's container). That small line of code completely breaks Barba's transitions. 

## Description
Specifically, I'm trying to change the active menu item on page change, with a really simple function:
```javascript
updateCurrentItem(data) {
    const currentClass= 'current-menu-item';
    const currentItem = $(`.${currentClass}`)[0];
    const nextPath = data.next.url.path;
    const nextItem = $(`.menu-item a[href$="${ nextPath }"]`)[0];

    currentItem.removeClass( currentClass );
    nextItem.parentElement.addClass( currentClass );
}
```
The last line of the function (adding the class on the parent element) triggers the following errors:
> [@barba/core]  Error: Transition error [page][enter] at barba.umd.js:1
> [@barba/core]  Error: Transition error at barba.umd.js:1

### Details
Also, here's how that function gets called:
```javascript
const header = new Header();
header.init();

barba.hooks.afterEnter( (data) => {
    header.updateCurrentItem(data);
});

barba.init({ debug: true });
```

### Expected behaviour

When clicking on a link, the current page's content should be replaced with the target page's content.

### Actual behaviour
- The first time you click on a link, the next page's container will be added but the current one won't be removed.
- The following clicks won't produce any change, except triggering the errors. 

---

## Environment
Built on a Roots' Sage 9 Wordpress Theme

- Barba version that exhibits the issue: "@barba/core": "^2.3.12"
- Build used: not sure about what I'm being asked here.
- Browser OS/version used: the error presents itself in all major browsers.

**Comment by thierrymichel** [comment]
Hi @Leisors ,

Can you check `nextPath` and `nextItem` values ?

**Comment by Leisors** [comment]
Everything looks fine:
- `nextPath` contains the correct path,  `"//localhost:3000/services/designers/"`
- `nextItem` contains the correct DOM element

Both testing it outside of the live server and using vanilla JS queries result in the same behaviour.

**Comment by ouun** [comment]
@Leisors I just had the same issue within a similar environment (Sage 9).
However I was able to solve it and took your code example as reference:

```
  // After leave hook
  barba.hooks.afterLeave(data => {
    // Update the active menu item classes
    if ( data.next.url.path ) {
      const activeClass = 'active';

      $( '.menu-item.' + activeClass ).each( function() {
        $(this).removeClass(activeClass);
      });

      $(`.menu-item > a[href$="${ data.next.url.path }"]`).closest('.menu-item').each( function() {
        $(this).addClass(activeClass);
      });
    }
  });
```

Maybe it helps.

**Comment by Leisors** [comment]
Dude! Your code _does_ work, and by trying to understand _why_ I've managed to fix mine.

Here's the corrected function:

```javascript
updateCurrentItem(data) {
    const currentClass= 'current-menu-item';
    const currentItem = $(`.${currentClass}`);
    const nextPath = data.next.url.path;
    const nextItem = $(`.menu-item a[href$="${ nextPath }"]`);

    currentItem.removeClass( currentClass );
    nextItem.parent().addClass( currentClass );
}
```

The differences are here, in the queries:
```diff
-       const currentItem = $(`.${currentClass}`)[0];
+       const currentItem = $(`.${currentClass}`);

-        const nextItem = $(`.menu-item a[href$="${ nextPath }"]`)[0];
+        const nextItem = $(`.menu-item a[href$="${ nextPath }"]`);
```

and here, in the selection of the parent element:
```diff
-        nextItem.parentElement.addClass( currentClass );
+        nextItem.parent().addClass( currentClass );
```

I have no idea about the reason why those errors make Barba act that way, but at least now it's working. 

Cheers!

**Comment by ouun** [comment]
Great. So I guess my usage of `.each()` is obsolete as e.g. `$(`.menu-item a[href$="${ nextPath }"]`)` get each link with that URL anyway... So going with yours. :)

**Comment by Louboutin1017** [comment]
@ouun and @Leisors 

All your codes works on Barba v2, but its targets all menu-items on the main-page.

Meaning all nav menu links are highlighted as active, on the main homepage.

I use css to fix it, but i want to learn, and fixing it on the same js code is more professional.

please anyone respond.
