### ISSUE TITLE
Manage previous scroll position with back/forward browser buttons

### ISSUE THREAD

**Issue by thierrymichel** [barbajs/barba#423]
N2S:
- https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration
- store more information in history

**Comment by xavierfoucrier** [comment]
Hi,

In my current project, I disable the scroll restoration **after the Barba init stage**, like this:

```js
if ('scrollRestoration' in history) {
  history.scrollRestoration = 'manual';
}
```

Then in the `enter` hook, just after removing the current container, I **scroll the window to the top** to properly display the next page:

```js
current.container.remove();
window.scrollTo(0, 0);
```

It could be very useful to have a property to manage this behavior inside Barba. :wink:

**Comment by thierrymichel** [comment]
For the moment, I've added a `scroll` property to the `history` items.
With trigger `back`|`forward`, you can use `scroll.x|y` from `barba.history.current|previous`.

**Comment by xavierfoucrier** [comment]
Perfect! I will try it soon, in vacation for now ^^. Thanks again :wink:

**Comment by xavierfoucrier** [comment]
Hi @thierrymichel!
Back from vacation, I will take time to update the doc soon :smile:

Perfect update with `back|forward` values :+1:

**Comment by xavierfoucrier** [comment]
Perfect fix!
If we have new issues regarding back/forward browser buttons, we will refer to this thread. :v:

**Comment by artistro08** [comment]
@thierrymichel I'm having trouble wrapping my head around this. Could you post an example on how we can restore the scroll position on the browser back button? while `history.scrollRestoration = 'manual';` is in place?

So far I got 

```
barba.hooks.before(() => {
   window.scrollTo(barba.history.current.scroll.x, barba.history.current.scroll.y);
});
```

**Comment by psntr** [comment]
would appreciate an example of how you handle that, I managed to solved that with the following code, but I'm sure there is better way:

```
if ('scrollRestoration' in history) {
  history.scrollRestoration = 'manual';
}
let linkClicked = false;
let scrollY = false;

barba.hooks.beforeEnter(() => {
  if (linkClicked) {
    // Scroll top of page
    window.scroll(0, 0);
  }
  else if (scrollY) {
   // Scroll back to Y position
    window.scroll(0, scrollY);
    scrollY = false;
  }
  else {
    window.scroll(0, 0);
  }
});

barba.hooks.afterLeave((data) => {
// Register data trigger
  if (data.trigger === 'back') {
    linkClicked = false;
  } else {
    linkClicked = true;
  }
})
barba.hooks.beforeLeave(() => {
  // Register last scroll Y position
  if (!scrollY) {
    scrollY = barba.history.current.scroll.y
  }
})
```

**Comment by artistro08** [comment]
After doing a little more investigation, I found this way to be the best




```
history.scrollRestoration = "manual";`

var scrollPosY = 0

barba.hooks.enter((data) => {
  if(barba.history.current.scroll.y > 0) {
    scrollPosY = barba.history.current.scroll.y;
  }
});

barba.hooks.after((data) => {
  if(data.trigger !== "back") {
    window.scrollTo(0,0);
  } else {
    window.scrollTo(0, scrollPosY)
  }
});
```

**Comment by chrirauch** [comment]
if someone is interested, i took artistro08s approach and extended it to save the scroll position in an array. this way the scroll position is also correct for subsequent history back navigations

`history.scrollRestoration = "manual";`

var scrollPosY = [0]

barba.hooks.enter((data) => {
  if(data.trigger !== "back") {
    scrollPosY.push(barba.history.current.scroll.y);
  }
});

barba.hooks.after((data) => {
  if(data.trigger !== "back") {
    window.scrollTo(0,0);
  } else {
    window.scrollTo(0, scrollPosY.pop())
  }
});`
