### ISSUE TITLE
vanta.js (three.js) not working after page transition

### ISSUE THREAD

**Issue by kumaaa** [barbajs/barba#424]
Hello,

sorry I'm a beginner and have a question that bugs me much...

so I want to use Vanta.js, which is a script for animated backgrounds using three.js
https://vantajs.com

I want this script to be executed in another page than the index, lets call it work-page

if I go from index to work-page, the vanta background is not showing up

but when I refresh the work-page, its visible

the init for vanta.js is

`    VANTA.WAVES({
        el: "#vanta-output",
        color: 0xb38218,
        shininess: 40.00,
        waveHeight: 10.50,
        waveSpeed: 0.85  
  });`

how come?

**Comment by xavierfoucrier** [comment]
Hi @kumaaa,

You should init your library in the associated page using Barba `views`: https://barba.js.org/docs/v2/user/core.html#view-object.

```js
import barba from '@barba/core';

barba.init({
  views: [{
    namespace: 'work-page',
    beforeEnter() {
      VANTA.WAVES({
        el: "#vanta-output",
        color: 0xb38218,
        shininess: 40.00,
        waveHeight: 10.50,
        waveSpeed: 0.85
      });
    }
  }]
});
```

Don't know what kind of transition you are doing, but be sure that your `#vanta-output` element is present before entering the next page.

> Note that you can use another hook to init your library

**Comment by kumaaa** [comment]
im using barba v1 and i tried to copy your code like this

`    <script>
var Vanta = Barba.BaseView.extend({
        views: [{
        namespace: 'work-page',
        beforeEnter() {
        VANTA.WAVES({
        el: "#vanta-output",
        color: 0xb38218,
        shininess: 40.00,
        waveHeight: 10.50,
        waveSpeed: 0.85
      });
    }
  }]
});
            
Vanta.init();
        
            </script>`

but it doesnt work either

**Comment by xavierfoucrier** [comment]
@kumaaa,

This is **Barba v2 code syntax**... that's why :wink: 
Here is the docs for `View` with Barba v1: https://barba.js.org/v1/views.html

Should work fine! :v:

**Comment by kumaaa** [comment]
well im using this syntax now but it still not appearing on work-page
the canvas isnt even rendered in the dom but console doesnt say anyhting

used this now 
`                    <script>
                            var Vanta = Barba.BaseView.extend({
                                namespace: 'work-page',
                                onEnter: function() {
                                    VANTA.WAVES({
                                    el: "#vanta-output",
                                    color: 0xb38218,
                                    shininess: 40.00,
                                    waveHeight: 10.50,
                                    waveSpeed: 0.85
                                  });
                                }
                              });
                            Vanta.init();
                    </script>`

**Comment by xavierfoucrier** [comment]
@kumaaa do you have the good html syntax?

You should have `barba-wrapper` and `barba-container` id/class in your html document, then have `data-namespace="your-page-name"` set on every page to allow Barba to associate the namespace to the view.

Check the installation section if you missed something: https://barba.js.org/v1/installation.html

:wink:

**Comment by kumaaa** [comment]
everything else is working fine and fast
just this animation wont appear after i transition to work-page
there are no errors or something

it just appears if i ctrl+r refresh the site

**Comment by kumaaa** [comment]
well i tried a bit with your information and i managed to make it work
thanks a lot!!

**Comment by xavierfoucrier** [comment]
@kumaaa perfect! Thanks for the close :+1:
