### ISSUE TITLE
Wordpress and barba V2

### ISSUE THREAD

**Issue by dngraphisme** [barbajs/barba#425]
Hello to all the barbas user :)

I have some questions about V2>

I am putting together a custom wordpress theme, I have put barbajs2 in it and I have no problem with the transition.

Where I have a problem>

1. I think it does not load custom inline css or js with a builder page like Visual Composer.

2. I have the same beug with the grid masonry of this plugin> https://connekthq.com/plugins/ajax-load-more/ I need to reload the page manually to view the grid :/

Has someone already implemented V2 on Wordpress?

Normally on the V1, I load my functions js in the "views" but it's different on WP...

Thanks in advance :) Nicolas

**Comment by thierrymichel** [comment]
Hi @dngraphisme,

- We do not use Visual Composer… :/ Does it inject `style`/`script` tags inside the barba container ?
- We use to add `[data-barba-container="template-namespace"]` on every template/page, then you can use `views` like in the `v1`. If it's more "global", `barba.hooks` should be your friend.

Hope it helps…

**Comment by dngraphisme** [comment]
Hi thierry,

First of all thank you for your reply. It is thanks to Xavier that I was able to understand the PJAX of Barba.

So I'll explain>

this morning I'm back on the V1 because I think there is more topic provided for Wordpress above.

I have no problem except that it can not redeclare js like this one> https://connekthq.com/plugins/ajax-load-more/

My grid is in place in the barba container but impossible to load the init of the plugin. I suddenly asked support advice.

Regarding visual composer, if I use a page builder it is later to be faster in terms of front in body pages.

Actually VC uses inline code. The only track I have is this one> https://codecanyon.net/item/visual-composer-page-builder-for-wordpress/242431/comments?from_buyers_and_authors_only=0&page=3&term=ajax&utf8=%E2 9C% 93%

Hello, The plugins are loading the style / scripts for the elements present on the page. In case of ajax, if only a single call is made initially, it will fail to render the style / scripts for inner pages. In this case, you can make a separate ajax call for each page.

but good a bit difficult to understand.

In sum I did this in my barbajs for my transitions (if I take the example of the blog)>

var Blog = Barba.BaseView.extend ({
    namespace: 'archive.php', onEnter: function () {
        mouseKosmo ();
        blogKosmo ();
    }
});

Do you advise me to go back on the V2 barba in these cases?

thanks again

**Comment by dngraphisme** [comment]
Hello **@thierrymichel** ,

1. Actually Visual composer injects CSS inline if we customize the blocks in BO.

I'm thinking of switching to another more powerful builder page. I hope I will not have any problem with Barba :)

2. Thanks, actually with the views it's great. I think I still stay on the V1, I have trouble with the V2 and documentation.

Thank you again for your response and thank you for this beautiful library JS !
