### ISSUE TITLE
Re-Init JS

### ISSUE THREAD

**Issue by carlm-fieldtrip** [barbajs/barba#426]
When I used v1 I was able to re-initialize my other js files after a transition. With v2 how would one go about re-initializing other javascript functions? For example, I use a scrolling/parallax plugin. After a page transition that plugin no longer works. I'm have trouble reading the v2 docs to understand how I would re-init that plugin. Any insights would be very much appreciated.

**Comment by prilcool** [comment]
@carlm-fieldtrip  can you pliz give me an exmple on how you were able to reinitialize your Js files in V1  ?  I'm having a real hard time , I cant even get my  <script> </script> files reinitialize in v1 .
would really appreciate your help or link to a github of example.

**Comment by thierrymichel** [comment]
@carlm-fieldtrip you should use [views](https://barba.js.org/docs/v2/user/core.html#syntax) or [global hooks](https://barba.js.org/docs/v2/user/core.html#hooks)
