### ISSUE TITLE
Using Barba with CSS transitions

### ISSUE THREAD

**Issue by danielschmid** [barbajs/barba#427]
I‘ve been using Barba JS version 2.x with JS animations before but I’m running into trouble when using CSS transitions. 

I’m currently implementing Barba for an existing site. 

How can i configure Barba to wait until CSS transition has finished on an element that is outside of the Barba wrapper. For example my navigation ?

Is there any further documentation on this topic ?

**Comment by thierrymichel** [comment]
Hi @danielschmid,

I guess you're not using `@barba/css` (which is for CSS only transition on the barba container).
Have you tried, from your leave/enter, to listen to `transitionend`, then do your  transition stuff?

**Comment by danielschmid** [comment]
Hi @thierrymichel 

I’m not using '@barba/css' only the '@barba/core'

What i’m trying to replicate with Barba is the current behavior.

```
$('.navigation__link').click(function(event) {
    event.preventDefault();
    $(this).addClass('is-animating').one(transEndEventName, function(e) {
        $(this).removeClass('is-animating');
        doLoadUrl($(this).attr('href'));
    });
});
```
If the link gets a click the element gets animated. I’ve animation is over load the url manually via a custom function that Makes an Ajax call via Jquery load(). I do have the problem of handling browser history wich i try to solve using Barba.

**Comment by thierrymichel** [comment]
@danielschmid You can do a barba transition programmatically with [`barba.go()`](https://barba.js.org/docs/v2/api/classes/core.core-1.html#go).
This could replace your `doLoadUrl()`.
Do not forget to use `[data-barba-prevent]` on your links, so barba won't start the auto transition.

As mentioned above, you can also try to listen to `transitionend` from your `enter` hook, then do your transition stuff (not tested).

Hope it helps!

**Comment by danielschmid** [comment]
@thierrymichel  Didn’t know about barba.go(). Seems to be the best solution for my project.
Thanks  a lot.
