### ISSUE TITLE
Play transition if click on text link

### ISSUE THREAD

**Issue by imstanleyyeo** [barbajs/barba#429]
Hi @luruke,

Thanks for this amazing library. I know this is the default behaviour of barba but can we play the transition instead of a normal page load? How do we do this?

Thank you.

**Comment by xavierfoucrier** [comment]
Hi @imstanleyyeo!

If you want to play a transition when clicking on a specific button or element, you can simply use this:

```js
document.querySelector('.go-next-page').addEventListener('click', () => {
  barba.go('next-page.html');
});
```

> Note that this will bring you to the next page, and will finally "load" it. There is no other way to play a barba transition and not load a page.

Hope this help! :wink:

**Comment by imstanleyyeo** [comment]
Thanks @xavierfoucrier for taking the time to reply. 
Barba works for my static site however when i implement this on wordpress, only menu links activates the transition but not text link in content. Did you have similar experience that why this is happening?
Thanks again and appreciate your help!

**Comment by xavierfoucrier** [comment]
Ok. Links in page content should work the same way navigation links works :confused:

**Comment by thierrymichel** [comment]
Hi @imstanleyyeo,

Transitions should work "out of the box" when using barba.
Any valid link should trigger a transition…
If not, please share some repo, url, code example, …
