### ISSUE TITLE
Problem with Nav menu with anchors on homepage

### ISSUE THREAD

**Issue by iamalessiopaoletti** [barbajs/barba#431]
Hi! 
It's my first project with barba.js V2,
I have a problem with the navigation menu links,
Most of the links are anchors in the home page and when i try to click on an anchor from other page barba.js send me to homepage correctly but at the top of the page and not at the anchor position, and another problem it's that:

example
in index.html
href="../it/#chi-siamo"

on other page (serivizi.html) it become
href="../it/servizi.html#chi-siamo"      instead of     "../it/index.html#chi-siamo"

but if I reload the page servizi.html the menu links are correct and the anchors works well

[https://alessiopaolettidesign.it/ph/it/](url)

how can i solve?
Thanks!

**Comment by xavierfoucrier** [comment]
Hi @iamalessiopaoletti,

Sorry for the laaaaate reply :roll_eyes:  ...

Is your problem fixed at this time?
Because it seems to properly work right now on your site.

Thanks for the feedback.

**Comment by iamalessiopaoletti** [comment]
Hi!
Sorry but i don't have fix this problem with barba..js,

In the site I have used swup.js and I have fix the problem with the slash without dots after read the doc.
And swup.js have differents plug-in to solve other problems like the head and the scroll position and the height of the page.

**Comment by xavierfoucrier** [comment]
Hi @iamalessiopaoletti,

Fine. Thanks for taking the time to give a feedback :wink:
