### ISSUE TITLE
Request: Add direction to 'popstate' trigger

### ISSUE THREAD

**Issue by c0mrx** [barbajs/barba#435]
I'm wondering if there's a way to implement a check to tell what direction the user is navigating using popstate. Currently, the developer has to code a custom handler for this and it can be a little confusing as there is not a lot of documentation for `barba.history`.

Right now we can use the `data.trigger` to show popstate as a trigger, so I'm wondering if there's a way to tap into the `barba.history` array and know which direction the user is navigating. This way you could test it as such: 

```
if (data.trigger == 'popstate' && data.direction == 'forward') {
  // Forward was clicked
} else {
  // Back was clicked
}
```

If I'm missing an easy way to do this with v2, please advise! 😄

**Comment by thierrymichel** [comment]
@c0mrx `data.trigger` have new values : `back` or `forward`…

**Comment by c0mrx** [comment]
@thierrymichel That was fast! 

I just tested it and it's working well. Thank you! :smile:
