### ISSUE TITLE
@barba/css transitions timing

### ISSUE THREAD

**Issue by heidiyee** [barbajs/barba#437]
I'm using @barba/core and @barba/css to do some simple fade in/fade out animation. I've read that @barba/css does not working with JS transitions, so I deleted all JS transitions. 

The css transitions are working, but the timing is off. Sometimes the transition plays fully and sometimes it's cut off prematurely. Any suggestions would be appreciated.

**Comment by thierrymichel** [comment]
Hi @heidiyee,

Some reproductible example or code would be appreciated!
Thanks in advance.

**Comment by marekalgoud** [comment]
Hi,
I face the same issue. In my case it seems that barba/css is not compatible with aos  library (https://michalsnik.github.io/aos/). If I disable this library, page transition works fine. Together, the barba-enter-active transition doesn't work well (timing is very short).

Is there a way to make theses two libraries work together ?

Thanks for your support.

**Comment by xavierfoucrier** [comment]
Hi @heidiyee,

Can you please take the time to share a reproductible repo?
Thanks :wink: 

> @marekalgoud last commit to aos was in 2018: doesn't know if it is supported anymore... if your transitions works fine, the issue is not barba related

**Comment by dan9b6** [comment]
Hello,

It doesn't seem that Barba and Aos work together. Is there a solution to this at all?

Thanks :)

**Comment by vladninja** [comment]
I am solved issue with AOS by adding:

```
const nextAOS = data.next.container.querySelectorAll(".aos-animate");

for (let i = 0; i < nextAOS.length; i++) {
    nextAOS[i].classList.remove("aos-animate");
}
```

To barba.hooks.beforeEnter hook.

And next added:

`AOS.init();`

to barba.hooks.after hook, and it works.

---

Full code:
```
barba.hooks.beforeEnter(data => {
  const nextAOS = data.next.container.querySelectorAll(".aos-animate");
    for (let i = 0; i < nextAOS.length; i++) {
        nextAOS[i].classList.remove("aos-animate");
    }
});

barba.hooks.after(() => {
  AOS.init();
});
```
