### ISSUE TITLE
Help for function() on views namespace

### ISSUE THREAD

**Issue by dngraphisme** [barbajs/barba#441]
Hello guys !

I try to go on barba v2 with a new project but I have things that I can not understand.

I have read a lot of topic on the github, codepens etc but nothing makes I am stuck at my level.

I can not understand how to initiate functions in the views of my different pages? On the V1 I had no problem but on the V2 I do not understand ....

I put the example of my code below. The goal is to do the same as on my website main> https://e-kosmo.com

Launch only specific functions for each page of a site.

I'm sorry to ask for help but honestly I really have trouble with V2 and I love the BarbaJS script. 

How to add the class to the body also according to the page in which we are ?

@thierrymichel, @xavierfoucrier  if you pass by there can you help me please ^^' ?

Thank you, Nicolas

-----

`document.addEventListener("DOMContentLoaded", function () {

    TweenMax.set('.for-transition .shape-overlays__path', {
        x: "-100vw"
    });

    barba.init({
        //timeout: 5000,
        transitions: [{
                // on leave page current
                leave: function (data) {
                    var done = this.async();

                    window.scrollTo(0, 0);

                    $('body').addClass('no-scroll');
                    $('header').addClass('no-click');

                    var tl = new TimelineMax();

                    tl.staggerTo(".for-transition .shape-overlays__path", 1.2, {
                        x: '0',
                        ease: Power4.easeInOut,
                    }, 0.25);

                    tl.to(data.current.container, 1.5, {
                        opacity: 0,
                        ease: Power4.easeInOut,
                        onComplete: done
                    });
                },

                // hello enter new page current
                enter: function (data) {
                    var done = this.async();

                    var tl = new TimelineMax();

                    tl.from(data.next.container, 1.5, {
                        opacity: 0,
                        ease: Power4.easeInOut,
                        onComplete: done
                    });

                    tl.staggerTo(".for-transition .shape-overlays__path", 1.5, {
                        x: '100vw',
                        ease: Power4.easeInOut,
                    }, 0.25);

                    setTimeout(function () {
                        $('body').removeClass('no-scroll');
                        $('header').removeClass('no-click');
                    }, 2400);

                    setTimeout(function () {
                        TweenMax.set('.for-transition .shape-overlays__path', {
                            x: "-100vw"
                        });
                    }, 4000);

                }
            },
        ], // transitions
        views: [{
            namespace: 'homepage',
            beforeEnter(data) {
                console.log("hello la home");
                // Its here or not to insert my 'function();' ?
            },
            namespace: 'groupe',
            beforeEnter(data) {
                console.log("hello la page groupe"); // Why does not the console tell me anything when I enter a page?

            },
        }], // views page
    }) //barba init

    barba.hooks.afterEnter( ( data ) => {
        // Its here or not to insert my 'function();' ? I dont understand this...
        groupePage();
    });
});

`

**Comment by xavierfoucrier** [comment]
Hi/Salut @dngraphisme,

First of all, global hooks doesn't work the same way as view hooks work.
Depending on what you need on your website you can:
- declare your function as a **global hook**: this mean that the code inside the hook will be executed each time you `enter/leave/beforeEnter/...` **any transitions**, for example if you need to update an element on the interface whatever the transition, use a global hook
- use one of the **view hook** per namespace: this mean that the code inside the hook will be executed each time you `enter/leave/beforeEnter/...` the **associated namespace**, for example if you want to display a specific message only on the homepage, use a view hook

Finally, there is many way of "coding" hooks: `async`, `Promise`, etc.. check the BarbaJS documentation:
https://barba.js.org/docs/v2/user/core.html#hooks

Hope this help :wink:

**Comment by dngraphisme** [comment]
> Hi/Salut @dngraphisme,
> 
> First of all, global hooks doesn't work the same way as view hooks work.
> Depending on what you need on your website you can:
> 
>     * declare your function as a **global hook**: this mean that the code inside the hook will be executed each time you `enter/leave/beforeEnter/...` **any transitions**, for example if you need to update an element on the interface whatever the transition, use a global hook
> 
>     * use one of the **view hook** per namespace: this mean that the code inside the hook will be executed each time you `enter/leave/beforeEnter/...` the **associated namespace**, for example if you want to display a specific message only on the homepage, use a view hook
> 
> 
> Finally, there is many way of "coding" hooks: `async`, `Promise`, etc.. check the BarbaJS documentation:
> https://barba.js.org/docs/v2/user/core.html#hooks
> 
> Hope this help 😉

Hello Xavier,

I hope you've been fine since time ?

Yes I read the doc except that I do not understand ...

In my case I want to declare a function see several per page. (As we had done on the V1)

Except that if I do this :

---
`views: [{
            namespace: 'homepage',
            beforeAppear(data) {
                console.log("hello la home");
                // Its here or not to insert my 'function();' ?
                initPage();
            },
            namespace: 'groupe',
            beforeAppear(data) {
                console.log("hello la page groupe"); // Why does not the console tell me anything when I enter a page?
                groupePage();
                initPage();
            },
        }], // views page`
---

It does not work ... There is something I do not understand at all :/

Thanks for your help again ;)

**Comment by xavierfoucrier** [comment]
Hi/Salut @dngraphisme,
I am fine thanks :smiley: !

As specified in the doc: *`views` is an `Array` of `<View>` objects*.

So, this is mainly **a syntax problem**, you should follow this pattern:

```js
barba.init({
  views: [
    <View>,
    <View>
  ]
});
```

Code example **from the documentation**:
```js
import barba from '@barba/core';

barba.init({
  views: [
    {
      namespace: 'index',
      beforeLeave(data) {
        // do something before leaving the current `index` namespace
      }
    }, {
      namespace: 'contact',
      beforeEnter(data) {
        // do something before entering the `contact` namespace
      }
    }
  ]
});
```

Please use the Slack workspace for questions that are not related to library issues next time, if possible. You can join right here: https://join.slack.com/t/barbajs/shared_invite/enQtNTU3NTAyMjkxMzAyLTI1NDIxZDZmMGJjMDlmNzFkODZmMmVmN2U2ODg2Y2M3MzczMDdjZTk5ODQwNWZkYWVlMDM5NGZiODJmMWVhODk

Take care :wink:
