### ISSUE TITLE
Return Promises in view functions

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [barbajs/barba#442]
Is there any way to use Promises in views to interrupt the flow of transitions?

For example if you put an animation in a views `beforeLeave()` function, is there any way to have that function return a Promise so that the relevant `leave` transition wont fire until the Promise is resolved?

**Comment by matthewjumpsoffbuildings** [comment]
If its by design that views cannot return Promises so that transitions wait till the view Promise is resolved, it kind of makes views redundant it seems. There is so much overlap between views and transitions you might as well just make a 'transition' object for each 'view', if you want to do fancy in/out transitions that are applied to specific items in each views html

In which case I would propose merging views and transitions into a single thing, and you have one for each view, and it defines the transitions, allows the transitions to return Promises, as well as does initialisation/destroys other stuff... otherwise what is the point of views as opposed to transitions? If its just for initialising/destroying things like sliders/form validation or whatever, but you need to do complex html dependant transitions for each view, you might as well just put it all in a bunch of targeted transitions

**Comment by thierrymichel** [comment]
Hi @matthewjumpsoffbuildings,

Thanks for using barba.js! -> [views are now "promisable".](https://github.com/barbajs/barba/commit/f11890dcd6161920afb486196466710a168fa162#diff-df15b6c41ac94da8cf78e9730a1aeb2c)

TBH, I do not use views at all (I made a small lib that allows component-oriented dev with automatic basic lifecycle). I see it like a legacy feature… 😄 

Joke aside, I know they are very useful for a lot of users.
IMHO, transitions are related to animations between pages. They are not linked to content/namespace and there are various ways to manage them.
Views are more connected to specific content/namespace and they should mainly used for simple init/destroy…

Hope this help!
Cheers

**Comment by matthewjumpsoffbuildings** [comment]
Views are now promisable? Does that mean they interact with the lifecycle of transitions? Eg if a views beforeLeave function returns a promise will the transitions leave function wait for that promise to resolve?

**Comment by thierrymichel** [comment]
@matthewjumpsoffbuildings yes.
I guess most people run synchronous code but if your view hook returns a promise, transition hook will wait.
Tell me if it works…
