### ISSUE TITLE
Lifecycle Diagram

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [barbajs/barba#443]
It would be really handy for the documentation to contain a complete lifecycle diagram, that includes both view and transition functions, for both normal and 'appear' cycles

Currently I have to fill my functions with console logs to understand when, say, the views `beforeEnter` is called in relation to the transitions `beforeEnter` etc, would be good to have a simple diagram to look at

**Comment by xavierfoucrier** [comment]
Hi @matthewjumpsoffbuildings,

Thanks for opening the issue and yes, this is one thing we discussed with thierry and other Barbas on slack. We will take time to work on it when the new website will be ready.

Thanks for your patience :wink:

**Comment by xavierfoucrier** [comment]
The diagram is build since two months approximately... but now we need a little more time to finish and release the v2 website :wink: :hourglass:
