### ISSUE TITLE
On fresh page load or page refresh url query is removed

### ISSUE THREAD

**Issue by Slgoetz** [barbajs/barba#445]
## The problem
When you go to a URL with a query attached `page.com?filter=test`, barba is removing the url Query after the page is hit.

### Expected behavior
We expect the page query to stay in the URL, and not have the page refresh/remove the query items.

Tell us what happens instead

### Code To Reproduce Issue 0

```
 barba.init({
     debug: true,
     timeout:10000,
     schema: { prefix: 'data-pjax'}
});
```

**Comment by olegatro** [comment]
same issue

**Comment by xavierfoucrier** [comment]
I can confirm the issue too.

**Comment by Mamboleoo** [comment]
Fyi the hash in the url is also impacted by this bug

**Comment by mrdoinel** [comment]
I can confirm the issue too.

**Comment by xavierfoucrier** [comment]
Related to #450.
