### ISSUE TITLE
Dom sibling is not working properly

### ISSUE THREAD

**Issue by mrsamse** [barbajs/barba#449]
I have two pages X and Y. If I go from X to Y the Y container is inserted after the X container like so:
```
<main data-barba="container" data-barba-namespace="x">
<main data-barba="container" data-barba-namespace="y">
```

When I return from Y to X the new X container is added BEFORE the y container. Why? Shouldn't the container be added at the end like this:
```
<main data-barba="container" data-barba-namespace="y">
<main data-barba="container" data-barba-namespace="x">
```

Because of this behaviour my transition works from X to Y but not from Y to X.

**Comment by mrsamse** [comment]
In packages/core/src/utils/dom.ts at line 99 it says that the container should be inserted before, when there is a sibling. But thats not the case?

**Comment by xavierfoucrier** [comment]
Hi @mrsamse,

Sorry for the late reply!

This should be the case if there is a next sibling element to use as reference, regarding this fix: https://github.com/barbajs/barba/commit/54821542cfe186f68da8a69442a04f4cafa5dd07

I will investigate that. :wink:

**Comment by xavierfoucrier** [comment]
Hi @mrsamse,

I can reproduce the issue with a test repo using a timing function that goes from `item1` to `item2`, wait for 2 seconds in the `enter` hook, then go 2 seconds later from `item2` to `item1`, with infinite loop.

Here is a short animation of what is going on:

![barba-container](https://user-images.githubusercontent.com/2471223/66270584-ac2ceb80-e855-11e9-918a-9866f973d4ba.gif)

> The paragraph `.sibling` element contain the current value of the `barba.dom._sibling` property

May be we need to store the current `main` as sibling reference... :thinking:
