### ISSUE TITLE
Is "from route to route" rule possible?

### ISSUE THREAD

**Issue by THRYB4** [barbajs/barba#454]
Hi

## The description

I'm trying to create a rule between to routes (projects and company) by setting first the routes, then telling barba to use these routes and later init barba with the "from-to" rules.

```
const routes = [{
      path: '/projects/',
      name: 'yellow',
    }, {
      path: '/company/',
      name: 'blue',
    },
  ];

 barba.use(barbaRouter, {
      routes,
 });

barba.init({
      debug: true,
      timeout: 5000,
      transitions: [
      {
        name: 'yellowToBlue',
        from: {
          // define rule based on multiple route names
          route: [
            'yellow',
          ],
        },
        to: {
          // define rule based on multiple route names
          route: [
            'blue',
          ],
        },
        beforeLeave(data) {
          console.log('leave yellow')
        },
        afterEnter(data) {
          console.log('enter blue');
        },
      }
  ]
})
```
---

## The problem
The from-to-rule only seems to work, when "to" is set up with a namespace. When both rules "from" and "to" are set up with a route, it doesn't work (as shown above).

In the example [here](https://barba.js.org/docs/v2/user/core.html#rules), there is also shown a rule with a route in "from" and a namespace in "to: 

So i'm wondering: is it even possible to have routes in both "from" and "to"?

(I know, its a question, but the slack invitation link doesn't work anymore)

**Comment by xavierfoucrier** [comment]
Hi @THRYB4,

I have test this use case in a local dev site with a `home.html` and `product.html` pages: it works fine!
Can you please try to set your routes like this:

```js
const routes = [{
  path: '/projects',
  name: 'yellow',
}, {
  path: '/company',
  name: 'blue',
}};
```

> Note that there is **no extensions to your routes** so you need to properly manage this by yourself

Thanks for your feedback! :wink:

**Comment by THRYB4** [comment]
hi @xavierfoucrier 

Thank you for your response. It works now for me too. Found out that barba.js only works correctly in the built version of my website, and not in the development environment with injected files.

**Comment by thierrymichel** [comment]
Hi @THRYB4,

I will close this.

> Found out that barba.js only works correctly in the built version of my website, and not in the development environment with injected files.

Can you investigate and/or give more details?
And, if appropriate, feel free to open another issue!
