### ISSUE TITLE
`state` can be undefined

### ISSUE THREAD

**Issue by luruke** [barbajs/barba#456]
from @lavolpecheprogramma

it appears that `state` can be undefined and generate error.
https://github.com/barbajs/barba/blob/master/packages/core/src/core.ts#L300

**Comment by lavolpecheprogramma** [comment]
I try to describe the flow:
- i have an homepage with a slider that change the hash on the same page (es. /#slide1,  /#slide2),
- i go on another page (es. /test)
- when i click on prev browser button i have this error:
![image](https://user-images.githubusercontent.com/19146698/67268687-6444d000-f4b5-11e9-9ef6-4cef97553775.png)

Barba try to read index property on state, but state is null
https://github.com/barbajs/barba/blob/master/packages/core/src/core.ts#L302 

Thank you

**Comment by lavolpecheprogramma** [comment]
it seems to happen if you use directly `window.location.hash = '#your-hash'` and not if you use `history.pushState({}, '',  '#your-hash')`.

**Comment by luruke** [comment]
grazie for the context @lavolpecheprogramma 👌
