### ISSUE TITLE
Extend logger usage

### ISSUE THREAD

**Issue by xavierfoucrier** [barbajs/barba#457]
**Logger** can be used in some situation to **improve code understanding in dev mode**.

For example, this code display the console message every time and doesn't throw any warning...

```js
barba.init({
  transitions: [{
    name: 'default',
    from: 'home',
    leave: () => {
      console.log('leaving the home page...');
    }
  }]
});
```

... but in fact, the `from` attribute is waiting for an `object`, not a `string`.

This could **mislead the user** when using Barba if he is not properly reading the documentation.

**Comment by taksuparth** [comment]
@xavierfoucrier I would like to give it a go
