### ISSUE TITLE
Query / Hashes deleted on reload

### ISSUE THREAD

**Issue by THRYB4** [barbajs/barba#459]
Problem:
With barba core v2.6 my hashes / queries in the URL vanish when reloading or initially load the page. For example: 

mysite.com#info will be redirected to mysite.com
mysite.com?type=blue will be redirected to mysite.com

When clicking on a link on the site, for example mysite.com/subsite#info the hash stays on the loaded site and is visible in the data.current.url object. But then when reloading this URL, the hash gets deleted.

Downgrading to v2.3.15 solves this problem, my hashes and queries stay in the URL.

**Comment by luruke** [comment]
Hi @THRYB4 have you tried 2.6.1?
it was released yesterday

https://github.com/barbajs/barba/pull/450

**Comment by THRYB4** [comment]
Hi @luruke 

With v2.6.1 it works again. Thank you!

**Comment by luruke** [comment]
Great!
