### ISSUE TITLE
Possible to ignore routes using the router?

### ISSUE THREAD

**Issue by lmartins** [barbajs/barba#461]
Hi, I'm having issues getting a plugin FacetWP to work with barbed loaded views, as that plugin injects data into the document that I'm not finding a practical way to replicate using the lifecycle hooks.

So I'm thinking the next viable approach would to simply exclude that specific page from Barba routes, making the library essentially ignore any link to that URL. I'm not however finding anything in the API for this purpose. Mind you some links on the documentation are giving 404s, so perhaps I'm just out of luck with that. I know there was a way to manually exclude links with a certain classname, but in this case I actually need that to not be dependant on any class being applied to the link. 

Is this possible?

**Comment by thierrymichel** [comment]
Hi @lmartins,

There are different ways to ["prevent" barba using a transition on a page change](https://barba.js.org/docs/v2/user/core.html#prevent):

1. `data-barba-prevent` attribute. Can be used on a link (`self`) or container (`all`)
2. `prevent` function on `init()` parameter. You can implement your own logic returning true or false.

NB: Just to be clear, `@barba/router` can be use to trigger a page transition based on a "route pattern"…

**Comment by lmartins** [comment]
Hey @thierrymichel thanks so much for the quick answer as per usual.

The reason the data-attribute is not adequate in this case is because this is a WordPress build, where we have generated content where I can't guarantee that attribute to be present. 

Given that it includes information about the `href`, the `prevent` method appears to be the best approach. Thanks again Thierry!
