### ISSUE TITLE
Missing Typescript definitions for hooks

### ISSUE THREAD

**Issue by Ahrengot** [barbajs/barba#462]
## The problem

I get a Typescript error when using hooks using this format: 

```JavaScript
barba.hooks.beforeLeave( ({next}) => {} );
``` 

error in VSCode:
![Screenshot 2019-10-24 at 16 19 32](https://user-images.githubusercontent.com/391810/67495571-6b1d3f80-f67b-11e9-9db6-003dcb8998df.png)

---

The callback doesn't know what kind of arguments to expect. It's the common "X implicitly has 'any' type" error, and it's circumventable by just adding `// @ts-ignore` above the line, but having these autocomplete values are really helpful.

Hooks inside of the transitions list work just fine, e.g.:

```JavaScript
barba.init({
  transitions: [
    {
      beforeLeave({ next }) {
        // Do something with `next`
      },
    }
  ],
});
```

## Environment

- Barba version that exhibits the issue: 2.6.1

**Comment by thierrymichel** [comment]
Hi @Ahrengot,

It should be fixed. Can you confirm? Thanks.

**Comment by Ahrengot** [comment]
Yup, that did it — Man that was fast!

I never used Barba before v2, but really digging the API and documentation. You guys have done an awesome job.
