### ISSUE TITLE
Ignore links in Barba v2

### ISSUE THREAD

**Issue by camillo18tre** [barbajs/barba#471]
Hi!!
How can I say to Barba to ignore links?
I saw this issue: https://github.com/barbajs/barba/issues/47 but doesn't work for BarbaV2

Thank you! :)

**Comment by mrsamse** [comment]
Have a look at the v2 documentation: https://barba.js.org/docs/v2/user/core.html#prevent

**Comment by xavierfoucrier** [comment]
Hi @camillo18tre,

Thanks for using barba.

Be sure to **read the doc** before posting a question: https://barba.js.org/docs/v2/user/.
And if it's needed, post the question on the Slack channel instead: grab the link on the [main readme](https://github.com/barbajs/barba#barbajs-v2).

:wink:

**Comment by Nikita-Sp** [comment]
@xavierfoucrier hi! I wish to remove the hook from the fancybox links too, but all the links in your posts are broken.
Could you please provide updated links? This thread in google top.
Thanks.

**Comment by xavierfoucrier** [comment]
Hi @Nikita-Sp,

New documentation website is here:
https://barba.js.org/docs/getstarted/intro/

:wink:
