### ISSUE TITLE
Google Tag Manager receives two history events for any navigation change

### ISSUE THREAD

**Issue by mvpspl619** [barbajs/barba#473]
## The problem

Google Tag Manager is receiving two history events for each navigation change triggered by Barba. This is by Barba design according to this slack message: https://barbajs.slack.com/archives/CH1EA0FKP/p1574323099149900?thread_ts=1574266338.149400&cid=CH1EA0FKP

### Expected behaviour

For each navigation change, there should be only window.history change event so tools listening to history changes receive accurate updates. 

### Actual behaviour

For each navigation change, there are two events as per below text:
Visting a new page: pushState, replaceState
Using browser back button: popState, replaceState

### Code To Reproduce Issue [ Good To Have ]

Any latest version of Barba V2 produces this.

## Environment

- Barba version that exhibits the issue: 2.x
- Browser OS/version used: All

**Comment by thierrymichel** [comment]
@mvpspl619,

It should be fixed in [next release](https://www.npmjs.com/package/@barba/core/v/2.9.3).
And it would be very appreciated if you could check and confirm… 😊

**Comment by mvpspl619** [comment]
That was quick @thierrymichel. I'll confirm today if this is fixed in `2.9.3`

**Comment by thierrymichel** [comment]
Perfect. Thanks a lot @mvpspl619  !!!
Will wait for 2 other confirmations then release on `latest` asap.
