### ISSUE TITLE
barbaPrefetch on links (like v1)

### ISSUE THREAD

**Issue by S1SYPHOS** [barbajs/barba#474]
## The problem
I cannot get barba v1 prefetch behaviour to work

### Expected behaviour

I want to load links on hover instead when in viewpoint (v1 behaviour)

### Actual behaviour

Barba loads dozen of links (because viewpoint loading)

### Code To Reproduce Issue
Just the prefetch demo code, really:
```js
import barba from '@barba/core';
import barbaPrefetch from '@barba/prefetch';

// tell Barba to use the prefetch module
barba.use(barbaPrefetch);

// init Barba
barba.init();
```

---

## Environment
- barba.js:
  - "@barba/core": "^2.8.0",
  - "@barba/prefetch": "^2.1.8"
- Firefox 70 / Fedora Linux

**Comment by thierrymichel** [comment]
Hi @S1SYPHOS,

Please, [check this](https://github.com/barbajs/barba/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)…
We really need more details / context / explanations to provide some help…
Another option is to [join us on Slack](https://join.slack.com/t/barbajs/shared_invite/enQtNTU3NTAyMjkxMzAyLTkxYWUwZmM1YWQxMmNlYmE0ZjY4NDQxMGUxYjkwYWFlMzEzOWM4OTRhMWRmYTQyYzFlMmQ3OGFmYmI3MWY0OWY).

Thanks

**Comment by thierrymichel** [comment]
@S1SYPHOS,

Do not use `@barba/prefetch`.
By default v2 has the same hover/prefetch behaviour as v1…

**Comment by S1SYPHOS** [comment]
Thank you very much, totally missed that.
