### ISSUE TITLE
Can I reload a page when browser back button is clicked?

### ISSUE THREAD

**Issue by yoshikawa-wise** [barbajs/barba#476]
I am using barba.js with wordpress.
I use no-barba class to disable pjax when a user mouse-hover.
But when I load the first page and go to another page and click 'browser's back button' , the first page cached by barba is displayed.
It is ok that cached contents are displayed if they are no-barba contents.
But I dont want the first page to be cached by barba and I want the page to be reloaded.
Is it possible?

**Comment by thierrymichel** [comment]
Hi @yoshikawa-wise,

Not sure to understand your issue but the followings should help:
- [cacheIgnore option](https://barba.js.org/docs/v2/user/core.html#cacheignore)
- [custom rule](https://barba.js.org/docs/v2/user/core.html#rules) when `trigger` equals `back`

If not, do not hesitate to join the [Slack channel](https://join.slack.com/t/barbajs/shared_invite/enQtNTU3NTAyMjkxMzAyLTkxYWUwZmM1YWQxMmNlYmE0ZjY4NDQxMGUxYjkwYWFlMzEzOWM4OTRhMWRmYTQyYzFlMmQ3OGFmYmI3MWY0OWY)!
