### ISSUE TITLE
How to calculate & display percentage of progress of page load & transition ?

### ISSUE THREAD

**Issue by aydinvivik** [barbajs/barba#477]
Hello, firstly thanks for this beautiful app.

How do I show the load percentage when loading a page and page transitions?  For example;

https://assets.awwwards.com/awards/external/2018/03/5aba13e2d8e05.mp4
https://assets.awwwards.com/awards/external/2017/02/58aac1c5e6017.mp4

**Comment by xavierfoucrier** [comment]
Hi @aydinvivik,

Barba is not intended to help you display the percentage of page load: this can be achieved by **preloading every assets** that are needed to display your page.

Take a look at:
https://andreupifarre.github.io/preload-it/docs/index.html

I let this issue open for further discussion with the team :wink:

**Comment by aydinvivik** [comment]
Thank you :)
