### ISSUE TITLE
Different transitions for specific pages (using namespace)

### ISSUE THREAD

**Issue by Nyshhh** [barbajs/barba#478]
Gday!

Thanks so much for Barba. Big ups from down under.  

I know this issue has been addressed  in #19 and elsewhere - I've tried my best to follow along, with little success. I am new to all of this so, please forgive me :( 

I'm attempting to use the namespace strategy outlined by @luruke, but I think my logic for "waiting for NewContainerLoading to be resolved" is flawed, as **I'm not able to retrieve the Barba.HistoryManager.prevStatus(); inside my valid: function**. (I just get null when I console.log it). As a result the specific page transition only works on "the first click', after which it doesn't work.

My code is set up with just 2 transitions at the moment. I've left out the GSAP timelines as they are irrelevant. If anyone can help with setting up the valid: function() part, I'd be forever grateful. Hopefully, some more details about this type of set up could help some other noobs like me too 👍 

Much love~

```

var TopDownTransition = Barba.BaseTransition.extend({

  start: function() {
    Promise
      .all([this.newContainerLoading, this.fadeOut()])
      .then(this.fadeIn.bind(this));
  },

  fadeOut: function() {
    return $(this.oldContainer).animate({ opacity: 0 }).promise();
  },

  fadeIn: function() {
    var _this = this;
    var $el = $(this.newContainer);

    $(this.oldContainer).hide();
    $el.css({
      visibility : 'visible',
      opacity : 0
    });

    $el.animate({ opacity: 1 }, 400, function() {
        _this.done();
    });

  tl = gsap.timeline();
  },

  valid: function() {
    var prev = Barba.HistoryManager.prevStatus();
    return prev.namespace === 'home' && (window.innerWidth > 800);
  }
});


var DownTopTransition = Barba.BaseTransition.extend({
  
start: function() {
    Promise
      .all([this.newContainerLoading, this.fadeOut()])
      .then(this.fadeIn.bind(this));
  },

  fadeOut: function() {
    return $(this.oldContainer).animate({ opacity: 0 }).promise();
  },

  fadeIn: function() {
    var _this = this;
    var $el = $(this.newContainer);

    $(this.oldContainer).hide();
    $el.css({
      visibility : 'visible',
      opacity : 0
    });

    $el.animate({ opacity: 1 }, 400, function() {
        _this.done();
    });

  tl2 = gsap.timeline();
  },

  valid: function() {
    var prev = Barba.HistoryManager.prevStatus();
    return prev.namespace === 'program' && (window.innerWidth > 800);
  }

});


Barba.Pjax.getTransition = function() { 
 if (TopDownTransition.valid()) {
    return TopDownTransition;
  }
  if (DownTopTransition.valid()) {
    return DownTopTransition;
  }
};

```

**Comment by xavierfoucrier** [comment]
Hi @Nyshhh,

Just to be sure, this is related to Barba v1, that is no longer maintained...
If you are new to Barba, you should try to use the latest v2.

https://barba.js.org/docs/v2/user/
:v: :wink:
