### ISSUE TITLE
Linking from facebook android app

### ISSUE THREAD

**Issue by andymathieson** [barbajs/barba#481]
Hi guys,

We've just a new site using Barba. It works superbly and really adds to the experience. 

However, I have just shared the site via facebook mobile app on android. 

When you click on the link, the site automatically opens in facebooks own browser causing none of the links to work. 

Is there a setting I need to put or something that can check whether barba should even run?

**Comment by xavierfoucrier** [comment]
Hi @andymathieson,

Sorry for the late reply. There is no setting in the BarbaJS side to prevent this from happening: the Facebook mobile browser may block/prevent scripts execution for security reason probably :thinking: ...

> Note that when BarbaJS is not able to handle links, we fallback to the default browser link behavior, so you should be able to click on the link and go to the next page anyway, without having a BarbaJS page transition.
