### ISSUE TITLE
Typography looks transparent on code samples

### ISSUE THREAD

**Issue by trevasco** [barbajs/barba#490]
the font styles for the code examples in the docs are really light and a bit hard to read. maybe bump the font weight up one? other than that, love the awesome new site!

<img width="785" alt="Screen Shot 2020-02-25 at 4 12 13 PM" src="https://user-images.githubusercontent.com/6633534/75299431-dfaee900-57e9-11ea-81c5-af3c3ac4868a.png">

**Comment by xavierfoucrier** [comment]
Hi @trevasco,

Thanks for getting in touch.
Unfortunately, it depends on the web browser you are using and how it is configured.

On Google Chrome with the default settings, the font weight looks good:
![Capture](https://user-images.githubusercontent.com/2471223/75342159-2528f000-5896-11ea-90e2-b011e0da6274.JPG)

What browser do you use?

**Comment by trevasco** [comment]
hmm strange.. I'm on the latest Google Chrome, and don't recall ever messing with any settings

**Comment by xavierfoucrier** [comment]
@trevasco,

Can you try on another browser, or just reset your Chrome settings, then restart, then test and show the result. Thanks :wink:

**Comment by trevasco** [comment]
yeah I just reset them and same issue 🤷‍♂

**Comment by trevasco** [comment]
looks the same on firefox / safari as well

**Comment by xavierfoucrier** [comment]
MacOS or Windows?

**Comment by trevasco** [comment]
macOS Sierra. I checked it on browserstack with same settings and it looks fine, so definitely something specific with my machine, just not sure what 😄

**Comment by xavierfoucrier** [comment]
The site is using `monospace`, so probably something wrong with the typo file on your machine. Or probably something about **font smoothing**. Sorry to be unable to help you with that :disappointed: 

I am closing the issue :wink:

**Comment by gitgudcameron** [comment]
This shouldn't be closed. I have to increase the font-weight in the inspector every time i visit the site. It's near impossible to read otherwise. I'm using Chrome on the latest MacOS.

**Comment by xavierfoucrier** [comment]
Hi @gitgudcameron,

This is something we will look into and check. Thanks for the feedback.

**Comment by xavierfoucrier** [comment]
@gitgudcameron some people reported this issue, can you please share a screenshort of the rendering you got on MacOS/Chome?

Thanks a lot!

**Comment by gitgudcameron** [comment]
Hey @xavierfoucrier, 

Hopefully some of this is useful. It's rendering 'Source Code Pro ExtraLight'.

Adding this font-weight does the trick for me:

```
.code {
    font-weight: 400;
}
```
![Screen Shot 2020-04-06 at 9 26 16 pm](https://user-images.githubusercontent.com/52658950/78553993-9d97af00-784d-11ea-820e-9157fa95df76.JPG)
![Screen Shot 2020-04-06 at 9 31 48 pm](https://user-images.githubusercontent.com/52658950/78554207-14cd4300-784e-11ea-84e4-53b3318927aa.JPG)
![Screen Shot 2020-04-06 at 9 30 48 pm](https://user-images.githubusercontent.com/52658950/78554253-2e6e8a80-784e-11ea-8cbf-af599b472d22.JPG)

**Comment by xavierfoucrier** [comment]
@gitgudcameron thanks for the share.

This is probably because Chrome resolves the font using your local files through the name "Source Code Pro". I am on Windows and doesn't have those typos installed, that's why I haven't seen this bug.

I close the issue, and will push a fix with the next documentation update.
