### ISSUE TITLE
How to use babar v2 directly in browser by CDN import

### ISSUE THREAD

**Issue by hosxes** [barbajs/barba#492]
Hello I am a rookie who just learned javascript.
I have used barba v1 in the project and I imported it directly by writing <script> in HTML and it works well : )
But after I imported v2 in the same way, as you said in the novice tutorial, 
“// do not import Barba like this if you load the library through the browser”
Is it that I must only install through node's npm and use it after packaging it with webpack ?
Is it that I can't import it directly as before ?
Thank you very much.

**Comment by xavierfoucrier** [comment]
Hi @hosxes!

Of course you can import Barba the same way you did before with the v1.
Barba is hosted on the UNPKG CDN, so you should use this kind of script tag in your document:

```html
<script src="https://unpkg.com/@barba/core"></script>
```

If you are comfortable with webpack stuff, you should import the library as specified in the documentation:

```js
import barba from '@barba/core';
```

Thanks for your feedback. :wink:

**Comment by hosxes** [comment]
Hi @xavierfoucrier 
Thank you for replying to me! What I actually want to ask is how to use `@barba/css` without npm, because you only wrote the CDN link of `@barba/core`, which made me mistakenly think that `@barba/css` can be used after importing that. 
Anyway, I realized that I only need to import `<script src =" https://unpkg.com/@barba/css "> </ script>` to use the new features!! I'm really stupid haha.
Thank you very much again, I have no other questions, and will continue to support barba.js :3

**Comment by xavierfoucrier** [comment]
@hosxes perfect!
No problem, glad to help your with that :wink: 
Have a nice day :sunglasses:
