### ISSUE TITLE
Codepens hard to understand with Redacted font

### ISSUE THREAD

**Issue by olets** [barbajs/barba#497]
## The problem

https://barba.js.org/examples/ has two Codepen links. The font choice makes it hard to understand what's going on.

### Expected behaviour

Pen makes it clear which things are filler text and which things are images. In the pen with text links, it is clear that the links are links.

### Actual behaviour

For both (https://codepen.io/thierrymichel/project/editor/ZrzBBK and https://codepen.io/thierrymichel/project/editor/XkkWWv) it isn't clear that the rectangles are text. 

For https://codepen.io/thierrymichel/project/editor/ZrzBBK, where one of the rectangles on each page is a link, it makes it hard to know what the pen "does." Maybe others get it more quickly, but I personally didn't know to click until I figured out by luck that the rectangles were text and then tried disabling Redacted.

**Comment by xavierfoucrier** [comment]
Hi @olets,

Sorry for the late reply, and thanks for the issue.
We will take time to review the codepen typography when updating the website documentation.

Have a nice day :wink:

**Comment by xavierfoucrier** [comment]
Hi @thierrymichel,

Can you take 5 minute to review this issue, as I haven't write access on your Codepens :wink: 
Thanks a lot!

**Comment by xavierfoucrier** [comment]
Typo is now fixed on Codepens. Closing the issue. :wink:
