### ISSUE TITLE
Duplicated pages in Wordpress with @barba/prefetch

### ISSUE THREAD

**Issue by dangelion** [barbajs/barba#502]
Hi
I'm building a Wordpress theme with Barba 2.9.7. I noticed that adding `barba.use(barbaPrefetch)` everytime I refresh a page (CMD+R) Wordpress automatically create a draft of the current page. 
I mean, for example, if I refresh for 3 times the "home", I'll get in the Wordpress admin panel 3 "home" pages (as drafts) in Pages listing!
It's crazy. Disabling prefetch this doesn't happen.
Anyone is experiencing this issue?

**Comment by xavierfoucrier** [comment]
Hi @dangelion,

Sorry for the late reply. Very strange situation :thinking: 
Of course, when refreshing with `CMD+R`, you are logged in as admin right?

Can you please check if this happen on a Wordpress page that doesn't have any links inside the page content: like a blank page.

Can you confirm that this happen when only using barba on your Wordpress theme? (remove every other js plugins and disable all Wordpress plugins for your theme.

Thanks for the feedback. :+1:

**Comment by thomaslecoeur** [comment]
I got the same issue.

It's due to the prefetch of the links in the Wordpress admin bar.
I had to use the prefetchIgnore globally to fix this issue.

**Comment by xavierfoucrier** [comment]
Thanks @thomaslecoeur for the feedback.

If you have a WP demo running online on which I could see the bug, it would help determine what's going on.

Have you try without adding @barba/prefetch: is it the same result?

Thanks :wink:

**Comment by xavierfoucrier** [comment]
I just tested on a **WordPress 5.4**, using a custom theme, and it works just fine: no issues to report about duplicated pages.

> As @thomaslecoeur said, if you encouter this issue again, use the [`prefetchIgnore`](https://barba.js.org/docs/advanced/strategies/#prefetchIgnore) option to tell Barba to ignore those links

Closing the issue.
