### ISSUE TITLE
Unable to get next.namespace

### ISSUE THREAD

**Issue by romain-granai** [barbajs/barba#503]
I'm strictly **unable to get the `next.namespace`**.

`console.log(trigger)` works
`console.log(currentPage)` works
`console.log(nextPage)` doesn't work, why?

```js
leave({current, next, trigger}){
  var currentPage = current.namespace,
  nextPage = next.namespace;
  
  console.log(trigger);
  console.log('current page is : ' + currentPage)
  console.log('next page is : ' + nextPage)
  
  return new Promise(resolve => {
    var indexLeave = gsap.timeline({
      onComplete: resolve
    });
    
    indexLeave.to('.transition-about', 2, {
      autoAlpha: 1,
      display: 'block'
    });
  });
}
```

**Comment by xavierfoucrier** [comment]
Hi @romain-granai,

According to the [lifecycle diagram of BarbaJS](https://raw.githubusercontent.com/barbajs/barba/master/lifecycle-diagram.png), you can't get the `next.namespace` inside the `leave` stage as the next page isn't fetch at this time...

Use the **`afterLeave` hook** instead :wink:
