### ISSUE TITLE
Barba v2 removed the "default" transition support?

### ISSUE THREAD

**Issue by OksanaRomaniv** [barbajs/barba#506]
Hello, 

After updating from v1 to v2, my transitions described as "default" stoped working. How can you specify the default transition (if any other doesn't match) to use? I couldn't find anything in the docs.

Thanks!

**Comment by OksanaRomaniv** [comment]
Hello,

I found the issue. It appears that I needed to change the "beforeLeave" function inside the default transition object to "leave" function otherwise it didn't match the transition anymore. 

Thanks!

**Comment by xavierfoucrier** [comment]
Hi @OksanaRomaniv,

The code syntax is different between the v1 and v2.
Did you take a look at the **[legacy example](https://barba.js.org/docs/getstarted/legacy/)**?

To tell Barba to use a "default" transition in the v2, you just have to define a transition, give it a name, and add your animation logic with an animation library (gsap, animejs, etc.) like this:

```js
barba.init({
  transitions: [{
    name: 'default',
    leave: function(data) {
     // your animation logic when leaving the current page
    }
  }]
});
```

Hope this help! :wink:
