### ISSUE TITLE
Can you query data.next.container.html for updating content outside of container?

### ISSUE THREAD

**Issue by telagraphic** [barbajs/barba#507]
I've searched the issues history and docs and I did not find anything that answer my question.
How to query **data.next.container.html** to get content from the next loading page?

I tried using querySelector, but container.html is just a string? 

I'm trying to update an element outside of the **barba container** using the new page content upon each page transition in a **beforeEnter** hook.

**Comment by xavierfoucrier** [comment]
Hi @telagraphic,

Yes you (we) can! :smiley:

Indeed, `data.next.container.html` is a `String`, so if you need to travel that string to find a specific element, you will need to parse it in order to query it like a **DOM object**.

Another point, if your element is outside the barba container, **you can access it along all the pages**. As the documentation says:

> Beware, everything inside of this wrapper and outside of the container will not be updated by Barba: you can put your `<header>`, `<footer>` or `<nav>` safely here.

See https://barba.js.org/docs/userguide/markup/.

Hope this help :wink:

**Comment by telagraphic** [comment]
I realized its **data.next.html** instead of **data.next.container.html**
Thanks for the response @xavierfoucrier!

**Comment by yagayente** [comment]
@telagraphic hi ! If you have an example code of what you did I am interested !

**Comment by xavierfoucrier** [comment]
Hi @yagayente,

Take a look at the parameters section in the docs here:
https://barba.js.org/docs/advanced/hooks/#Parameters

> All hooks receive **the same data argument** object [...]

Meaning that you can use it in any hooks.
Here is an example (from scratch):

```js
barba.hooks.enter((data) => {

  // use a DOM parser to convert a String into an HTMLDocument
  let parser = new DOMParser();
  let dom = parser.parseFromString(data.next.container, 'text/html');

  // this will get the .projects div from the next container
  let projectsDiv = dom.querySelector('.projects');
});
```

> See https://developer.mozilla.org/fr/docs/Web/API/DOMParser.

Hope this help :wink:
