### ISSUE TITLE
Locomotive-scroll implementation

### ISSUE THREAD

**Issue by vidi45** [barbajs/barba#511]
I'm trying to get barba.js and locomotive scroll to work correctly when switching pages. But when going from one page to another, the locomotive stops working. The error is as follows: "Uncaught TypeError: Cannot read property 'match' of undefined"

This is my code.  I can't remove locomotive completely when I leave a page

```
const scroll = new LocomotiveScroll({
   el: document.querySelector(".js-scroll"),
   smooth: true
});
barba.hooks.beforeLeave(data => {
   scroll.destroy();
});
barba.hooks.enter(data => {
   scroll.init();
});

barba.init();
```

**Comment by xavierfoucrier** [comment]
@vidi45,

Please update your issue to explain it with **more consistency and better code syntax**.
Thanks.

**Comment by vidi45** [comment]
Hi, @xavierfoucrier  

It's already corrected. Excuse the awkwardness

**Comment by xavierfoucrier** [comment]
@vidi45 thanks :smiley: !
Some peoples reported the same issue, I will test and give a feedback as soon as possible. :wink:

**Comment by xavierfoucrier** [comment]
Hi @vidi45,

I just add a [dedicated LocomotiveScroll section](https://barba.js.org/docs/advanced/third-party/#Locomotive-scroll) inside the **advanced third party scripts** documentation on the Barba website.

> This section may evolve in time based on LocomotiveScroll updates...

Feel free to close the issue.
Happy reading! :wink:

**Comment by vidi45** [comment]
Thank you very much! |

**Comment by cl-alessandro-molari** [comment]
@xavierfoucrier Hi, I followed the guide.

The Javascript code is the following:

```js

let scroll;

barba.init({
  transitions: [
    {
      name: "custom-transition",
      once({ next }) {
        // init LocomotiveScroll on page load
        smooth(next.container);
      },
      beforeEnter({ next }) {
        // destroy the previous scroll
        scroll.destroy();

        // init LocomotiveScroll regarding the next page
        smooth(next.container);
      },
    },
  ],
});

function smooth(container) {
  scroll = new LocomotiveScroll({
    el: container.querySelector("[data-scroll-container]"),
    smooth: true,
  });
}

```

This is the HTML:

![image](https://user-images.githubusercontent.com/66269365/83441229-783ab200-a446-11ea-9c7e-72e1e87c6317.png)

However after I change page (I click on a anchor with href to another barba page) I get the error and I am  not able to make Locomotive and Barba work together.

Do you have any suggestions?

Thanks

**Comment by xavierfoucrier** [comment]
Hi @cl-alessandro-molari,

Do you have a reproductible test repository or development site to share in order to help you.
Enable the Barba debug mode using `debug: true` inside `barba.init({ options });` in order to see if there are exceptions.

Thanks!

**Comment by simonerama** [comment]
Hi @cl-alessandro-molari,
If can help my settings are:

```
let scroll;
barba.init({
    sync: true,
	transitions: [{
		once({ next }) {
			smooth(next.container);
			config();
			contentAnimation();
		},
		beforeEnter() {
			scroll.destroy();
		},
		afterEnter({ next }) {
			setTimeout(function() {
				smooth(next.container);
			}, 1000);
		},
		async leave(data) {
			const done = this.async();
			pageTransition();
			await delay(1000);
			done();
		},
		enter() {
			config();
			contentAnimation();
		}
	}]
});

function smooth(container) {
	scroll = new LocomotiveScroll({
		el: container.querySelector('[data-scroll-container]'),
		smoothMobile: true,
		smooth: true
	});
}
```

**Comment by cl-alessandro-molari** [comment]
@xavierfoucrier @simonerama I created a repository to reproduce the issue.

https://github.com/alem0lars/yoyo

To reproduce the issue:
- from "homepage" visit "approach" page, so it makes page transition
- scroll down and then up
It will start doing wrong calculations and showing empty page.

Thanks
Alessandro

**Comment by xavierfoucrier** [comment]
Hi @simonerama and @cl-alessandro-molari,

Please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

I am locking the conversation.
