### ISSUE TITLE
Webpack dont provide TypeScript sourceMap

### ISSUE THREAD

**Issue by dkrnl** [barbajs/barba#513]
Hi!

Not issue -- question:

i catch not readable error([webpack ignore sourcemap from typescript](https://github.com/webpack/webpack/issues/7172)):
```
TypeError getAction(@barba/core/dist/barba.umd) this.k.get(...) is undefined
./node_modules/@barba/core/dist/barba.umd.js in getAction at line 1:13994
./node_modules/@barba/core/dist/barba.umd.js in r at line 1:27221
./node_modules/@barba/core/dist/barba.umd.js in apply at line 1:11565
./node_modules/@sentry/browser/esm/helpers.js in arg at line 71:23
```

Can you disable minify `barba.umd.js` ? Or maybe two version: `barba.umd.js` and `barba.umd.min.js`

Thx! Barba is awesome!

**Comment by xavierfoucrier** [comment]
Hi @dkrnl,

Sorry for the late reply!

UMD versions are always published minified on unpkg.
May be we should **disable source map generation in production build** in order to prevent this kind of error :thinking: 

cc @thierrymichel 

> Note that **we are using [microbundle](https://github.com/developit/microbundle)** to compile the package.

**Comment by thierrymichel** [comment]
Hi @dkrnl,
Thanks for pointing this.
There is an option to disable sourcemaps that works like a charme… but for all builds… :D
@xavierfoucrier Do you think it's a problem ?

**Comment by xavierfoucrier** [comment]
@dkrnl if you can provide more informations, we would love to help you more.
For now, we are closing the issue. :wink:
