### ISSUE TITLE
What is the use case for sync mode?

### ISSUE THREAD

**Issue by telagraphic** [barbajs/barba#514]
I typically use promises when writing my hooks because that's how I saw it done.  I see you can use async/await which or sync mode.  Is there a difference between using promises and sync mode and why would you chose on over the other?  Seems like sync mode doesn't follow the hook order and that they occur at the same time?

The docs says:

>  A mode that indicates whether leave and enter hooks should “play together”.
> This involves waiting until the next page is available: fetched or cached.

[Here is short code example using sync mode](https://github.com/karanmhatre1/barba-page-transition-example/blob/master/js/main.js).

With promises:

```
enter({current, next, trigger}) {
        return new Promise(resolve => {

          const timeline = gsap.timeline({
            onComplete() {
              resolve();
            }
          })

          timeline
            .from(next.container, {opacity: 0, y: 50})
            .to(next.container, {opacity: 1, y: 0, ease: 'power4.out', duration: .25});
        })
      }
```

With sync mode from this [repo](https://github.com/karanmhatre1/barba-page-transition-example/blob/master/js/main.js):

```
// Function to add and remove the page transition screen
function pageTransition() {

  var tl = gsap.timeline();
  tl.set('.loading-screen', { transformOrigin: "bottom left"});
  tl.to('.loading-screen', { duration: .5, scaleY: 1});
  tl.to('.loading-screen', { duration: .5, scaleY: 0, skewX: 0, transformOrigin: "top left", ease: "power1.out", delay: 1 });
}

// Function to animate the content of each page
function contentAnimation() {

  var tl = gsap.timeline();
  tl.from('.is-animated', { duration: .5, translateY: 10, opacity: 0, stagger: 0.4 });
  tl.from('.main-navigation', { duration: .5, translateY: -10, opacity: 0});

  $('.green-heading-bg').addClass('show');

}

$(function() {

  barba.init({

    sync: true,

    transitions: [{

      async leave(data) {
        
        const done = this.async();
        
        pageTransition();
        await delay(1000);
        done();

      },

      async enter(data) {
        contentAnimation();
      },

      async once(data) {
        contentAnimation();
      }

    }]
  });

});
```

**Comment by xavierfoucrier** [comment]
Hi @telagraphic,

As [describe in the documentation](https://barba.js.org/docs/advanced/transitions/#Sync-mode), the `sync` mode allow you to have `leave` and `enter` transition hooks playing "together".

In another words, regarding the [legacy example](https://barba.js.org/docs/getstarted/legacy/), if you have an opacity transition from `0 -> 1` for `leave` and `1 -> 0` for `enter`:
- using `sync: false` will play the `leave` transition first, making your page content goes transparent, then play the `enter` transition, making the next page content goes opaque _(two step transition)_
- using `sync: true` will make the current page goes transparent while the next page becomes opaque at the same time _(crossfade transition)_

Hope it's clear for you now :wink:
Feel free to close the issue.

**Comment by telagraphic** [comment]
Yes, that makes more sense, thanks!

**Comment by xavierfoucrier** [comment]
Nice! I will improve the `sync mode` section in order to make it clear for everyone. 😉
