### ISSUE TITLE
Update menu class

### ISSUE THREAD

**Issue by Jaune8** [barbajs/barba#518]
Hello,

Thanks for released the V2, i'm reading this and trying to change my local site from v1 to v2.
During one day i look for updated body class and with this post ( https://github.com/barbajs/barba/issues/51 )  it help me a lot, and it works.

And now i want to update menu outside data-barba="container" data-barba-namespace="home".
Before, in v1 i use this code find here ( https://github.com/barbajs/barba/issues/43 ) and it works well : 

`    const navs = $(html).find('[data-barba-update]');

    $('[data-barba-update]').each(function(index) {
        const newClasses = $(navs[index]).get(0).classList.value;
        $(this).attr('class', newClasses);
    });
`
 I also find this code v2 ( https://github.com/barbajs/barba/issues/395 ) to updated menu depend on the href : 

`
      // get the menu element
      let menu = document.querySelector('.menu');
      
      // select the menu item depending on the next URL (you can do that in many ways)
      let nextItem = menu.querySelector(`a[href="${next.url.href}"]`);
      
      // reset the active menu item and set the next item as "active" (if there is one)
      if (nextItem !== null) {
        menu.querySelector('.item-active').classList.remove('item-active');
        nextItem.classList.add('item-active');
      }
`

It works on my first menu but i have link with no href witch open one other menu witch is not a child, and it doesn't work for me on 2 ".menu".

Do you have an idea to help me resolve this and do you have any other code to updated markup like [data-barba-update] ?

Thanks and sorry for my english. :)

**Comment by xavierfoucrier** [comment]
Hi @Jaune8,

This issue is more related to **how your code is running** than Barba v2 implementation...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

I am closing the issue.

**Comment by poopsplat** [comment]
@Jaune8 — for what it's worth I was looking for the same thing and used the following with success:
```
    beforeEnter(data) {
      const updateItems = $(data.next.html).find('[data-barba-update]');

      $('[data-barba-update]').each(function(index) {
          const newClasses = $(updateItems[index]).get(0).classList.value;
          $(this).attr('class', newClasses);
      });
    },
```
