### ISSUE TITLE
Transitions not working with namespaces

### ISSUE THREAD

**Issue by jrandallw** [barbajs/barba#523]
Hello! I'm trying to build out different GSAP transitions for content on different pages of my site. I've gotten my baseline page transitions working, and even some content animation, but for some reason as soon as I utilize a namespace the page transitions stop working, although the content continues to switch. I've set the namespace correctly in my markup, and this is my javascript.

```
barba.init({
  transitions: [{
    name: 'work-index',
    to: { 
        namespace: 
            [ 'work-index' ] 
    },
    async leave(data) {
      const done = this.async();
      pageTransition();
      await delay(1000);
      window.scrollTo(0, 0);
      done();
    },
    async enter(data) { 
      workIndexAnimation(); 
    }
  }]
});
```

Live site is [jessewinton.works](https://jessewinton.works), and I can provide more info/code as necessary. That being said, am I doing something wrong? 

Thank you!

**Comment by xavierfoucrier** [comment]
Hi @jrandallw,

Did you ended to make it work?
Because you close then open the issue again :smile: 

Thanks for the feedback!
