### ISSUE TITLE
Async not working with WordPress

### ISSUE THREAD

**Issue by studiohic** [barbajs/barba#524]
Thanks for creating Barba...

I'm trying to implement it in Wordpress and have got it working to a point! However as soon as I try to add async to the code links need to be clicked twice and there are no transitions. Async is needed otherwise the next page appears before the transition starts. Essentially the code is as below. Site is being built locally using node/npm. I thought that Babel might have been the culprit but I've ruled that out.

Been scratching my head for quite a few hours now so if anyone can help that would be very much appreciated. 

`function delay(n) {
	n = n || 2000;
	return new Promise((done) => {
		setTimeout(() => {
			done();
		}, n);
	});
}

function pageTransition() {
	var tl = gsap.timeline();
	tl.to('.loading-screen', {
		duration: 1.2,
		width: '100%',
		left: '0%',
		ease: 'Expo.easeInOut',
	});

	tl.to('.loading-screen', {
		duration: 1,
		width: '100%',
		left: '100%',
		ease: 'Expo.easeInOut',
		delay: 0.3,
	});
	tl.set('.loading-screen', { left: '-100%' });
}

function contentAnimation() {
	var tl = gsap.timeline();
	tl.from('.is-animated', {
		duration: 1,
		y: 30,
		opacity: 0,
		stagger: 0.4,
		delay: 0.2,
	});
}

$(function () {
	barba.init({
		sync: true,

		transitions: [
			{
				async leave(data) {
					const done = this.async();

					pageTransition();
					await delay(1000);
					done();
				},

				async enter(data) {
					contentAnimation();
				},

				async once(data) {
					contentAnimation();
				},
			},
		],
	});
});`

Thanks

**Comment by xavierfoucrier** [comment]
Hi @studiohic,

Please take time to properly format your code in order for us to give a proper answer...
Thanks!

**Comment by adrilevendi** [comment]
I have almost the same problem. Overall problem is that the transition doesnt play, the page makes a quick refresh and then its back to the sam page. It works well without async. Also it does work with async on pure html/css.
-- Using Wordpress 5.4.2 and  Timber 1.13
JS:
`import barba from '@barba/core';


//Page Transitions

function delay(n) {
  n = n || 2000;
  return new Promise(done => {
    setTimeout(() => {
      done();
    }, n)
  })
}

function pageLeaveAnimation () {
  // $('#sideMenu').removeClass('active');

  var t = gsap.timeline();

  t.to('.transition',
    {
      width: "100%",
      duration: 1
    });

    t.to('.transition', {
      x: "100%",
      duration: 0.5
    });

    t.set('.transition', {x:0, width: 0});
}



$(function () {
  barba.init({
      sync: true,
   
    transitions: [{
       async leave(data) {
  
        const done = this.async();  
        pageLeaveAnimation();
  
  
        await delay(1000);
        done();
  
  
      },
       async enter(data) {
      }
    }],

  });
  
});`

LAYOUT SETUP:
`{% block html_head_container %}

    {% include 'html-header.twig' %}
    {% block head %}
    {% endblock %}
    </head>
{% endblock %}

<body data-barba="wrapper" class="page-{% block body_class %}{% endblock %}" data-template="base.twig">


<div class="transition"></div>

<main data-barba="container" data-barba-namespace="home" id="content" role="main" class="content-wrapper">
<header class="header">
    {% block header %}

        {% include "header.twig" %}

    {% endblock %}
</header>
    <div class="wrapper {{ sidebar_class }}">
        {% block content %}
            Sorry, no content
        {% endblock %}
    </div>
    {% if sidebar %}
        <aside class="layout-sidebar">
            {{ sidebar }}
        </aside>
    {% endif %}
</main>

{% block footer %}
    <footer id="footer">
        {% include 'footer.twig' %}
    </footer>
    {{ function('wp_footer') }}
{% endblock %}


{# <script type="text/javascript" src="//code.jquery.com/jquery-2.2.4.min.js"></script> #}

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
		<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="{{ site.theme.link }}/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/ScrollMagic.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/plugins/debug.addIndicators.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.3.4/gsap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.4.0/ScrollTrigger.min.js"></script>

<script src="{{ site.theme.link }}/dist/js/index.min.js"></script>



</body>
</html>
`

Thank you
