### ISSUE TITLE
Cancel waiting prefetch requests

### ISSUE THREAD

**Issue by 1ucay** [barbajs/barba#525]
Hello, it is possible cancel all prefetech waiting request, if user click to link? I have menu with many items. If I hover over them, prefetch will load for example 5~10 pages, but if user click immediately to link, these others prefetch pages is unnecessary. I have little bit slow server, so it can be performance impact. Also, in browser it can be faster. Thank you

**Comment by xavierfoucrier** [comment]
Hi @1ucay,

There is no way to cancel prefetch requests, but, **you can easily disable the prefetch feature** by using the `prefetchIgnore` property:

```js
barba.init({
  prefetchIgnore: true
});
```

> See https://barba.js.org/docs/advanced/strategies/#prefetchIgnore for more informations.
