### ISSUE TITLE
How to disable barba.js in some urls?

### ISSUE THREAD

**Issue by ProdesignerAgency** [barbajs/barba#526]
I have WordPress website, and i have problem with admin panel - localhost/x/wp-admin/
If i use barba i have problem with time sessions - 
Your session has expired. Please login to continue.
Please help :)

**Comment by xavierfoucrier** [comment]
Hi @ProdesignerAgency,

You can **disable Barba on some links** by using a `prevent` strategie:

```html
<!-- prevent Barba from running on a specific link -->
<a href="localhost/x/wp-admin/" data-barba-prevent="self">Admin</a>

<!-- prevent Barba from running on an entire block -->
<div data-barba-prevent="all">
  <p>text content</p>
  <a href="link-1">link-1</a>
  <a href="link-2">link-2</a>
</div>
```

> See https://barba.js.org/docs/advanced/strategies/#prevent for more informations.

Please let me know if it fits your need :wink:

**Comment by xavierfoucrier** [comment]
@ProdesignerAgency,

Barba doesn't have any effects on session duration, as it is a server-side setting.
Closing the issue.

**Comment by webdiller** [comment]
Just add this code into you main js file:
```js
document.querySelectorAll("#wpadminbar a").forEach(item=>item.setAttribute('data-barba-prevent','self'));
```

**Comment by achappard** [comment]
```
barba.init({
  prevent: ({ el }) => (el.classList && el.classList.contains('ab-item')),
});
```

**Comment by xarxino** [comment]
> Just add this code into you main js file:
> 
> ```js
> document.querySelectorAll("#wpadminbar a").forEach(item=>item.setAttribute('data-barba-prevent','self'));
> ```

thanks brother, i just wrapped it in a domcontentloaded event listener and it worked like a charm. not that savvy with js either 😅
