### ISSUE TITLE
Can't get barba.js css working

### ISSUE THREAD

**Issue by Jonatan-r** [barbajs/barba#528]
So.. I figured it out.

If I follow this https://barba.js.org/docs/plugins/css/#Custom-rule :

```
  barba.use(barbaCss);
  barba.init({
  transitions: [{
    name: 'fade',
    leave() {},
    enter() {}
  }]
});
```

and I follow I also copy the css from https://barba.js.org/docs/plugins/css/#Custom-rule CSS:

```
.fade-leave-active,
.fade-enter-active,
.slide-leave-active,
.slide-enter-active {
  transition: opacity 450ms ease, transform 650ms ease-in-out;
}

.fade-leave,
.fade-enter-to {
  opacity: 1;
}

.fade-enter,
.fade-leave-to {
  opacity: 0;
}
```

it works!... Yay.. My simple basic CSS page fade transition. Horrayy... But.. It was, following the docs, _**not**_ logic getting there.. Why? Well because I just initially followed it from the top down:

That is I just thought it was plug'n'play using the first paragraphs code,  totally copy-pastable:
https://barba.js.org/docs/plugins/css/#How-it-works

```
    barba.use(barbaCss);
  barba.init({
 
});
```

And CSS:

```
.barba-leave-active,
.barba-enter-active {
  transition: opacity 450ms ease;
}

.barba-leave,
.barba-enter-to {
  opacity: 1;
}

.barba-enter,
.barba-leave-to {
  opacity: 0;
}
```

But.. no. It is **_not_** obviously clear, as a noob following the docs, just wanting some of the very very simplest CSS totally basic fade from page to page transition you can not just do the justabovementioned initial https://barba.js.org/docs/plugins/css/#How-it-works. But you have to figure out that you need to actually follow this part: https://barba.js.org/docs/plugins/css/#Custom-rule

– That is, that you need   :
```
barba.init({
  transitions: [{
    name: 'xxxx',
    leave() {},
    enter() {}
  }]
});
```

– to actually make it work :)

_Originally posted by @Jonatan-r in https://github.com/barbajs/barba/issues/509#issuecomment-635481583_

**Comment by xavierfoucrier** [comment]
Hi @Jonatan-r,

Thanks for getting in touch.
I just test the code again to be sure... but **it is working as expected**.

When using `@barba/css` without any `Transition` defined, it will use **the default `barba-xxx` naming convention** to create the CSS classes.

When declaring a `Transition` with a dedicated name, it will use that name to create the CSS classes instead, as described in this section: https://barba.js.org/docs/plugins/css/#CSS-prefix.

> Please read the documentation carefully.

I am closing the issue :wink:

**Comment by sahilk** [comment]
The docs mention `barba.use(css);`, but that probably only works for `import`. I'm using the CDN and I'd keep getting the `css is not defined` error. I had to land here to find `barba.use(BarbaCss);` is what worked for @Jonatan-r. Please update the documentation accordingly.

**Comment by xavierfoucrier** [comment]
Hi @sahilk!

Working on it right now.
Thanks for pointing this out.

Have a nice day :sunglasses:
