### ISSUE TITLE
Custom JavaScript is not executed after transitioning once

### ISSUE THREAD

**Issue by Manu10744** [barbajs/barba#534]
Hello,

I am now encountering a problem that lots of people encounter after they set up BarbaJS. And I know this is probably nothing new to you, but I've seen lots of Questions about it on StackOverflow and somehow none of them could provide a solution which works for barba v2.

### The Problem
I have registered a basic Transition and everything works fine, but after i transitioned once between two pages, everything of my custom JavaScript is gone. EventListeners don't work anymore, which for example makes the mobile navigation on my page useless, literally nothing is working anymore. And I also understand thats because it simulates a Single Page Application, but still there must be a way of Reinitializing everything after a page transition? 

### What I Tried
In `barba.hooks.afterEnter()`, I already tried to manually inject every script of the corresponding new page by extracting the script src's, making an AJAX call for each and inserting them into the DOM by using the following code: 

`barba.hooks.afterEnter((data) => {
    let HTMLnext = data.next.html;
    var scriptRegex = new RegExp("<script?\\w+(?:\\s+(?:" + 'src' + "=\"([^\"]*)\")|[^\\s>]+|\\s+)*>","gi");
    var sources = [];

    while (match = scriptRegex.exec(HTMLnext)) {
        // full match is in match[0], whereas captured groups are in ...[1], ...[2], etc.
        sources.push(match[1]);
    }

    document.querySelectorAll("script").forEach((item) => {
        document.body.removeChild(item);
    })

    sources.forEach((src) => {
        var xhttp = new XMLHttpRequest();
        xhttp.onreadystatechange = function() {
           if (this.readyState == 4 && this.status == 200) {
                let script = document.createElement('script')
                let scriptText = document.createTextNode(this.response);
                script.appendChild(scriptText);
                document.body.appendChild(script);
            }
          };
     
        xhttp.open("GET", src, true);
        xhttp.send();
    })
}) `

but it still does'nt work. And as you can't "unload" JavaScript code from the browsers memory, I really don't know what to try out anymore. Is there any solution you can give me? 

You can watch my page at http://www.manuelneumayer.com

**Comment by xavierfoucrier** [comment]
Hi @Manu10744,

This issue is more related to **how your code is running** than Barba v2 implementation...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

I am closing the issue.
