### ISSUE TITLE
Script-src tags are disabled when I navigate between pages

### ISSUE THREAD

**Issue by duboloms** [barbajs/barba#535]
I use barba with webpack, and my script tag looks like this:
`<script src="./dist/home.js"></script>` 

**When i navigate between pages this script disable**

And script on other page, don't work when i navigate there too
More details: On second page i have another script:
`<script src="./dist/form.js"></script>`

> form js is a main js file for second page

In internet have fixes, but i don't now, how i can load two script with different src attributes:
<pre>
barba.hooks.beforeEnter((data) => {
   let script = document.createElement('script');
   script.src = "./index.js";
   data.next.container.appendChild(script);
});
</pre>

How i can repair this?

**Comment by xavierfoucrier** [comment]
Hi @duboloms,

Sorry for the late reply!

You should use `View` in order to fix that.
See https://barba.js.org/docs/advanced/views/.

Here is a short example based on your code:

```js
barba.init({
  views: [{
    namespace: 'home',
    beforeEnter(data) {
      // here you need to place the content of
      // your file ./dist/home.js
    }
  }, {
    namespace: 'form',
    beforeEnter(data) {
      // here you need to place the content of
      // your file ./dist/form.js
    }
  }]
});
```

> This code pretend that you are using `data-barba-namespace="home"` for your homepage, and `data-barba-namespace="form"` for the page that contain your form. See https://barba.js.org/docs/getstarted/markup/#DOM-structure

As you are using webpack, it should be easy to implement with `import` :wink:
