### ISSUE TITLE
How to determine the menu color of the active page

### ISSUE THREAD

**Issue by mesutuca33** [barbajs/barba#547]
Hello again, I have never used such a library. I would be very happy if you answer my question by coding.

(Menü)
Home - About - Gallery - Videos - Contact

I have 5 pages that I exemplified above or more. How can I add "active" class to menus when barba.init starts or how can I determine the font-color of the active page. please do not show me the address or source before answering it will not work for me because I have no information. For example, if you show on the code, at least thousands of people starting from scratch will benefit. Thank you from now.

**Comment by xavierfoucrier** [comment]
Hi @mesutuca33,

Same answer as yesterday...

This issue is more related to **how your code is running** than Barba v2 implementation...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

Anyway, this can be achieve **in many different ways, depending on your code structure, template, etc.** One "easy" way is to manage an `active` class on the current menu item with a given URL and update it using Barba. Here is a code sample that should work in most cases:

```html
<body data-barba="wrapper">
  <header>
    <nav class="menu">
      <ul>
        <li><a href="home.html" class="active">Home</a></li>
        <li><a href="about.html">About</a></li>
        <li><a href="gallery.html">Gallery</a></li>
        <li><a href="videos.html">Videos</a></li>
        <li><a href="contact.html">Contact</a></li>
      </ul>
    </nav>
  </header>
  <main data-barba="container" data-barba-namespace="home">
    <!-- home page content here -->
  </main>
</body>
```

```js
// method that will update the active class on the menu, based on a given url
function updateMenu(url) {
  const active = header.querySelector('.menu a.active');

  if (active !== null) {
    active.classList.remove('active');
  }

  const links = Array.from(header.querySelectorAll('.menu a'));

  const index = links.map(link => link.href).findIndex((href) => {
    return url.indexOf(href) !== -1;
  });

  if (index !== -1) {
    links[index].classList.add('active');
  }
}

// hooks that will be triggered before any page transition
// meaning your menu active class will be updated before going to the next page
barba.hooks.before({ trigger }) {
  updateMenu(trigger.href);
}

// init Barba
barba.init();
```

Hope this help :wink: 

> Please do not open an issue for each question about your development: use the Slack workspace.
> **Issues are made for new features and bug tracking/problems** that you encounter when using the library.

I am closing the issue.

**Comment by mesutuca33** [comment]
I signed up wet but how do I find your community group

**Comment by mesutuca33** [comment]
`Uncaught SyntaxError: Unexpected token '{'`

` barba.hooks.before({ trigger }) {
        updateMenu(trigger.href);
    }`

I got an error like this

**Comment by mesutuca33** [comment]
it has no effect in this way. the active class does not print and there is nothing changing in the transitions. I have been struggling for 3 days. I still haven't found a solution for the paging problem.

**header.php**
```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hello World</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body data-barba="wrapper">
<header>
    <nav class="menu">
        <ul>
            <li><a href="home.php" class="active">Home</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="gallery.php">Gallery</a></li>
            <li><a href="videos.php">Videos</a></li>
            <li><a href="contact.php">Contact</a></li>
        </ul>
    </nav>
</header>
```
**footer.php**
```
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>

<script src="https://unpkg.com/@barba/core"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.2.6/gsap.min.js"></script>
<script>

    // method that will update the active class on the menu, based on a given url
    function updateMenu(url) {
        const active = header.querySelector('.menu a.active');

        if (active !== null) {
            active.classList.remove('active');
        }

        const links = Array.from(header.querySelectorAll('.menu a'));

        const index = links.map(link => link.href).findIndex((href) => {
            return url.indexOf(href) !== -1;
        });

        if (index !== -1) {
            links[index].classList.add('active');
        }

    }

    // hooks that will be triggered before any page transition
    // meaning your menu active class will be updated before going to the next page
    barba.hooks.before((trigger) => {
        updateMenu(trigger.href);

    });

    // init Barba
    barba.init();
</script>
</body>
</html>
```
**home.php**
```
<?php require_once 'header.php'; ?>
<main data-barba="container" data-barba-namespace="home">
    <!-- home page content here -->
    <div class="container">
        <h1>Welcome to the Home</h1>
    </div>
</main>
<?php require_once 'footer.php'; ?>

```

**about.php**
```
<?php require_once 'header.php'; ?>
<main data-barba="container" data-barba-namespace="about">
    <!-- About page content here -->
    <div class="container">
        <h1>Welcome to the About</h1>
    </div>
</main>
<?php require_once 'footer.php'; ?>

```

**gallery.php**
```
<?php require_once 'header.php'; ?>
<main data-barba="container" data-barba-namespace="gallery">
    <!-- Gallery page content here -->
    <div class="container">
        <h1>Welcome to the Gallery</h1>
    </div>
</main>
<?php require_once 'footer.php'; ?>

```

**videos.php**
```
<?php require_once 'header.php'; ?>
<main data-barba="container" data-barba-namespace="videos">
    <!-- videos page content here -->
    <div class="container">
        <h1>Welcome to the Videos</h1>
    </div>
</main>
<?php require_once 'footer.php'; ?>

```

**contact.php**
```
<?php require_once 'header.php'; ?>
<main data-barba="container" data-barba-namespace="contact">
    <!-- Contact page content here -->
    <div class="container">
        <h1>Welcome to the Contact</h1>
    </div>
</main>
<?php require_once 'footer.php'; ?>

```

**Comment by xavierfoucrier** [comment]
> Thank you for your answer. it was good at some point to write here. because people who will use the library look for it when they encounter such a problem.
> I signed up wet but how do I find your community group.

Yes, but as I said, **it's not a "problem" with the library**.

You can join the Slack workspace by:
- downloading Slack
- signing in [using the invite link](https://barba.js.org/docs/getstarted/useful-links/#Developer)
- join the `#general` channel and ask questions to the community

> Note that all developers from the community are helping on their own spare time and we are all working on public/private projets, so you will need to be patient in order to get answers to your questions.

Finally, **as specified in the documentation**:
> Notice: this guide assumes intermediate knowledge of HTML, CSS, and JavaScript. It is worth mentioning that all code examples use ES6+ syntax. If you are not comfortable with this syntax, we would encourage you to grasp the basics then come back.

I am using ES6, so that's why you got an error in your script as you just copy/paste/run code in a browser. I have updated the code snippet accordingly.

I am locking the conversation...
Please use Slack instead. :+1:
