### ISSUE TITLE
Barba namespaces for Wordpress Posts

### ISSUE THREAD

**Issue by MichalPietrzok** [barbajs/barba#548]
When i switching between subpages with the **same data-barba-namespace**, **DOM elements are not updated in javasript.** sometimes it is impossible to avoid the same names (for example, if it is a subpages with **wordpress posts**). 

How can i solve this problem

**I am using the latest version of the library**

**Comment by xavierfoucrier** [comment]
Hi @MichalPietrzok,

All your pages need to have **a unique namespace**.
There is no workaround for that.

When loading your WordPress post, you should be able to generate a unique namespace based on the current page, using a custom template.
