### ISSUE TITLE
UNPKG and NPM install errors

### ISSUE THREAD

**Issue by iamtompickering** [barbajs/barba#549]
I have been connecting to the barba core via `https://unpkg.com/@barba/core` but it looks like this has gone down?

When you visit that link, it is coming up with the following: `Cannot find package @barba/core@latest`

Any idea what is going on here? Is this an issue on unpkg side?

**Update**

I have just tried installing it via NPM also, and am getting the following errors: 

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@barba%2fcore - Not found
npm ERR! 404 
npm ERR! 404  '@barba/core@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by xavierfoucrier** [comment]
Hi @iamtompickering,

Everything looks fine from my side.
Can you check it again please?

**Comment by iamtompickering** [comment]
Looks like it is back up and running again now. 

Not sure what that was about, thanks for the quick reply either way!

**Comment by luruke** [comment]
@iamtompickering , npm was down for some time today:
https://status.npmjs.org/
