### ISSUE TITLE
When should I use hooks?

### ISSUE THREAD

**Issue by ZachSaucier** [barbajs/barba#552]
From what I can tell, I can use the same events to fire custom code in both Barba transitions and hooks. Given all of the code that I'm thinking of relates to the transition, my first intuition is to just use the transition function and not have a separate hook as well. When's the best practice for using hooks?

For example here's the same code written with a transition and a hook (I believe):

```
// With a hook
barba.hooks.enter(() => {
  window.scrollTo(0, 0);
});

// With a transition
barba.init({
  transitions: [{
    enter() {
      window.scrollTo(0, 0);
    }
  }]
});
```

**Comment by xavierfoucrier** [comment]
Hi @ZachSaucier,

Of course, you can have the same result when running the same code in a transition or a view... but, `View` are made for namespace-based code by running in a confined place, while `Transition` are made for animation-based logic between pages.

In addition, views are not "promisable", see https://github.com/barbajs/barba/issues/442#issuecomment-546736369.

Hope it's more clear now :wink:
