### ISSUE TITLE
Animation not being fired after new page load

### ISSUE THREAD

**Issue by theinfosecguy** [barbajs/barba#555]
I am using BarbaJS for creating my Portfolio by using <ul> for creating a Page-Transition. I have set up animations such as AutotypeJS and Many More but they aren't getting fired after the Page transition is done. Once I refresh the page, The Animations gets fired.

What could be the possible reason?

**Comment by xavierfoucrier** [comment]
Hi @theinfosecguy,

Can you better explain the issue you encounter please?
Thanks a lot :smiley:

**Comment by xavierfoucrier** [comment]
@theinfosecguy up

**Comment by xavierfoucrier** [comment]
Hi @theinfosecguy,

As Barba makes your site run like a **SPA**, you need to init/call your animations, such as AutotypeJS and others, when the transition to the next page is done. For example in the `afterEnter` hook of a view.

Please take a look at the docs here:
https://barba.js.org/docs/getstarted/custom-code/

I am closing the issue.
