### ISSUE TITLE
after page transition my event "click" is not working 

### ISSUE THREAD

**Issue by INOCcent-afk** [barbajs/barba#565]
function pageTransition() {
  const tl = gsap.timeline();

  tl.to(".first-page-transition-animation", {
    duration: 1,
    transformOrigin: "right",
    scaleX: 1,
  });
  tl.to(".first-page-transition-animation", {
    duration: 1,
    transformOrigin: "right",
    scaleX: 0,
  });
}

function contentAnimation() {
  const tl = gsap.timeline();
  tl.from(".bizzare", { duration: 1.5, translateY: 50, opacity: 0 });
  tl.to(".bizzare", { duration: 1.5, translateY: 0, opacity: 1 });
}

function delay(n) {
  n = n || 2000;
  return new Promise((done) => {
    setTimeout(() => {
      done();
    }, n);
  });
}

barba.init({
  sync: true,

  transitions: [
    {
      async leave(data) {
        const done = this.async();

        pageTransition();
        await delay(1000);
        done();
      },
      async enter(data) {
        contentAnimation();
      },
      async once(data) {
        contentAnimation();
      },
    },
  ],
});

// ***************** THIS EVENT LISTENER NOT WORKING  AFTER TRANSITION

const contactBtn = document.querySelector(".contact-frontPage-button");
const contactForm = document.querySelector(".contact-form");
const contactBtnClose = document.querySelector(".contact-form-closeBtn");

contactBtn.addEventListener("click", () => {
  contactForm.style.transform = "translateX(0%)";
  console.log("working");
});

contactBtnClose.addEventListener("click", () => {
  contactForm.style.transform = "translateX(-100%)";
});
// *****************THIS  EVENT LISTENER NOT WORKING AFTER TRANSITION

**Comment by xavierfoucrier** [comment]
Hi @INOCcent-afk,

This issue is more related to **how your code is running** than Barba v2 implementation...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer

> Please use the appropriate code highlight/syntax when opening an issue, making it readable and understandable...

I am closing the issue.
