### ISSUE TITLE
Import CSS Plugin

### ISSUE THREAD

**Issue by EmilyChews** [barbajs/barba#569]
Hi

I was looking the through the docs and couldn't see how you import the CSS plugin via a CDN like you do with Barba core? Am I missing something here? I'm relatively new to JS although I am currently using GSAP quite a lot. Can you only import the CSS plugin with a build tool NPM/Webpack etc ? I don't really have any knowledge of Webpack etc yet.

Any help or advice greatly appreciated.

**Comment by Ihatetomatoes** [comment]
Hi Emily.

You can include the css plugin like the core itself.

<script src="https://unpkg.com/@barba/core"></script>
<script src="https://unpkg.com/@barba/css"></script>

And initiate it the same way as shown in the docs.

barba.use(barbaCss);

Here is a simple tutorial on Barba and the Css plugin.

https://ihatetomatoes.net/page-transitions-tutorial-barba-with-css/

Hope that helps.

**Comment by EmilyChews** [comment]
Hey thanks Petr. I came across your course earlier because a friend of mine said he learnt greensock / scroll magic with your related courses (pre GSAP scroll-trigger before you updated your courses). Will be having a proper look through later.

Thanks again.
