### ISSUE TITLE
Barba CSS fade-enter-to class and back button

### ISSUE THREAD

**Issue by theamnesic** [barbajs/barba#573]
Hi !

When I am on a page, go to an other page, and use back button, the `barba-enter-to` stay : 

![output](https://user-images.githubusercontent.com/242203/96269968-54c66d00-0fcb-11eb-8060-2b478c34e005.gif)

**Comment by xavierfoucrier** [comment]
Hi @theamnesic,

It's a duplicate of #559.
Closing the issue.
