### ISSUE TITLE
Choose the good transition by link class

### ISSUE THREAD

**Issue by theamnesic** [barbajs/barba#574]
Hi!

I have two transitions (using Barba CSS).
A `direct` one when I click on a link containing `js-direct-transition` class, and a `fade` one for all the others links.

Due to priority order, I tried to do this : 

```js
  transitions: [{
    name: 'direct',
    from: {
      custom: ({ trigger }) => {
        return trigger.classList && trigger.classList.contains('js-direct-transition');
      },
    },
  },
  {
    name: 'fade',
    sync: true,
    once() {},
    leave() {},
    enter() {}
  }]
```

But it doesn't work ... Fire only `fade` transition.

![Capture d’écran 2020-10-16 à 18 17 18](https://user-images.githubusercontent.com/242203/96283055-e2aa5400-0fdb-11eb-9dc5-99ad15559ea4.png)

Is my logic right or I'm missing something ?

Thanks!

**Comment by seamofreality** [comment]
Hey there, is it possible this might be the right strategy for you?
https://barba.js.org/docs/advanced/strategies/#prevent

**Comment by xavierfoucrier** [comment]
Hi @theamnesic,

You are missing the **transition definition itself** for your custom rules.

This should work:

```js
transitions: [{
  name: 'direct',
  from: {
    custom: ({ trigger }) => {
      return trigger.classList && trigger.classList.contains('js-direct-transition');
    },
  },
  leave() {}, // <-- this will be played when clicking on links that matches `.js-direct-transition`
}, {
  name: 'fade',
  sync: true,
  once() {},
  leave() {},
  enter() {}
}]
```

Not sure if the `sync` keywords should be a problem in your case, let me know :wink:

**Comment by theamnesic** [comment]
Hi Xavier, 

Ok I see, the misunderstanding here is that I don't need barbaCss for the `direct` transition (just a basic replacement), only for `fade`.

In that case we have to use barbaCSS for just one transition, what do you advise ?
Is simulating a basic replacement like that is a good way ?

```js
  transitions: [{
    name: 'direct',
    from: {
      custom: ({ trigger }) => {
        return trigger.classList && trigger.classList.contains('js-direct-transition');
      },
    },
    once() {},
    leave() {},
    enter() {}
  }, {
    name: 'fade',
    sync: true,
    once() {},
    leave() {},
    enter() {}
  }]
``` 

```css

/* Direct */

.direct-leave-active,
.direct-once-active,
.direct-enter-active
  transition opacity 0s ease


.direct-leave,
.direct-once-to,
.direct-enter-to
  opacity 1


.direct-enter,
.direct-once,
.direct-leave-to
  opacity 0

/* Fade */

.fade-leave,
.fade-enter-to
  opacity 1

.fade-enter,
.fade-leave-to
  opacity 0

.fade-once
  opacity 0

.fade-leave-active,
.fade-once-active,
.fade-enter-active
  transition opacity 0.7s ease-in-out-expo

.fade-enter-active
  position fixed
  width 100vw
  top 0
  z-index 3
```

Thanks !

**Comment by xavierfoucrier** [comment]
Hi @theamnesic,

You can't just use **@barba/css** for one transition, then rollback to **@barba/core** with JS animations...
The plugin is made for people that prefer working with CSS transitions, so if you enable it, then all your transitions will run under **@barba/css**.

If your site doesn't require complex animations, it is recommended to only use **@barba/css** for all your transitions. If it's not the case, use **@barba/core** instead. Personally, I never had a case study where I needed to use both.

**Comment by theamnesic** [comment]
Thank you for this clarification Xavier!

**Comment by xavierfoucrier** [comment]
@theamnesic always a pleasure to help Barba's community! :wink:
