### ISSUE TITLE
Error import barba 

### ISSUE THREAD

**Issue by akashshyamdev** [barbajs/barba#578]
While using barba js with npm, I'm getting the following error - Uncaught ReferenceError: regeneratorRuntime is not defined. The code is - 

```
import barba from '@babel/core';
import barbacss from '@barba/css';
function pageTransition() {
	barba.use(barbacss);

	barba.init({
		transitions: [
			{
				once() {},
			},
		],
	});
}
pageTransition();
```

So I tried importing using a cdn - 
```
	<script src="https://unpkg.com/@barba/core"></script>
	<script src=" https://unpkg.com/@barba/css"></script>
	<script src="./js/index.js"></script>
```

It shows barbacss is undefined. It is said in the official website that plugin must be used differently. However I could not find the way to use barba plugins using cdn on the official webpage. Please help.

**Comment by xavierfoucrier** [comment]
Hi @akashshyamdev,

You made a typo, it's `barbaCss`, not `barbacss`.
See https://barba.js.org/docs/plugins/css/.

> Read the documentation carefully.

I am closing the issue :wink:
