### ISSUE TITLE
Silent for errors in scripts

### ISSUE THREAD

**Issue by BaranovRoman** [barbajs/barba#579]
Hi, first of all thank you for Barba, it's great, and well documented. 
I'm working with Barba for the first time, and sometimes the components don't work, but there's nothing in the console, and I have to manually search for the component after which the scripts don't work. Has anyone else encountered this, and is there any solution? I just added a timeout to one script, and got an error in the console, maybe this will help someone.

**Comment by xavierfoucrier** [comment]
Hi @BaranovRoman,

You need to read the docs first before diving into BarbaJS.
By default, the `debug` mode is disabled.

Learn more here:
https://barba.js.org/docs/advanced/recipes/#Debug-with-Barba

I am closing the issue :wink:

**Comment by BaranovRoman** [comment]
Thank you very much for very fast answer! My bad :)

**Comment by xavierfoucrier** [comment]
@BaranovRoman no problem! Welcome to the Barba community :wink:
