### ISSUE TITLE
afterLeave hook not called for Views

### ISSUE THREAD

**Issue by richardcalahan** [barbajs/barba#583]
I'm on version 2.9.7. 

All other applicable hooks for views are called correctly. Globally, the afterLeave hook is called correctly too, just not for Views specifically.

**Comment by xavierfoucrier** [comment]
Hi @richardcalahan,

Thanks for opening the issue, I will investigate shortly :wink:

**Comment by xavierfoucrier** [comment]
Alright, I guess it's a mistake or it's not really an issue haha :smile: 
Thanks for closing it fast!

**Comment by richardcalahan** [comment]
Hey, sorry, i think i had a bug in a global callback that was suppressed by Barba transition. I wasn't in dev mode.

Thanks for the quick reply.
