### ISSUE TITLE
For google analytics, document.title should be updated before call to pushstate

### ISSUE THREAD

**Issue by andersdn11** [barbajs/barba#584]
Using gtag and history change, we see the pages being added to Google analytics but their assiociated page title is the title of the previous page. 

gtag updates every time it detects a push state change, but the new document title is not available at that time, giving the old title instead.

**Comment by xavierfoucrier** [comment]
Hi @andersdn11,

You need to push the Google Analytics traffic at the right time in your application, when the `next` page is fetched by Barba: in the `enter` hook for example, by just retrieving it with a simple `document.title`, then push stats using `gtag('config', ..., { 'page_title': document.title, ... });`.

If you try to access `document.title` before `beforeEnter` hook, you won't be able to get the `next` page title.

> See https://barba.js.org/docs/getstarted/lifecycle/.

**Comment by andersdn11** [comment]
Just for anyone coming by later. The suggestion pointed me in the right direction. I however had to push an event instead.
Remember to create you variables in tag manager.

```
function GTM_push_pageview_layer() {
	
	window.dataLayer = window.dataLayer || [];
	window.dataLayer.push({
		'event': 'Pageview',
		'page_title': (document.title) ? document.title : '',
		'page_URL': (window.location.href) ?  window.location.href : '',
		'page_path': (window.location.pathname) ? window.location.pathname : '',
		'page_hash': (window.location.hash) ? window.location.hash : '';
	});
}

```

```
barba.hooks.after((data) => {

	GTM_push_pageview_layer()

});
```

**Comment by mantrone** [comment]
@andersdn11 excuse my ignorance: did you put something in the <head> of your site? 
Is that code complete? 
I never see in your code the gtag() function. Is that right?

**Comment by andersdn11** [comment]
@mantrone Sorry, yes i placed the gtag script in head:

`
		<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-XXXXX');</script>
		`

**Comment by mantrone** [comment]
@andersdn11 ty for your response.

did you also put another code inside the `<body>` like this one? 

`<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-XXXXXXX" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>`

This is second piece of code that provided by GTM when creating the property in addition to what you wrote above. What position did you put it in?

**Comment by Anders3byg** [comment]
Yes, you should add that as well, but outside your barba-container, so it doesn't initialize more than once. 
But that noscript is not that important IMO. Just for tracking people with javascript turned off.

**Comment by mantrone** [comment]
@Anders3byg a ok, thanks. 

it is quite difficult to set up all tracks, but I think it now depends on GTM, not that much on Barba js.

if I wanted to add, just for example, a track at the click of buttons specifics, I have to create a custom event from GTM and implement the code down here by adding the data of the created event, right?

```
function GTM_push_pageview_layer() {
	
	window.dataLayer = window.dataLayer || [];
	window.dataLayer.push(
        {
		'event': 'Pageview',
		'page_title': (document.title) ? document.title : '',
		'page_URL': (window.location.href) ?  window.location.href : '',
		'page_path': (window.location.pathname) ? window.location.pathname : '',
		'page_hash': (window.location.hash) ? window.location.hash : '';
	}, 
        {
                'event': 'Customclick',
	        'button_id': ... ,       
        });
}
```

**Comment by Anders3byg** [comment]
This code is only for the issue with PJAX websites and tracking of virtual pageviews.
If you want to track button clicks etc.. you should just follow the guides from google, thats not barba related and should not cause conflicts with barba.

I would write a new function for those events :)
