### ISSUE TITLE
Disable on mobile device / small screens

### ISSUE THREAD

**Issue by brentnl** [barbajs/barba#585]
Hi, 

can't find it anywhere in the documention, but how can I disable the whole script/transitions on mobile (screenwidth less then 768px).

Kind regards,
Brent

**Comment by xavierfoucrier** [comment]
Hi @brentnl,

Thanks for opening the issue.
It's a good question, unfortunately, there is no option to tell Barba to prevent all transitions on mobile device / small screens.

You can **implement your own logic** by checking the User Agent or screen size, and prevent calling `barba.init()`. This way the library won't be enable on mobile device. If you need to manage resize events and switch between Barba enable/disable states, then you can init the instance, destroy it using the `.destroy()` util method, then init it again next time.
> See https://barba.js.org/docs/advanced/utils/.

Hope this help!
Let me know, and feel free to close the issue :wink:

**Comment by brentnl** [comment]
Hi @xavierfoucrier , thanks for the fast response. You pointed me in the right direction, so I came up with this;
`window.addEventListener('load', function(){
if(screen.width > 1050) {
    init();
    }
});`

Pretty simple, and it does the job. Thanks.

**Comment by xavierfoucrier** [comment]
@brentnl Glad to help! :wink:
