### ISSUE TITLE
mouse hover sends request

### ISSUE THREAD

**Issue by BigGitWorld** [barbajs/barba#586]
Solution to the title: 
It was pre-fetching and disabled it.

**Comment by BigGitWorld** [comment]
ooops!
It is pre-fetching! I solved it.

**Comment by xavierfoucrier** [comment]
Hi @BigGitWorld,

This is a Barba **internal default behavior** to improve page speed.
Of course you can disable it, but Barba use it to improve page transitions, so you shouldn't in fact.

Glad you find a solution.
