### ISSUE TITLE
Inverse of .no-barba?

### ISSUE THREAD

**Issue by jrvanstone** [barbajs/barba#589]
Hey,

First of all, great library 👍  I'm currently using Barba with GSAP and it works a treat! I just have a use case query to see what your recommended usage/solution would be. 

**Pre-requisites:**

- My header has entrance animations using anime.js, I only want these to animate when the page is first loaded;
- Animations work as expected, only links inside the barba container cause animation, anything outside causes a full reload;

**The Problem:**

I have page links in my header, but because these sit outside of the barba container (in order to not reload the header on page transition), when I click them it forces a reload. I guess my question is, other than creating a list of menu items inside the barba container, hiding them and firing a click(); event with jS when a user clicks on a menu item, is there a native way to manage this in Barba?

Can I somehow use links which are inside the barba wrapper but outside the barba container to trigger my page animations?

Thanks!

**Comment by xavierfoucrier** [comment]
Hi @jrvanstone,

Default inverse of `.no-barba` is, well, Barba itself ^^

If I understand your problematic correctly, you wan't to call Barba transitions on links that are outside of the container?
This is possible by using the internal `.go()` [utils method](https://barba.js.org/docs/advanced/utils/).

> See API here: https://barba.js.org/api/classes/_core_src_core_.core.html#go.

Let me know if it works and feel free to close the issue when its done :wink:

**Comment by jrvanstone** [comment]
Hey Xavier,

Perfect thank you, I have this working but only the first time it fires. For example:

1. Click header link, (outside of barba) and fire this:

```
$(".ui-item-client-2").click(function () {
    barba.go("/page2.html");
});
```

This works perfectly, however once on page2.html if I click the same function to return:

```
$(".ui-item-client-1").click(function () {
    barba.go("/page1.html");
});
```

This breaks the transition. Am I supposed to be clearing something after running the go() util? _If I do a force refresh on either page the transition works the first time (in either direction i.e P1 -> P2 or P2 -> P1), but on future clicks it breaks._

Sorry if I'm missing something and thanks again!

**Comment by xavierfoucrier** [comment]
Hi @jrvanstone,

Normally, there is nothing to call after `.go()` :thinking: ...
May be you got an error inside your transition, did the `debug` mode is enabled on your Barba settings?

> See https://barba.js.org/docs/advanced/recipes/#debug.

**Comment by jrvanstone** [comment]
Hey @xavierfoucrier,

I enabled debug but there's nothing showing in console using:

```
barba.init({
  debug: true,
  logLevel: 'error'
});
```

What's weird is that I managed to patch this by setting the fade-in animation from `gsap.from` to `gsap.to` and by firing an `opacity: 0;` value on beforeEnter. It's a work-around but it works consistently with no glitching/performance lag, although I still have issues with the `barba.go();` util.

For some reason links inside the barba-container animate correctly, even with my custom animation scripts for other page elements, and my reinitialised jS script, however when using the .go(); function to call the same barba transition, my reinit script piles up functions sequentially, so every time I switch pages the load time doubles until it becomes unusable.

Are the any guidelines around using the .go(); method with other jS scripts that differ from general usage of links inside the barba container?

**Comment by jrvanstone** [comment]
Update:

I've found a way to refactor this so that barba, gsap and my custom animations work together, the solution is to move the header into the barba container and have the animations trigger without using the _.go();_ util. Obviously this causes the initial problem of my entrance animations playing each time a page transition is made, so I am going to wrap these so that they only play on a force reload, something to [this](https://stackoverflow.com/a/17986241/10084649) effect.

As for the `.go();` util conflict it seems the best solution if it doesn't play ball (baring in mind I am using a lot of jS animations and other scripts so the probability of a conflict somewhere is fairly high) is to simply restructure the page to work as a default barba config (i.e all `<a>` tags inside the `barba-container` element) and then refactor any other code to behave as desired.

Thanks for your help on this one anyway @xavierfoucrier!

**Comment by xavierfoucrier** [comment]
Hi @jrvanstone,

Glad that you find a workaround, but without a minimal reproductible test repository its almost impossible to reproduce and understand your issue(s).

Anyway, thanks for your feedback! :wink:
