### ISSUE TITLE
HTML 5 Video not autoplaying

### ISSUE THREAD

**Issue by fingerprintscreative** [barbajs/barba#596]
Hi All,

I have a bunch of html5 videos on my home page thats on autoplay, loop & Muted. When i navigate away from the homepage and come back the video is not autoplaying. It is playing only when i reload the page. I am new to barba. Requesting you guys to guide me to solve this issue. Thanks a lot.

```
    <video  muted autoplay loop playsinline   width="100%">
    <source src="images/boyandgirl.mp4" type="video/mp4">
  Your browser does not support the video tag.
  </video>
```

```
Barba setup:

function contentAnimation() {
// All my animations are here.
}

function delay(n) {
    n = n || 2000;
    return new Promise((done) => {
        setTimeout(() => {
            done();
        }, n);
    });
}

barba.init({
    sync: true,

    transitions: [
        {
            async leave(data) {
                const done = this.async();
data.current.container.remove();
                pageTransition();
                await delay(1000);
                done();
            },
            
            async beforeEnter(data) {
				ScrollTrigger.getAll().forEach(t => t.kill());
			},
            async enter(data) {
                contentAnimation();
            },

            async once(data) {
                contentAnimation();
            },
		},
	],
});

barba.hooks.enter(() => {
    window.scrollTo(0, 0);
});
```

You can check it here: http://fingerprints.co.in/bharathi/

**Comment by xavierfoucrier** [comment]
Hi @fingerprintscreative,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

**Comment by dash-james** [comment]
`var vid = document.querySelectorAll("video");
for (let i = 0; i < vid.length; i++) {
	var playPromise = vid[i].play();
	if (playPromise !== undefined) {
			playPromise.then(_ => {})
			  .catch(error => {});
	};
};`

Place this in your afterEnter hook - it should autoplay your videos.
However, I'd suggest using a intersectionObserver in conjunction with the above, so that they only play when in view.
