### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "@barba/core"

### ISSUE THREAD

**Issue by nvminhhieu** [barbajs/barba#597]
# Uncaught TypeError: Failed to resolve module specifier "@barba/core". Relative references must start with either "/", "./", or "../".

### I got this issue in the browser when I'm following the installation steps. ("npm install @barba/core" then "import barba from '@barba/core' "). 

It doesn't throw any errors on my VS Code, only on the browser. 

Things I have tried: 

1. Add "type = module" in index.js script 
2. Using CDN method, which works fine!

So how can I fix this npm import issue so I can use import @barba/css plugins?

**Comment by xavierfoucrier** [comment]
Hi @nvminhhieu,

This is **definitely not a barba issue**.
If you want to use **native ES modules** with a Barba plugin, just do:

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Barba</title>
  </head>
  <body data-barba="wrapper">
    <main data-barba="container">
      <!-- page content here -->
    </main>
    <script type="module">
      import barba from 'https://unpkg.com/@barba/core@2.9.7/dist/barba.mjs';
      import barbaCss from 'https://unpkg.com/@barba/css@2.1.15/dist/barba-css.mjs';

      // tell Barba to use the css plugin
      barba.use(barbaCss);

      // init Barba
      barba.init();
    </script>
  </body>
</html>
```

> Barba is build upon `microbundle`, so the `mjs` version is provided into the NPM package: https://unpkg.com/browse/@barba/css@2.1.15/dist/.

Hope this help!
I am closing the issue :wink:

**Comment by nvminhhieu** [comment]
Aha thanks for your help! Sorry I am a newbie in this npm thing. 
So if I want to install like the way that is shown on barba.js website, I would need a bundle tool like Webpack or Browserify to compile the barba.js modules and my .js file so it can be use on the browser right?

**Comment by xavierfoucrier** [comment]
No problem! Glad to help :wink: 
Exactly. NPM/Yarn package installation is required when using a bundler.
