### ISSUE TITLE
Page transition reload the page then go to anchor element in Fullpage.js

### ISSUE THREAD

**Issue by nvminhhieu** [barbajs/barba#598]
## Page transition reload the page then go to anchor element instead of go to anchor element 

I'm using Fullpage.js with Barba for my project. The issue I'm dealing with is when I'm transit to another page anchor (eg. index.html#projects), after the enter() stage, the page index.html got reloaded, then start to scroll down to the anchor (#projects) instead of transit straight to the anchor. 

I want the page transition to **go straight to the anchor** instead of reload the page then scroll down to the anchor. I'm thinking about these ways but I don't know how to do it:

1. Make the index.html page re-loading and scroll to anchor process run at the same time and behind the animation transition to create illusion of transit to anchor of the page. 
2. Hide elements of the first section of the page so the reload and scroll is not visible since section has same background. 

Here is the replication of the problem in Codepen: https://codepen.io/ntobyh/project/editor/AnGQEe

**Comment by nvminhhieu** [comment]
I figure this is more like a fullpage.js problem because even without barba, the page transition to a fullpage page still go from top first!

**Comment by xavierfoucrier** [comment]
Hi @nvminhhieu!

Didn't notice your opened issue today :smile: 
Thanks for your feedback, sounds clear that it's related to fullpage library.

Happy coding with Barba! :tada:
