### ISSUE TITLE
Problem bundling Parcel-Bundler with BarbaJS

### ISSUE THREAD

**Issue by ksh-r** [barbajs/barba#599]
## Prerequisites
- npm
- parcel-bunder (installed globally)
- Visual Studio Code (with Live Server Extension)
---

## The problem
Not able to use BarbaJS using Parcel-Bundler's Local Server.
The project breaks down when running on Parcel-Bundler's Server but works perfectly on VS Code's Live Server

## Description
Please check [ barba-parcel-test ](https://github.com/ksh-r/barba-parcel-test) repo where I have shown the problem using a simple 2 page transition.

This issue is posted as a minimal reproduction was requested when discussed on Slack.

---

## Relevant Links

- **My repo:** [ barba-parcel-test ](https://github.com/ksh-r/barba-parcel-test)

## Environment

- Barba version that exhibits the issue: [CDN](https://unpkg.com/@barba/core) Barba v2

**Comment by xavierfoucrier** [comment]
Hi @ksh-r,

Thanks for opening the issue :wink: 
We will give a look at this as soon as possible.

**Comment by AndreaBaccolini** [comment]
Does anyone have a solution for this error?

**Comment by ksh-r** [comment]
Hi @AndreaBaccolini, I switched onto using Webpack because BarbaJS didn't seem to work with Parcel (at least for me)
In the documentation, BarbaJS has a really good starter kit for Webpack so it shouldn't be a problem figuring that out.
Hope this helps :)

**Comment by xavierfoucrier** [comment]
@AndreaBaccolini, @ksh-r I need to have a look at this and give a feedback here, thanks for your patience :wink:

**Comment by AndreaBaccolini** [comment]
> Hi @AndreaBaccolini, I switched onto using Webpack because BarbaJS didn't seem to work with Parcel (at least for me)
> In the documentation, BarbaJS has a really good starter kit for Webpack so it shouldn't be a problem figuring that out.
> Hope this helps :)

Anyway with parcel v2 does not give errors.

**Comment by ksh-r** [comment]
> > Hi @AndreaBaccolini, I switched onto using Webpack because BarbaJS didn't seem to work with Parcel (at least for me)
> > In the documentation, BarbaJS has a really good starter kit for Webpack so it shouldn't be a problem figuring that out.
> > Hope this helps :)
> 
> Anyway with parcel v2 does not give errors.

@AndreaBaccolini would it be possible for you to make a template repository and share it here? It would really help anyone who encounters this thread in the future.

**Comment by xavierfoucrier** [comment]
I am currently **investigating on this issue**.

**Comment by xavierfoucrier** [comment]
@AndreaBaccolini @ksh-r Sorry for the late reply... :roll_eyes: 

Both `parcel-bundler` (v1) and `parcel` (v2) works fine with `@barba/core`.
As your test repository is not available anymore, I have made a simple test with two `.html` pages and an `index.mjs` file with only:

```js
import barba from '@barba/core';

barba.init();
```

Page transitions works fine in both cases.

> Note that `parcel-bundler` is clearly **not supported anymore** by the Parcel team, so you should consider migrating following the dedicated online guide here: https://parceljs.org/getting-started/migration/.
