### ISSUE TITLE
Anchor tag element getting fired on hover or enter

### ISSUE THREAD

**Issue by mepiphany** [barbajs/barba#603]
## The problem

I am using ROR

ruby version 2.6.5
rails version 6.0.3.4

Very strange behaviour is happening, whenever I hover over a link it triggers a request however it doesn't fully redirect to that specific page.

I have a send email button which has a data-confirm event handler but his bypasses the confirmation and sends an email whenever I hover over.

Can someone help me with this bug? thank you so much!

Cheers,

**Comment by xavierfoucrier** [comment]
Hi @mepiphany,

This is **a Barba internal feature** called "prefetch".
Have a look at https://barba.js.org/docs/advanced/strategies/#Prefetch.

You can fully disable this feature on your application, bypass some links using a "prevent" test or bypass a single link using `data-barba-prevent="self"` attribute, see https://barba.js.org/docs/advanced/strategies/#prevent.

Happy coding with Barba! :wink:
