### ISSUE TITLE
Support for nextjs?

### ISSUE THREAD

**Issue by andrewnijmeh** [barbajs/barba#606]
Are you guys seeing yourself supporting barba for nextjs in the near future?

**Comment by otmanecherradi** [comment]
I would really want to know this too, I'm currently working on a ReactJS/NextJS website and I wanted to use barbaJS. Adding support for that would be great.

**Comment by xavierfoucrier** [comment]
Hi @andrewnijmeh @otmanecherradi,

Sorry for the late reply.
For now, this is not planned.

We will need more time to have a look at the implementation, write associated documentation and pre-requisites, just to be sure you can use them together without any issues. May be someone already have a look at this: ask the community on Slack.

For now, there is other ReactJS frameworks that you can use to build page transitions, like **Framer Motion**.
But I guess you know that :wink:
