### ISSUE TITLE
global hooks

### ISSUE THREAD

**Issue by Norb48** [barbajs/barba#608]
Hi @thierrymichel, 
I guess you will not be happy to hear the same complain,sorry

loading external js. is nothing new I realised but still problem for me ,I spend a lot of time to looking for solution. I'm using barba 2.9.7 and really happy how it works for me, all transitions works just FINE as I want ,but Loading 20 lines of code for switching class works only on hard reload and after transition no more , i used global hooks and view , I have no clue where I'm wrong. 

here is my   code  

import barba from '@barba/core';
import barbaPrefetch from '@barba/prefetch'
import gsap from 'gsap';
import '../css/style.scss';
import animOnes from './animOnes';
import animEnter from './animEnter';
import animLeave from './animLeave';
import leaveToProject from './leaveToProjekt';
import enterToProject from './enterToProjekt';
import myScroll from './scroll';

barba.use(barbaPrefetch);

const reset = () => gsap.set('.scroll', {
  yPercent: 120
})
const resetNav = () => gsap.set('.rightnav-link', {
  autoAlpha: 0
})

barba.hooks.afterEnter((data) => { 
  myScroll() 
})

barba.init({
  debug: true,

  schema: {
      prefix: 'data-project',
    },

    transitions: [{
        name: 'leaveToProject',
        to: {
          namespace: ['work']
        },
        leave: ({
          current
        }) => leaveToProject(current.container),
        enter: ({
          next
        }) => enterToProject(next.container)
      },
      {
        name: 'default',
        once({
          next
        }) {
          reset()
          resetNav()
          gsap.from('.leftnav-link', {
            duration: 0.7,
            autoAlpha: 0,
            stagger: 0.6,
            ease: 'power1.in',
            onComplete: () => animOnes(next.container)
          })
        },
        leave: ({
          current
        }) => animLeave(current.container),

        enter: ({
          next
        }) => animEnter(next.container)
     }
    ]
 })

and myScroll code which actually switching class sections nav ......

let myScroll;
let sectionsScroll = document.querySelector('.scroll');
let sections = document.querySelectorAll('.section-link');
let rightNav = document.querySelectorAll('.rightnav-link');
let windowHeight = window.innerHeight;

myScroll = function reset() {
  rightNav.forEach(function (link) {
    link.classList.remove('current-section')
  })  
}

sectionsScroll.addEventListener('scroll', function () {
  let scrollTop = sectionsScroll.scrollTop;
  sections.forEach(function (section, i) {
    if (section.offsetTop < scrollTop + windowHeight / 4 && scrollTop < section.offsetTop + windowHeight / 4) {
      myScroll();
      rightNav[i].classList.add('current-section');
    }
  })
})
export default myScroll

**Comment by xavierfoucrier** [comment]
Hi @,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

**Comment by Norb48** [comment]
@xavierfoucrier , thank for your quick answer , I will definitely look at Slack
