### ISSUE TITLE
Contact Form 7 Wordpress work one time 

### ISSUE THREAD

**Issue by francescocortese** [barbajs/barba#611]
The CF work only one time when I load the form for the first time, after load barba the form doesn't work. 
I tried this code:
```
beforeEnter({ next }) {
  var cf_selector = 'div.wpcf7 > form';
  var cf_forms = $(next.container).find(cf_selector);
  if (cf_forms.length>0) {
      $(cf_selector).each(function() {
          var $form = $(this);
          wpcf7.initForm( $form );
          if ( wpcf7.cached ) {
              wpcf7.refill( $form );
          }
      });
  }
```
But when I click to change the page, the page doesn't load.

I tried also:
`$( 'div.wpcf7 > form' ).each( function() { var $form = $( this ); wpcf7.initForm( $form ); if ( wpcf7.cached ) { wpcf7.refill( $form ); } });
`
But I get this from console:
`wpcf7.initForm is not a function`
Any help?

Thanks.

**Comment by francescocortese** [comment]
The newest version of wpcf7 needs some code changes:
```
barba.init({

  transitions: [{
    name: 'opacity-transition',
beforeEnter: function({ next }) {
      var cf_selector = 'div.wpcf7 > form';
      var cf_forms = $(next.container).find(cf_selector);
      if (cf_forms.length>0) {
         $(cf_selector).each(function() {
          var $form = $(this);
          wpcf7.init( $form[0] ); 
        });
      }   
    },
... 
}]
});

```
Check on 
Duplicate of #122

**Comment by xavierfoucrier** [comment]
Hi @francescocortese!

Thanks for closing the issue and providing further informations :wink:

**Comment by Louboutin1017** [comment]
@francescocortese 
Thanks for this fix, almost gave up on Barba JS.

Please incase of any code changes from Contact Form 7, kindly address it here.

The author of this great framework, made it only for Javascript professionals. 

I hope they expand their documentation on important issues like Contact Form 7 or Gravity Form and transitions.

Thanks again.

**Comment by xavierfoucrier** [comment]
Hi @Louboutin1017,

> The author of this great framework, made it only for Javascript professionals.
What do you mean with this..?

> I hope they expand their documentation on important issues like Contact Form 7 or Gravity Form and transitions.
That's why the world still needs developers today, because a great framework can't support all scripts/codes from everyone.

:wink:
