### ISSUE TITLE
Barba container appears underneath of Locomotive Scroll.

### ISSUE THREAD

**Issue by elebumm** [barbajs/barba#614]
Love the package. I use it a lot.

I am using Locomotive Scroll for my pages. I am having issues when it comes to new pages using the doucmentation that is currently up. On there, it suggests to have the `container` nested within the `data-scroll-container`.

```
<div class="main-content-container cowork" data-barba="wrapper">
      <div data-scroll-container>
        <div data-barba="container" data-barba-namespace="page"  >
```

I have it set up like this. In my pageanimations.js:

```
import barba from '@barba/core';
import { gsap, Power4 } from 'gsap';
import initPageScripts from './cowork';
import scroll from './scroll';


export default function barbaInit() {
  barba.hooks.after((data) => {
    if (data.next.namespace === 'page') {
      scroll.update();
      initPageScripts();
    }
  });

  barba.init({
    transitions: [
      {
        name: 'page-transition',
        leave(data) {
          const done = this.async();
          gsap.to(data.current.container, {
            opacity: 0,
            ease: Power4.easeOut,
            onComplete: () => {
              done();
            },
          });
        },

      },
    ],
  });
}
```

I have it so that the scroll updates.

scroll.js:
```
import LocomotiveScroll from 'locomotive-scroll';

export default new LocomotiveScroll({
  el: document.querySelector('[data-scroll-container]'),
  smooth: true,
});
```

Whenever I implement it like this, it causes the scroll to still show up and reinitialize, but it appears above the container (without wrapping).

<img width="1471" alt="Screen Shot 2021-04-01 at 5 01 41 PM" src="https://user-images.githubusercontent.com/6053155/113353660-0522f600-930c-11eb-83ef-9b0e22bfe255.png">

Appreciate the help. What's the reason that Locomotive wouldnt be able to catch the container?

**Comment by Dushyant1295** [comment]
` 
<body data-dpk="wrapper">   
  <main data-barba="container" data-barba-namespace="PageName">
        <div data-scroll-container>
               <section data-scroll-section >
                   ....
                </section>
        </div>
    </main>
 <script src="js/bundle.js"></script>
</body>
`

**Comment by Dushyant1295** [comment]
Use Like This

**Comment by Dushyant1295** [comment]
```

<body data-dpk="wrapper">   
  <main data-barba="container" data-barba-namespace="PageName">
        <div data-scroll-container>
               <section data-scroll-section >
                   ....
                </section>
        </div>
    </main>
 <script src="js/bundle.js"></script>
</body>
```

**Comment by xavierfoucrier** [comment]
Hi @elebumm,

There are **many ways of implementing Barba with locomotive scroll**, really depends on your layout and what kind of element you want to make scroll. The official documentation only shows a working example on how you can implement it with ease, and there is a side note attached to it:

> it can be whenever you want on the page, no matter outside or inside Barba wrapper/container, but keep in mind that when using it inside the Barba container, it will be duplicated. Bear with this!
> 
> Note that this code assume that you have the data-scroll-container attribute on every pages, so you need to add the appropriate checks if LocomotiveScroll is not used on the whole site.

In addition, you can find a full repository with open source code here:
https://github.com/Ihatetomatoes/barbajs-demos/tree/master/barbajs-gsap-locomotive-scroll

Live working demo right here:
https://ihatetomatoes.net/demos/barbajs/barbajs-gsap-locomotive-scroll/

Hope this help! :wink:

**Comment by elebumm** [comment]
Appreciate the resource @xavierfoucrier. I found that I needed to update my @barba/core, I was really behind on versions.

**Comment by xavierfoucrier** [comment]
@elebumm I appreciate the feedback, thank you! :wink:
