### ISSUE TITLE
Barbajs and wordpress scripts

### ISSUE THREAD

**Issue by AndreVictor** [barbajs/barba#615]
I`m tring to use barbajs with a theme that I'm developing. To install barba, I used wp_register_script and wp_enqueue_script in function.php file: 
```

	wp_register_script( 'barba', 'https://cdnjs.cloudflare.com/ajax/libs/barba.js/0.0.2/barba.min.js', null, null, true );
	wp_enqueue_script('barba');
```
then, in my main.js file I have had initialized barba like documentation with: 
```
barba.init({
	
	sync: true,

	transitions:[{

		async leave(data) {

			const done = this.async();

			pageTransition();
			await delay(2000);
			done();

		}
	}]

});
```
However, I receive barba is not defined in console. Any one know what can be this?

**Comment by xavierfoucrier** [comment]
Hi @AndreVictor,

You just need to use the appropriate Barba version :wink: 
Here is the link to the latest UMD build: https://unpkg.com/@barba/core

I am closing the issue.
