### ISSUE TITLE
Where to put the PreventCheck code that decides what links are used by Barba and not?

### ISSUE THREAD

**Issue by fredy31** [barbajs/barba#616]
Preventing some links from being 'barbafied'... there is a bunch of code here that says exactly how do to it: https://barbajs.org/faq.html (as referred in another issue: https://github.com/barbajs/barba/issues/61)

````` js
Barba.Pjax.originalPreventCheck = Barba.Pjax.preventCheck;
Barba.Pjax.preventCheck = function(evt, element) {
  if (!Barba.Pjax.originalPreventCheck(evt, element)) {
    return false;
  }
  // No need to check for element.href -
  // originalPreventCheck does this for us! (and more!)
  if (/.pdf/.test(element.href.toLowerCase())) {
    return false;
  }
  return true;
};
`````

Thing is, I have no clue where the hell that code is supposed to go. I try to put it right before barba.init (that works) and I get an error : `main.js:118 Uncaught TypeError: Cannot read property 'preventCheck' of undefined``

I need to do so (and not the no-barba class) because this is a wordpress site that will be used by non-programmer people. They will not do such a small thing. And right now, when you click on a PDF link, Barba loops the page on itself.

So where am I supposed to put the custom condition for what links are used by barba and not?

**Comment by xavierfoucrier** [comment]
Hi @fredy31,

Unfortunately, Barba v1 is no longer maintained...
You should [**take a look at the v2**](https://barba.js.org/).

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

I am closing the issue.

**Comment by fredy31** [comment]
Bug is probably that I'm mixing V1 and V2... so what would be the code to do about the same?

**Comment by xavierfoucrier** [comment]
@fredy31 right here https://barba.js.org/docs/advanced/strategies/#Prevent

😉
