### ISSUE TITLE
Prevent page from looping on itself if the page afterwards may be on the same domain, but not 'barba able'

### ISSUE THREAD

**Issue by fredy31** [barbajs/barba#617]
I have two types of URLs that seem to make Barba loop on itself.

Clicking on a PDF or pages that redirect to something else.

In both instances, Barba does the exit animation, but then seems confused, and intros back the same page. Is there any way to if the page would be to loop on itself, instead follow the link as-is and not break navigation?

**Comment by xavierfoucrier** [comment]
Hi @fredy31,

Please create a minimal reproductible test repository for those issues.
Thanks a lot :wink:
