### ISSUE TITLE
barba.umd.js:1 Uncaught TypeError: Cannot read property 'action' of undefined

### ISSUE THREAD

**Issue by fredy31** [barbajs/barba#619]
Barba sometimes seem to block, mid page transition.

I'm trying to debug it but getting this error and having a hard time to figure out what triggers it (it would need to have more details, if I could request it)

<img width="1289" alt="Screen Shot 2021-04-23 at 3 09 44 PM" src="https://user-images.githubusercontent.com/2183470/115918800-f381c980-a445-11eb-98aa-6d25152a463e.png">

Or, if it's a very had thing to help me debug without seeing the code, is there a 'debug mode' that could give a more detailed answer?

**Comment by fredy31** [comment]
For the debug mode, I'll use the friday defense and say that my brain seems to be fried.

But here is with the debug mode what I'm hitting.
<img width="1296" alt="Screen Shot 2021-04-23 at 3 15 03 PM" src="https://user-images.githubusercontent.com/2183470/115919392-c550b980-a446-11eb-998c-b61d9c007073.png">

**Comment by xavierfoucrier** [comment]
Hi @fredy31,

**It's due to a long server response**, in fact, greater than 2 seconds, which is the default `timeout` in Barba.
Take a look at the documentation here: https://barba.js.org/docs/advanced/recipes/#timeout.
