### ISSUE TITLE
Flickering content during transition

### ISSUE THREAD

**Issue by anta199** [barbajs/barba#629]
Hello,
First of all, thanks for the amazing work.

I've implemented an 'slide-type' page transition that uses transform CSS property to 'push' the current page and slide the next one.
It all works fine but I get that super-quick half a second flicker/flash of content  during the transition.

Things I noticed are:
- It only happens when sync is true
- It tends to happen if I scroll down a bit, not if I'm in the top of the page

I'm aware that this might be just some issue in my code or something that doesn't have anything to do with Barba but CSS. But wanted to ask in case this is a known thing that someone encountered before since it's driving me crazy :-)

Thanks a lot!

Here's my CSS code (I'm using the CSS plugin):

```
.slide-leave,
.slide-enter-to {
    transform: translateY(0);
    -webkit-transform: translateY(0);
    opacity: 1;

}

.slide-leave-active,
.slide-enter-active {
    transition: all .8s cubic-bezier(1,0,0.47,1.01);
    -webkit-transition: all .8s cubic-bezier(1,0,0.47,1.01);
    opacity: 1;
}
.slide-leave-to {
    transform: translateY(-100vh);
    -webkit-transform: translateY(-100vh);
    opacity: 0;
}

.slide-enter {
    transform: translateY(100vh);
    -webkit-transform: translateY(100vh);
    opacity: 1;

}
.slide-enter-to {
    position: fixed;
    top: 0;
    left: 0;
    z-index: 99999;
    opacity: 1;
    min-height: 100vh;
}
```

**Comment by xavierfoucrier** [comment]
Hello @anta199,

Can you share a minimal reproductible test repository in order to investigate?
Thanks!

**Comment by anta199** [comment]
@xavierfoucrier Thanks for that.
I don't seem to be able to run Barba in the Codepen but that's essentially what I have.

https://codepen.io/anta199/project/editor/AOrrjQ

Thanks,

**Comment by xavierfoucrier** [comment]
Yes, please provide at least a minimal reproductible test repository on Github to let me check in good conditions. Thanks

**Comment by anta199** [comment]
Hello @xavierfoucrier 
Thanks for the help. I just invited you to collaborate on the repository so you can check the code.

- Barba set up can be found [here](https://github.com/anta199/transitions/blob/main/assets/js/index.js)
- Barba CSS [here](https://github.com/anta199/transitions/blob/main/assets/css/index.css)

Could the flickering be related with absolute/fixed positioned elements within the pages?

Let me know if I can provide any other helpful information
Thanks

**Comment by xavierfoucrier** [comment]
Hello @anta199,

I will have a look as soon as possible to your code.
Talk soon!

**Comment by anta199** [comment]
Hi @xavierfoucrier 
I really appreciate it! Thanks

**Comment by godalming123** [comment]
found same thing with my site: https://godalming123.github.io/ code: https://github.com/godalming123/godalming123.github.io

**Comment by godalming123** [comment]
in my site the content only seems to be animating in properly when it flickers

**Comment by godalming123** [comment]
I think the reason the content is flickering is because of the small amount of time when both elements are in the dom so if your on the home page which scrolls you go to another page the home elements opacity is set to 0 but its still rendered so when the next page comes in it appears nothings happend for abit when actually the next page is below the home page you just dont see it and then the home page gets destroyed showing the nextpage but it flashes into veiw and the reason it changes depending on wether a page is scrollable is beacues when a page isnt scrollable the page fades out and the next page fades in but you can see it underneath the first page before the next page snaps to the top becuase the first page is deleted so I would try setting display none for the afterBefore trigger so after your initial animation display is set to none and the content stays out of the way

**Comment by anta199** [comment]
Hello. As ridiculous as it sounds, in my case the issue was related with the ‘z-index’ applied to the different elements. There’s that common habit of setting extremely high values to the ‘z-index’ (like 99999) which together with the sync feature was making the elements overlap. By using less high values and being conscious of which elements leave first I fixed it!

**Comment by godalming123** [comment]
**Update:** I have done what I said in my previous comment and expeiencing new issue see [here](https://github.com/barbajs/barba/issues/645)

**Comment by xavierfoucrier** [comment]
The `z-index` issue happen a lot of time to many developers when trying to deal with page transitions.
Thanks @godalming123 for closing!
