### ISSUE TITLE
Add custom data to `barba.history`

### ISSUE THREAD

**Issue by goyavo** [barbajs/barba#630]
It seems to be not possible to **add custom data to the `barba.history`** using `pushState` as the state gets overwritten by barba.js own data. There is currently no methods provided to do that.

> browse to any page
> push some data
```js
window.history.pushState('{"random_data":1}', '', `?new_random_state`);
```
> check that data is there:
```js
history.state
"{\"random_data\":1}"
```
> click on any link
> click on previous button
> check history.state;
```js
history.state
```
we lost all data previously added and history.state just contains other barba.js data:
```js
{from: "barba", index: 0, states: Array(1)}
```

**Comment by xavierfoucrier** [comment]
Hello @goyavo,

This is the intended behavior.
Barba uses `pushState` to manage internal page history.

What's is the goal of pushing random data into the window history here? :thinking:

**Comment by goyavo** [comment]
> What's is the goal of pushing random data into the window history here? 🤔

Thanks for answering and apologies, I somehow completely missed the reply notification.

Perhaps the expression "random data" is misleading, we were thinking of specific things related to the state of the page like:
> the tab that was open on that page
> the product that was clicked when leaving the page 
etc

basically any kind of state date which could normally be pushed in window.history but which is currently being overwritten by barbajs

**Comment by xavierfoucrier** [comment]
@goyavo OK I understand what you mean :+1: 

May be at least it would be better that Barba store their own data into a "subkey" inside the state object instead of erasing the whole state. We will discuss that with Thierry in our next meeting :wink:

cc @thierrymichel

**Comment by psntr** [comment]
That would be lovely to have a way to store data in the history state. It could in the same time solve issues with the back and forward button from the browser related to issue #601 .
