### ISSUE TITLE
Using Barba with Django Framework

### ISSUE THREAD

**Issue by houzayy** [barbajs/barba#634]
**My Issue**

Barba is logging me out without any warning, and causing my view's loginrequiredmixin to fire off.

---

**Some Explanations**

After incorporating Barba js animation library into my Django Project, it started to break. 
All my views has a loginrequiredmixin to check if user is logged in. 
This means that if users are not logged in, they will be redirected automatically to the login page.
This is handled by Django byappending ```/accounts/login/?next=/``` to the address.
e.g. ``` http://127.0.0.1:8000/accounts/login/?next=/```

However, somehow, barba seems to be logging me out without warning, hence firing off my loginrequiredmixin randomly as well.

e.g. if i am in home page, and i am trying to enter my settings page, it will turn into a 404 with the address bar showing ``` http://127.0.0.1:8000/accounts/login/?next=/user/settings/2```

---

**My script.js**
```javascript
function pageTransition() {
    var tl = gsap.timeline();
    tl.to('#main-wrapper', { duration: 0.1, opacity: 1, transformOrigin: "bottom"})
}

function contentAnimation() {
    var tl = gsap.timeline();
    tl.from('#content-wrapper', {duration: 0.8, translateY: 50, opacity: 0})
    tl.from('#header-wrapper', {duration: 0.8, translateY: 50, opacity: 0}, "-=0.6")
    tl.from('#instructions-wrapper', {duration: 0.8, translateY: 50, opacity: 0}, "-=0.6")
    tl.from('#messages-wrapper', {duration: 0.8, translateY: 50, opacity: 0}, "-=0.6")
}

function delay(n) {
    n = n || 2000;
    return new Promise(done => {
        setTimeout(() => {
            done();
        }, n);
    });
}

barba.init({
    sync: false,
    transitions: [{
        leave(data) {
            const done = this.async();
            pageTransition();
            delay(100);
            done();
        },

        enter(data) {
            contentAnimation();
        },

        once(data) {
            contentAnimation();
        },
    }]


})
```

---
**My base.html**

The nav is redacted but do let me know if you'd like to see the full nav.

```html
<body data-barba="wrapper">
  <main data-barba="container" role="main" id="main-wrapper" class="container content-wrapper">
    <nav>
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" data-menu="logout" href="{% url 'logout' %}">
              Logout
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" data-menu="settings" href="{% url 'settings' request.user.userprofile.id %}">
              Settings
            </a>
          </li>
      </ul>
    </nav>
    <div id="header-wrapper" class="header d-flex justify-content-center align-items-center">
      <h1>
      {% block header %}

      {% endblock %}
      </h1>
    </div>

    <!-- Instructions -->
    <div id="instructions-wrapper">
    {% block instructions %}

    {% endblock %}
    </div>

    <!-- Messages -->
    <div id="messages-wrapper">
      {% for message in messages %}
      <div class="alert alert-{{message.level_tag }} mt-3 mb-3">
        <a class="close mx-auto my-auto" href="#" data-dismiss="alert">×</a>
        {{ message }}
      </div>
      {% endfor %}
    </div>
    
    <!-- Content -->
    <div id="content-wrapper">
    {% block content %}
    {% if user.is_authenticated %}

    {% else %}
    
    {% include "relogin.html" %}
    
    {% endif %}
    {% endblock %}
    </div>
  </main>

</body>
```

---
When I am clicking slowly, everything works perfectly; links are loading, animations are firing pages are transiting to the next href and the address bar reflects the href accurately.

However, when I am clicking very quickly, I am suddenly logged out.

---
**An Example**

When I am at home page after logging in, the address bar is: 
```
http://127.0.0.1:8000
```
When I start to randomly click the links in quick succession, it could be any page, but one example of the address bar will be:
```
http://127.0.0.1:8000/accounts/login/?next=/user/settings/2
```

---

**Error Logs**

I managed to capture an error in web dev tools console.
When I hover over a problematic link:
The web dev tools is pointing to 'o.send()', saying that it is failing to load the resource with an error code 404

**Barba core**
```javascript
function I(t, n, r) {
        return void 0 === n && (n = 2e3),
        new Promise((function(e, i) {
            var o = new XMLHttpRequest;
            o.onreadystatechange = function() {
                if (o.readyState === XMLHttpRequest.DONE)
                    if (200 === o.status)
                        e(o.responseText);
                    else if (o.status) {
                        var n = {
                            status: o.status,
                            statusText: o.statusText
                        };
                        r(t, n),
                        i(n)
                    }
            }
            ,
            o.ontimeout = function() {
                var e = new Error("Timeout error [" + n + "]");
                r(t, e),
                i(e)
            }
            ,
            o.onerror = function() {
                var n = new Error("Fetch error");
                r(t, n),
                i(n)
            }
            ,
            o.open("GET", t),
            o.timeout = n,
            o.setRequestHeader("Accept", "text/html,application/xhtml+xml,application/xml"),
            o.setRequestHeader("x-barba", "yes"),
            o.send()
        }
        ))
    }
```

**Console**
```
GET http://127.0.0.1:8000/accounts/login/?next=/user/settings/2 404 (Not Found)
(anonymous) @ core:formatted:682
I @ core:formatted:650
e.B @ core:formatted:1648

```

**Relevant Issues**
I found this link: ```https://stackoverflow.com/questions/6227197/django-login-attempts-sometimes-silently-fail```

It details that the django is blowing the connections limit to the posgres server but not sure if it helps..

**Comment by xavierfoucrier** [comment]
Hi @houzayy,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

In addition, you should **open an issue or ask the Django community for help**.
Unfortunately, we are not able to cover all use case or all frameworks, and sometimes, there are incompatibilities.
