### ISSUE TITLE
[SOLVED] Remove '.html' or '.php' in page URL

### ISSUE THREAD

**Issue by rcoussy-16h33** [barbajs/barba#637]
Hi, I'm working on a website with PHP with Barba v2 and I can't figure out how to get rid of the '.php' at the end of my URL.

I tried to redirect all of my URL in .htaccess like this:

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)\.php$ /$1 [L,R=301] 
```

But then two things happen:
- When I hover a link to another page that is impacted by the redirection stated above I get an error 406 in JS from barba core.
- When I click those same links, the page load to it without Ajax nor transition.

You can reproduce this issue with the legacy example: https://barba.js.org/docs/getstarted/legacy/

**Comment by rcoussy-16h33** [comment]
Anyways I find out what the problem was, I needed to add `Options -MultiViews` in my .htaccess :
```
Options -MultiViews
RewriteEngine on

RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME}\.php -f
RewriteRule ^(.*)$ $1.php
```

**Comment by xavierfoucrier** [comment]
Hi @rcoussy-16h33,

Not a Barba issue: as you noticed, it's related to your server-side rendering engine :wink:
