### ISSUE TITLE
Conflict with mmenu-light plugin

### ISSUE THREAD

**Issue by limedon** [barbajs/barba#643]
Trying to use [mmenu-light.js](https://github.com/FrDH/mmenu-light) for a offcanvas  menu with barba.js in a recent project, but all links inside the mmenu-light instance work as normal links without any transition effect.
------------------
Here is the example in [codepen](https://codepen.io/limedon/project/editor/ZrJOwe) and main js code as below.
----------------
```javascript
function menuInt(doc = document){
   let menu = new MmenuLight(doc.querySelector( '#menu' ),'all');
   let navigator = menu.navigation();
   let drawer = menu.offcanvas();
   doc.querySelector( 'a[href="#menu"]' ).addEventListener( 'click', evnt => {
	evnt.preventDefault();
	drawer.open();
   });
}

document.addEventListener("DOMContentLoaded", () => {
   menuInt();
   barba.init({
        transitions: [{
          name: 'opacity-transition',
          leave(data) {
            return gsap.to(data.current.container, {
              opacity: 0
            });
          },
          enter(data) {
            return gsap.from(data.next.container, {
              opacity: 0
            });
          }
        }]
      });
 barba.hooks.beforeEnter(data => {			  
	menuInt(data.next.container);
   });
 });
```

**Comment by xavierfoucrier** [comment]
Hi @limedon,

Does it work without `mmenu` component? (I mean, Barba transitions)
If yes, this is more related to the plugin from my point of view.

In addition, why having your menu inside the Barba container?
It would be better to have it outside, because most time menu are not updated between pages, this way you won't need to init it again the `beforeEnter` hook.

Please let me know, thanks!

**Comment by limedon** [comment]
Thanks for your reply @xavierfoucrier,
1. Yes, it works fine without `mmenu`, and I have found the issue is caused by `stopImmediatePropagation` method being attached to the click event.
2. Yes, your are right. I will try to put the menu outside and deal with the active classes😆

**Comment by xavierfoucrier** [comment]
@limedon fine, something I was thinking about too...
Let me know about the final result and feel free to close the issue when it's looks fine to you :wink:

**Comment by limedon** [comment]
@xavierfoucrier yes, it works as expected after changing the `stopImmediatePropagation` to `preventDefault` in `sliding panel navigation` part. 
The example code below is dealing with the opened panel after click event and also the active classes, hope this would help for someone facing the same issue.
```javascript
function menuInt(){
   let menu = new MmenuLight(document.querySelector( '#menu' ),'all');
   let navigator = menu.navigation();
   let drawer = menu.offcanvas();
   document.querySelector( 'a[href="#menu"]' ).addEventListener( 'click', evnt => {
	  evnt.preventDefault();
	  drawer.open();
   });
  menuInt.prototype.close = function() {
    return drawer.close();
  };
}
document.addEventListener("DOMContentLoaded", () => {
   let menu =  new menuInt();
   barba.init({
        transitions: [{
          name: 'opacity-transition',
          leave(data) {  
            return gsap.to(data.current.container, {
              opacity: 0
            });
          },
          enter(data) {
            return gsap.from(data.next.container, {
              opacity: 0
            });
          }
        }]
      });
 barba.hooks.leave(data => {
    menu.close();
 });
  barba.hooks.afterEnter(data => {
     let parser = new DOMParser();
     let content = parser.parseFromString(data.next.html, "text/html");
     let navs = content.querySelectorAll('#menu ul li');
     document.querySelectorAll('#menu ul li').forEach(function(el, index) {
        let classes = navs[index].classList.value;
        el.setAttribute('class', classes);
     });
   }); 
 });
```

**Comment by xavierfoucrier** [comment]
Thanks @limedon for the feedback :wink: 
Happy coding with Barba! :tada:
