### ISSUE TITLE
`@barba/preset` release date?

### ISSUE THREAD

**Issue by zipelkopf** [barbajs/barba#644]
Hi, 
I have jsut starte dusing barbajs and I wonder when you expect to release the `barba/preset` plugin.
It would be great in my case as I need only basic transitions.
Thanks!

**Comment by xavierfoucrier** [comment]
Hi @zipelkopf,

Yeah it's a good question :smile: 
As of today, there is no release date defined.

We will discuss that with Thierry in our next meeting in october.
Thanks for using Barba!
