### ISSUE TITLE
content animation in wrong direction

### ISSUE THREAD

**Issue by godalming123** [barbajs/barba#645]
## The problem

My page-transistion animation works fine the first time but fails when you subsequently trigger it by navagiting to another page see https://godalming123.github.io/ for example. Code: https://github.com/godalming123/godalming123.github.io the animation is in /asstes/js/animations.js which is imported with defer keyword in head when site loads. 

### Details

he problem with the animation subsequent times is The animation is played is the content currently on screen plays the animation for content entering onto the screen when it should be playing the animation for content leaving the screen this could be becaues the data.next.container is applying to both the old content and the new content and the data.current.container does not apply to any content.

### Expected behaviour

I am expecting the subsequent animations after the first to be the same as the first new page animation.

### Actual behaviour

The subsequent animations play the content entering animation even if the content is leaving.

### Code To Reproduce Issue
Just see https://codepen.io/godalming123/project/editor/AeVkKv for minimal reproducable code sample but for full code see: remember it works as expected the first time but files when you continue to try
```js
class animation {
    //takes one property animationProps
    //this is just a mapping of gsap props eg:
    //{opacity: 0, x: 100}
    //this has to functions leave and enter they both take a variable animation item and return
    //gsap.to/from(anamationItem, this.animationProps) where animations props is the propertys you specify for animation
    constructor(animationProps) {
        this.animationProps = animationProps;
    }

    enter(animationItem) {
        return gsap.from(animationItem, this.animationProps);
    }

    leave(animationItem) {
        return gsap.to  (animationItem, this.animationProps);
    }
}

//change page animation
const pageItemsAnimation = new animation({
    opacity: 0,
    y: 100,
    duration: 0.4,
    //stagger: 0.2
})

const hide = new animation({//hide an element so it is'nt even rendered in the veiwport
    display: "none",
    duration: 0.001,
})

//page first loads animations
const sidebarAnimation = new animation({
  opacity: 0,
  x: -100,
  duration: 0.4,
})

const pageItemsFirstLoadAnimation = new animation({
    opacity: 0,
    x: 100,
    duration: 0.4,
})

function pageFirstLoad() {
    sidebarAnimation.enter("header");
    pageItemsFirstLoadAnimation.enter(".wrapper > section")
    console.info("first load")
}

barba.init({
  transitions: [
    {
      leave: (data) => pageItemsAnimation.leave(data.current.container),
      afterLeave: (data) => hide.leave(data.current.container),
      enter: (data) => pageItemsAnimation.enter(data.next.container),
    },
    {
      to: {namespace}
      ounce: ({next}) => pageFirstLoad(),
    }
]
});
```

code source:
- https://github.com/godalming123/godalming123.github.io
demo (this is just the project that I am experiencing issue on):
- https://godalming123.github.io/

## Environment

- Build Used: Barba version that exhibits the issue: I am using the latest barba version imported through cdnjs
- Browser OS/version used: this issue applies to chrome and firefox I am also using linux for os as i've tested

**Comment by xavierfoucrier** [comment]
Hi @godalming123,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.

> I think the error here is that you don't properly `return` the animation promise to Barba, so instead of `leave: (data) => pageItemsAnimation.leave(...)`, just use `leave: (data) => return pageItemsAnimation.leave(...)`, and it should work.

**Comment by godalming123** [comment]
Thats wrong. When you say:
```
const pageAnimation = {
    opacity: 0,
    y: 100,
    duration: 0.4,
}

const hideAnimation = {//hide an element so it is'nt even rendered in the veiwport
    display: "none",
    duration: 0.001,
}

barba.init({
  transitions: [
    {
      leave: (data) => gsap.to (data.current.container, pageAnimation),
      afterLeave: (data) => gsap.to (data.current.container, hideAnimation),
      enter: (data) => gsap.from (data.next.container, pageAnimation),
    },
]
});
```
Arrow functions support ditching `{}` and when you do this it is equivalent to with these except the statement in your function is returned. You can see this if you convert the above example into a es5 (arrow functions are es6) use [this](https://es6console.com/). Ounce converted it returns a normal function with a normal `return` statement. In fact it actually throws an error when you use your code snippet and use the return statement without the curly braces wether that be transformed an a compiler or ran in firefox. I believe this issue should be reopened. ... Oh and even if you do use a normal function as per the es5 compiled code it still doesnt work.

**Comment by xavierfoucrier** [comment]
Hi @godalming123,

Sorry, this was a bad copy/paste on my side. Of course arrow function return single statement.

But the main problem here remains inside `this.animationProps`, which doesn't provide the appropriate value at the time you run `gsap.to` or `gsap.from`. Replacing `this.animationProps` with `{ opacity: 1 }` works fine.

Next time, please **use the Slack workspace** in order to ask the whole community for support.

**Comment by godalming123** [comment]
issue fixed
