### ISSUE TITLE
Priority problem with two different transitions

### ISSUE THREAD

**Issue by FlorianW7** [barbajs/barba#647]
Hi! As the title states, I think I've got an issue concerning the priority order for two different transitions.

So basically I want the "default-transition" to play everytime I'm changing pages, but I want "no-transition" to play when I'm clicking links with the "main-menu-link" class, hence the "custom" condition. 

My problem is that I get no transition whatsoever. It seems that the "custom" condition gets fired all the time. Only If I completely comment out the "no-transition" part of my code I get the transition to work. Weird thing is, that this code actually worked yesterday and I don't think I made changes elsewhere, so any help is greatly appreciated!

```
barba.init({
            debug: false,
            timeout: 5000,
            transitions: [{
		name: 'default-transition',
		async leave() {
			await loaderIn();
		},
		enter() {
			loaderAway();
			overflowVisible();
			window.scrollTo(0, 0);
		},
		name: 'no-transition',
		from: {
			custom: ({ trigger }) => {
				return trigger.classList && trigger.classList.contains('main-menu-link');
			},
		},
		leave() {},
                enter() {
                    overflowVisible();
               }		  
          }]
});
```

**Comment by xavierfoucrier** [comment]
Hi @FlorianW7,

This is just a **syntax error**: the `transitions` property require an `Array` or `transition`.

So you should just use something like:

```js
barba.init({
  debug: false,
  timeout: 5000,
  transitions: [
    {
      name: 'default-transition',
      async leave() {
        await loaderIn();
      },
      enter() {
        loaderAway();
        overflowVisible();
        window.scrollTo(0, 0);
      },
    }, {
      name: 'no-transition',
      from: {
        custom: ({ trigger }) => {
          return trigger.classList && trigger.classList.contains('main-menu-link');
        },
      },
      leave() {},
      enter() {
        overflowVisible();
      }
    }
  ]
});
```

Closing the issue :wink:

**Comment by FlorianW7** [comment]
Oh man, must've looked at it for too long, to completely oversee the obvious 😅

Thanks anyway, I'm glad I got it working now.

**Comment by xavierfoucrier** [comment]
@FlorianW7 No problem! You are not the only one in that case 😉. Happy coding with Barba ✌☀
