### ISSUE TITLE
DOMParser is not defined in Nextjs

### ISSUE THREAD

**Issue by BekaArabidze** [barbajs/barba#650]
Hello. I cant run barbajs in next js and shows me this error. Can you help me? How can I solve this?

![Screenshot_1](https://user-images.githubusercontent.com/36812744/135847285-f129b8a6-6bbf-4754-8fa9-8c96974a5049.png)

**Comment by MihaelN** [comment]
> Hi @BekaArabidze,
> 
> It's a duplicate of #512, Github have already tell you I guess. The bug is already fixed and will be implemented in the next release, thanks for your patience.
> 
> Closing this issue.
> 
> > See [896b44b](https://github.com/barbajs/barba/commit/896b44b33cc35b00e2f720f9edb982e3a985ca44).

When is the next release?
