### ISSUE TITLE
NPM archive crashed?

### ISSUE THREAD

**Issue by fredy31** [barbajs/barba#652]
The NPM archive is not responding, making Barba.js Impossible to add to a npm install.

![Screen Shot 2021-10-07 at 1 32 52 PM](https://user-images.githubusercontent.com/2183470/136434836-0d13bd0f-3155-4d7a-ad9f-296116e61856.png)

**Comment by xavierfoucrier** [comment]
Hi @fredy31,

Well, as you probably guess, **this is something we don't manage and don't have control on**.
NPM registry live status is available here: https://status.npmjs.org/.

As a fallback solution, you can use - temporarily - an alternative bundle like on Unpkg, JsDelivr, etc.

> :warning: Please, do not open issues that are non-related to BarbaJS here.
>
> This is **wasted time** for managers - like me - to explain, answer and close issues like this.
> Thanks!

**Comment by fredy31** [comment]
I wanted to but the link to the slack on the barba website is expired.
