### ISSUE TITLE
Question: Barba animation

### ISSUE THREAD

**Issue by stzach** [barbajs/barba#657]
Hello all,

I am working on a sample to check barbajs features and how that works. What i have on my mind is to create transition between pages using a layout like that:

<body data-barba="wrapper">
    <div id="bg-barba"></div>
    <div id="content" data-barba="container">
      <header>MY HEADER</header>
      <div id="main"></div>
      <footer>MY FOOTER</footer>
    </div>
</body>

On #main div each page will have as background an svg geometrical shape, maybe a little different on each page or maybe some pages have no such svg background. 

What i want that shape on leave() get scaled and fill the whole page as cover and on enter() of the next page get scaled to fit the next svg background. This is why i have created an #bg-barba to scale it and also use it if my page has no background.

Can you please help me with the transiitions? I don't know if there is another way not to use #bg-barba and change the svg background position so to scale it? Should i go with the views approach?

Also what options do we have when first page load?? I want on first time to also have by default a full cover, that will also get shrink to the pages background.

barba.init({
  debug: true,
  transitions: [
    {
      sync: true,
      name: "default-transition",
      leave() {
        gsap.to("#bg-barba", { duration: 2, scaleX: 1, scaleY: 1 });
      },
      enter() {
        gsap.to("#bg-barba", { duration: 2, scaleX: 0, scaleY: 0 });
      }
    }
  ]
});

**Comment by xavierfoucrier** [comment]
Hi @stzach,

This issue is more related to **how your code is running** than Barba v2 issue...

For those kind of questions/help, please **use the Slack workspace** in order to ask the whole community for support. Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.
