### ISSUE TITLE
How to load the page automatically after a timeout ?

### ISSUE THREAD

**Issue by laleikeCO** [barbajs/barba#658]
Is there a way to start the transition / page load automatically after a period of time?

Using window.location let load the page but it seams that barba isn't initiated at this point.

**Comment by xavierfoucrier** [comment]
Hi @laleikeCO,

Yes it's possible: you need to use `barba.go(url);` to trigger a barba transition, only using `window.location` won't work in your case.

> See https://barba.js.org/docs/advanced/utils/.

**Comment by laleikeCO** [comment]
Hey Xavier,

big thans. That's exactly what i'm looking for. 😇

Best, Thomas
