### ISSUE TITLE
Google Analytics 4 tracking not working barba hook

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [barbajs/barba#677]
When using the latest Google Analytics 4 and Google Tag manager, the barba hook below no longer seems to track changes...
Anybody know how to track un GA 4 using BarbaJS? 

```js
// do something after the transition finishes
barba.hooks.after(() => {
    ga('set', 'page', window.location.pathname);
    ga('send', 'pageview');
});
```

**Comment by xavierfoucrier** [comment]
> See official barba docs for that: https://barba.js.org/docs/advanced/third-party/#Google-Analytics
> Note that I am currently updating it for GA4, thanks for highlighting this 😉

**Comment by theamnesic** [comment]
Hi!

The "_Google SPA guide_ link" on the [documentation](https://barba.js.org/docs/advanced/third-party/#Google-Analytics) is dead @xavierfoucrier 😕

About GTM and your guide @DESIGNfromWITHIN, what method did you choose ?
I don't understand if GTM is autonomous with _Page changes based on browser history events_ [checkbox](https://www.analyticsmania.com/wp-content/uploads/2020/05/history-events-google-analytics-4-2.jpg) enabled, or if we have to use something like this 🤔 : 

```js
window.dataLayer = window.dataLayer || [];

window.dataLayer.push({
  'event': 'Pageview',
  'page_title': (document.title) ? document.title : '',
  'page_URL': (window.location.href) ?  window.location.href : '',
  'page_path': (window.location.pathname) ? window.location.pathname : '',
});

```

**Comment by xavierfoucrier** [comment]
@theamnesic Good catch, I will update it asap. Thanks!

**Comment by xavierfoucrier** [comment]
@theamnesic looks like it's back again! And I did nothing.. 😄

**Comment by theamnesic** [comment]
> The "_Google SPA guide_ link" on the [documentation](https://barba.js.org/docs/advanced/third-party/#Google-Analytics) is dead @xavierfoucrier 😕

Oups, it's dead again!

> About GTM and your guide @DESIGNfromWITHIN, what method did you choose ? I don't understand if GTM is autonomous with _Page changes based on browser history events_ [checkbox](https://www.analyticsmania.com/wp-content/uploads/2020/05/history-events-google-analytics-4-2.jpg) enabled, or if we have to use something like this 🤔 :
> 
> ```js
> window.dataLayer = window.dataLayer || [];
> 
> window.dataLayer.push({
>   'event': 'Pageview',
>   'page_title': (document.title) ? document.title : '',
>   'page_URL': (window.location.href) ?  window.location.href : '',
>   'page_path': (window.location.pathname) ? window.location.pathname : '',
> });
> ```

I don't understand how to use GTM with Barba, it's witchcraft 🫤 
Can anyone add a working exemple for the documentation?

Thanks!

**Comment by DESIGNfromWITHIN** [comment]
Ohnestly I have changed to using SWUPJS...
https://swup.js.org/plugins/ga-plugin/

It has a plugin and does what I need for SPA like effects.

**Comment by xavierfoucrier** [comment]
Hello @theamnesic 👋 

Since it's an external link and looks to work again without touching anything on my side, you should first wait a day before it come back, or at least check the cached page on Google or another search engine. Sorry..

Clearly it's not complicated to use Analytics with BarbaJS, that's why we don't have a plugin for that. Many implementations are possible.

I will add a note to bring a "default" Analytics example and refactor the SPA guide for GA.
😉
