### ISSUE TITLE
Show next container on top of scroll

### ISSUE THREAD

**Issue by gmzbri** [barbajs/barba#678]
Hey everyone!

I am wrapping my head around how to show the next container on its top scroll position vs appear in whatever scroll position I come from the current container. I am using a slide-type transition when the next page appears from the side and the current one gets pushed by the next one (sort of slide effect in a keynote).

Does someone know how to achieve something like this? I ideally would like the next container to appear in the top (scrollTop: 0) rather than in the middle or bottom, depending on how much I scrolled before triggering the animation.

I have tried the next, but this approach scroll to top the current container also, making the effect not to be how I would like to.

```
barba.hooks.enter((data) => {

  if ('scrollRestoration' in history) {
    history.scrollRestoration = 'manual';
  }
  window.scrollTo(0, 0);

});
```

Thanks in advance!

**Comment by daun** [comment]
The way I've managed to do it is by making both containers fixed position and manually setting their scroll position.

- Before transition, save the body scroll position in a variable (`nextAdded` hook in sync mode)
- During the transition, set both next and current container to `position: fixed`, `height: 100%` and `overflow-y: scroll`
- Set the current container's `scrollTop` to the previous body scroll position
- After the transition, reset both containers to static positioning

I don't have an isolated example ready to share, but that's the gist of it.

**Comment by xavierfoucrier** [comment]
To well understand, there is:
- `history.scrollRestoration` that allow you to prevent the browser from restoring the scroll position when you go backward/forward to a specific page, and you only need to do it one time, because of SPA
- container position: based on life cycle, two Barba containers can live together in the `DOM` at the same time, meaning that you need to be aware of this

> What @daun suggests should work in your case.
