### ISSUE TITLE
barba.history.previous return null

### ISSUE THREAD

**Issue by Romain-BASE-GVA** [barbajs/barba#680]
I'm trying to create a back button by getting the previous page url, but barba.history.previous return null even if I was on another page previously.

Just trying to make a back button on a 404 page. Why is it returning null tho it should return the previous page object as explained in the documentation.

Any example welcome!

Thank you.

**Comment by xavierfoucrier** [comment]
This is the intended behavior when using `backward` and `forward` buttons.
It works like a stack where you pop's objects out one by one.

If you start on page `A`, then go to page `B`, `barba.history.previous` is equal to `A` object - containing `ns`, `scroll` and `url` options - but if you go back to page `A` using backward button, the library need to pop object from the history to keep it clean regarding browser navigation, then `barba.history.previous` will be `null`.

> Note that this won't be the case if you click on a link present on page `B` that point to page `A`.
> You can also use a dedicated variable where you store `barba.history.previous` object if it is not `null`.

Be aware of checking the object before accessing it :wink:
