### ISSUE TITLE
Are global `once` hooks available?

### ISSUE THREAD

**Issue by stefanobartoletti** [barbajs/barba#687]
Like the title says, are `beforeOnce`, `once`, and `afterOnce` global hooks available?

**Comment by stefanobartoletti** [comment]
I think that I managed to solve this, without actually doing nothing special.

The `barba.hooks.afterEnter` and `barba.hooks.beforeEnter` are fired also at `once`, so there is no need for separate global hooks.

**Comment by xavierfoucrier** [comment]
Hello @stefanobartoletti,

Sorry for the late reply, but it's a **yes!** 😄

> Note that the `beforeEnter` and `afterEnter` are called at once stage, while `beforeOnce` and `afterOnce` are only called once, so there is a need to have both.
