### ISSUE TITLE
Issue with loading css style inside html tag

### ISSUE THREAD

**Issue by federicovisioli** [barbajs/barba#689]
I'm having an issue with a third party library.
This library loads different css styles to an html element, adding `style="...."` to html tag. (like `<div style="color: red">...</div>`).
The problem here is that, during page transition between different page, the inline style doesn't load, but when i reload the page, it shows up correctly.
The js file of that third party plugin loads correctly on all pages, but i think it dynamically change the style on page loads.
Is there a way i can solve this issue? Maybe with beforeEnter?
I'm still in the learning phase, I'm sorry if there is a simple solution.
Thanks!

**Comment by xavierfoucrier** [comment]
Hello @federicovisioli,

Of course, when transitioning, your previous container is replaced and your inline styles disappears. So basically you need to use `hooks` to properly call your third library again, like `library.update()` where `update()` add inline styles regarding the current page.

> See https://barba.js.org/docs/advanced/hooks/.
