### ISSUE TITLE
Can't go to other pages.

### ISSUE THREAD

**Issue by panmikolajczyk** [barbajs/barba#690]
Hi, I have a problem with pages that don't use barba.js.

I want to use barba only for the transition between one category page and its children.

> domain.name/category → domain.name/category/child

or

> domain.name/category/child → domain.name/category

Up to this point, everything works perfectly fine. However, when I try to go back to the home page, for example, a strange thing happens:
The URL changes to the target address, but the page only refreshes and the address of the subpage comes back.

The other pages do not have the data-attribute: [data-barba] because it blocks the rest of the JS scripts.

Any ideas on how to fix it?

**Comment by xavierfoucrier** [comment]
Hi @panmikolajczyk,

Sorry for the late reply.

You **need** to have `data-barba="wrapper"` and `data-barba="container"` on all your pages to properly remove the previous container and add the current one to the DOM. Markup section explains that: https://barba.js.org/docs/getstarted/markup/. If Barba is not able to find the next container, then the transition will fail. If you only want a transition to run `to` / `from` a specified child category, I suggest that you take a look at transition rules here: https://barba.js.org/docs/advanced/transitions/#Rules.

> In addition, be sure to enable the Barba `debug` mode when debugging: it helps catch transitions errors that are not "human visible" when the mode is disabled.
