### ISSUE TITLE
CSS Import in views

### ISSUE THREAD

**Issue by tractanz** [barbajs/barba#691]
Hi there,

This isn't a bug report, just a question on whether or not it's possible or could be possible. When using views, is/could it be possible to static import css files in specific views? 

Cheers!

**Comment by xavierfoucrier** [comment]
Hi @tractanz,

Short answer is **yes** 😄 
The best place to run custom code per namespace is `Views`.

> Read more inside the docs here: https://barba.js.org/docs/getstarted/custom-code/.
