### ISSUE TITLE
Keep current container instead of removing

### ISSUE THREAD

**Issue by elenaramirez** [barbajs/barba#696]
Hello there! 

I'm having some troubles to avoiding current container being removed after transitions. I would like to keep the previous content on the back for homepage, but i can't find info about how to get this done. 

Is it possible? Is there any config parameter to avoid current container being removed automatically?

Thank you all!

**Comment by xavierfoucrier** [comment]
Hi @elenaramirez 👋 

Unfortunately, this is not an option: the `previous` container is removed automatically by Barba just before the `after` hook, or at least removed programatically by yourself using `current.container.remove()` method during life cycle.

If you want to keep the previous container, you may need to "save it", and then insert it again in the DOM the way you want.
Currently there is no plan to keep it alive after a transition is done.

I am closing the issue.
