### ISSUE TITLE
Slack invitation link is not longer working

### ISSUE THREAD

**Issue by dzienisz** [barbajs/barba#697]
## The problem

Slack invitation link is not longer working

### Details

<img width="504" alt="Zrzut ekranu 2023-01-22 o 21 17 56" src="https://user-images.githubusercontent.com/3521624/213938346-d259bd38-3ecb-405f-9c3b-83a00a252c4c.png">

**Comment by xavierfoucrier** [comment]
Hi @dzienisz 👋 

Yup, I can confirm this is a bug 🐛 
I will care of updating the link as soon as possible.

Thanks!
