### ISSUE TITLE
Add `dark` mode support

### ISSUE THREAD

**Issue by xavierfoucrier** [barbajs/barba#701]
Enhance documentation website by implementing a **dark scheme** to improve developer experience when reading at night.

**Comment by pinak3748** [comment]
Hey xavierfoucrier,

can I implement the dark mode, I have some approach in my mind but don't have any idea where to start on them.

We can add theme classes directly in the body tag and can swap them on toggle button using the eventListner on it

eg: <body class="dark-theme || light-theme">

body {
  --text-color: #222;
  --bkg-color: #fff;
}

body.dark-theme {
  --text-color: #eee;
  --bkg-color: #121212;
}


@media (prefers-color-scheme: dark) {
  body { 
    --text-color: #eee;
    --bkg-color: #121212;
  }

  body.light-theme {
    --text-color: #222;
    --bkg-color: #fff;
  }
}

btn.addEventListener("click", function() {
  if (prefersDarkScheme.matches) {
    document.body.classList.toggle("light-theme");
  } else {
    document.body.classList.toggle("dark-theme");
  }
});

**Comment by xavierfoucrier** [comment]
Hello @pinak3748 👋 

Thanks for your proposal.

I haven't planned to build a switch button, because it was not planned in the design part, so only a dark mode based on the browser preferred scheme to begin.

If you have time and want to dive into this issue, create a pull request that target the `website-2.x` branch.
Currently I can't pass time to explain how the website setup is working, so if you don't know where to start and how to start, don't waste your time.

I have planned to work on this issue after #703 😉

**Comment by xavierfoucrier** [comment]
Working on it 🕶️ 🏴 🖤 ⚫

**Comment by xavierfoucrier** [comment]
![image](https://github.com/barbajs/barba/assets/2471223/ad28d9c0-a08d-41f3-8f56-972b027ade27)

> It's starting to look very nice 🖤
