### ISSUE TITLE
Barba.JS not work with GSAP Line Animation

### ISSUE THREAD

**Issue by SupportJason** [barbajs/barba#712]
Hi everyone, I got stuck on this main issue of my project. It work well when homepage appear, the Gsap line animation work correctly. But when I navigate to other page, it not working at all. It is I put the wrong code on beforeEnter() ? Could someone look at this code and correct me if I was wrong, Thanks everyone so much.

`function resetWebflow(data) {
  let parser = new DOMParser();
  let dom = parser.parseFromString(data.next.html, "text/html");
  let webflowPageId = $(dom).find("html").attr("data-wf-page");
  $("html").attr("data-wf-page", webflowPageId);
  window.Webflow && window.Webflow.destroy();
  window.Webflow && window.Webflow.ready();
  window.Webflow && window.Webflow.require("ix2").init();
  document.dispatchEvent(new Event("readystatechange"));
  if (typeof Webflow !== "undefined") {
    Webflow.destroy();
    Webflow.ready();
    Webflow.require("ix2").init();
  }
}

barba.init({
  preventRunning: true,
  transitions: [
    {
      sync: true,
      from: {
        namespace: ["home"]
      },
      leave(data) {
        return gsap.fromTo(
          data.current.container,
          { opacity: 1 },
          {
            opacity: 0,
            duration: 0.5,
            onComplete: () => {
              $(window).scrollTop(0);
              $(data.next.container).removeClass("fixed");
            }
          }
        );
      },
      enter(data) {
        let transitionData = data;
        $(data.next.container).addClass("fixed");
        Webflow.require("ix2").init();
        return gsap.fromTo(
          data.next.container,
          { opacity: 0 },
          {
            opacity: 1,
            duration: 0.5,
            onComplete: () => {
              $(window).scrollTop(0);
              $(data.next.container).removeClass("fixed");
              resetWebflow(transitionData);
            }
          }
        );
      }
    },
    {
      sync: true,
      from: {
        namespace: ["philosophy"]
      },
      leave(data) {
        return gsap.fromTo(
          data.current.container,
          { opacity: 1 },
          {
            opacity: 0,
            duration: 0.5,
            onComplete: () => {
              $(window).scrollTop(0);
              $(data.next.container).removeClass("fixed");
            }
          }
        );
      },
      enter(data) {
        let transitionData = data;
        $(data.next.container).addClass("fixed");
        Webflow.require("ix2").init();
        return gsap.fromTo(
          data.next.container,
          { opacity: 0 },
          {
            opacity: 1,
            duration: 0.5,
            onComplete: () => {
              $(window).scrollTop(0);
              $(data.next.container).removeClass("fixed");
              resetWebflow(transitionData);
            }
          }
        );
      }
    },
    {
      sync: true,
      from: {
        namespace: ["team"]
      },
      leave(data) {
        return gsap.fromTo(
          data.current.container,
          { opacity: 1 },
          {
            opacity: 0,
            duration: 0.5,
            onComplete: () => {
              $(window).scrollTop(0);
              $(data.next.container).removeClass("fixed");
            }
          }
        );
      },
      enter(data) {
        let transitionData = data;
        $(data.next.container).addClass("fixed");
        Webflow.require("ix2").init();
        return gsap.fromTo(
          data.next.container,
          { opacity: 0 },
          {
            opacity: 1,
            duration: 0.5,
            onComplete: () => {
              $(window).scrollTop(0);
              $(data.next.container).removeClass("fixed");
              resetWebflow(transitionData);
            }
          }
        );
      }
    },
    {
      sync: true,
      from: {
        namespace: ["portfolio"]
      },
      leave(data) {
        return gsap.fromTo(
          data.current.container,
          { opacity: 1 },
          {
            opacity: 0,
            duration: 0.5,
            onComplete: () => {
              $(window).scrollTop(0);
              $(data.next.container).removeClass("fixed");
            }
          }
        );
      },
      enter(data) {
        let transitionData = data;
        $(data.next.container).addClass("fixed");
        Webflow.require("ix2").init();
        return gsap.fromTo(
          data.next.container,
          { opacity: 0 },
          {
            opacity: 1,
            duration: 0.5,
            onComplete: () => {
              $(window).scrollTop(0);
              $(data.next.container).removeClass("fixed");
              resetWebflow(transitionData);
            }
          }
        );
      }
    }
  ],
  views: [
    {
      namespace: "portfolio",
      beforeEnter() {
        window.fsAttributes.cmsfilter.init();
        addAnimation();
        splitText();
      }
    },
    {
      namespace: "home",
      beforeEnter() {
        addAnimation();
        splitText();
      }
    },
    {
      namespace: "team",
      beforeEnter() {
        addAnimation();
        splitText();
        btn1();
        btn2();
        btn3();
      }
    },
    {
      namespace: "philosophy",
      beforeEnter() {
        addAnimation();
        playSlider();
        splitText();
      }
    }
  ]
});
*/
`

**Comment by xavierfoucrier** [comment]
Hi @SupportJason,

This issue is more related to **how your code is running** than Barba v2 issue...

For this kind of question/help, please **use the Slack workspace** in order to ask the whole community for support.
Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.
