### ISSUE TITLE
Improve documentation for WordPress

### ISSUE THREAD

**Issue by 1ucay** [barbajs/barba#717]
I would like to share code for adding classes to body element
For WordPress site it can be important.

    beforeEnter: function(data) {

		var classes = data.next.html.match(/<body.+?class="([^""]*)"/i)[1];
		document.body.setAttribute('class', '');
		if ( classes !== '' ) {
			classes.split(" ").map(function(item) {
				document.body.classList.add(item);
			});
		}

**Comment by xavierfoucrier** [comment]
Hello @1ucay 👋 

Thanks for pointing this, as many users requested on Slack to improve documentation about that, let's do it!
I will take the time to add a dedicated section on the BarbaJS website.

🏄

**Comment by xavierfoucrier** [comment]
Hello @1ucay 👋 

I just added a **dedicated section inside the documention**, right here:
https://barba.js.org/docs/advanced/third-party/#WordPress

I also shorten your code to make it more consistent and readable:

```js
beforeEnter: ({ next }) => {
  const matches = next.html.match(/<body.+?class="([^""]*)"/i);
  document.body.setAttribute('class', (matches && matches.at(1)) ?? '');
}
```

😉
