### ISSUE TITLE
Safari flash the leaving container

### ISSUE THREAD

**Issue by FettahAud** [barbajs/barba#723]
I've made this page transition

https://github.com/barbajs/barba/assets/74654437/4dccbed1-5d03-45ea-8c41-e0e944cd4f55

Which works fine on almost all devices, except on iphone browsers, this is how its flash

https://github.com/barbajs/barba/assets/74654437/55b383bf-711b-43a8-a14d-0f3e0626c1c9

You can test it from here as  well https://stil-3cbdd1.webflow.io/rooms/room-one

I've tried some solutions like 

```
const tl = gsap.timeline({
   onComplete: () => {
      current.container.style.display = "none";
      // and 
      current.container.remove() 
      // and
      current.container.style.opacity = 0;      
   }
});
```

**Comment by FettahAud** [comment]
Quick update, we found out that the reason isn't the iphone itself, but the high refresh rate does.
So regardless the phone is Iphone or Android, this issue happens in devices with high refresh rate

**Comment by xavierfoucrier** [comment]
Hello @FettahAud 👋,

Interesting case..

⚠️ First of all, **don't duplicate issue**: post your message only here if you think it could be related to a Barba bug, or only on the Slack workspace if you think you need more help from the community to implement a feature / have questions.

I am pretty sure it's related to the way you are managing the Barba `current` container.
Please provide a minimal test repository in order for me to investigate further on this.

In addition, let me know what refresh rate is causing the issue on your side.
Thanks!

**Comment by FettahAud** [comment]
Well, quick update. We figured out what is the reason of this flashing; it was a background white applied on .section_sticky-footer, and by removing it the problem was fixed.
However we still don't know why a background color cause a flash on high refresh rate devices. 
So I'll keep it to you, if you want to close this issue or keep looking what is the reason of that

**Comment by xavierfoucrier** [comment]
Hi @FettahAud,

Happy to know that it's fixed.
I will keep this opened in order to quickly check your repo and give a feedback.

**Comment by xavierfoucrier** [comment]
Hello @FettahAud 👋 

Giving my feedback after a long time, sorry 😄

I also figured out it was a background color that causes the issue.
However, I am unable to give you a clear answer on the cause.

This could be a browser / refresh rate issue.
Anyway, if you have found a workaround, that's great!
