### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by adaniello** [barbajs/barba#729]
Hi.
While waiting for new stable version with last enhancements (eg. 301 redirects support), i'm trying to compile current branch using microbundle but i get following error:

``
Error: .../barba-main/packages/core/src/modules/Transitions.ts(187,34): semantic error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'Error'.
  Type '{}' is missing the following properties from type 'Error': name, message
``

I'm using microbundle 0.15.1 on MacOS Sonoma 14.2.1 (23C71).

Any suggestion?

Thanks

**Comment by xavierfoucrier** [comment]
Hello @adaniello 👋 

Unfortunately, some people inside the team are really overload, sorry about that!
About the compilation, everything is fine on my side and inside the CI pipeline.

Anyway, I will take the time to **publish a new pre-release version on Github** in the next few days, stay tuned!
I will also update repository regarding contribution guide to better list stack requirements.

Closing the issue for now.
Please star the repo and subscribe to be notified about releases 😎
