### ISSUE TITLE
Disable `prefetch` on specific links

### ISSUE THREAD

**Issue by virgilejanssen** [barbajs/barba#730]
Hi,

Is it possible to disable prefetch on a specific link, in the same way "data-barba-prevent" works?
I have one page with a lot of links which users are invited to hover over (a different image is displayed on each link hover).
So a lot of pages are prefetched at the same time which often leads to a timeout error (and slows the loading of the images that appear on hover).
Would it be possible to disable prefetch for those links or on that specific page all together?

Thank you!

**Comment by xavierfoucrier** [comment]
Hello @virgilejanssen 👋 

Sorry for the late reply.

Unfortunately there is no `data-barba-prefetch="disable"` attribute, or similar, to prevent barba from prefetching a specific link.
However, you can use `prefetchIgnore` and provide a list of links that won't be prefetched by Barba. You can also disable the `prefetch` option and programmatically prefetch links you need using `barba.prefetch` method.

> See https://barba.js.org/docs/advanced/strategies/#Prefetch.

**Comment by 1ucay** [comment]
Please can you extend prefetchIgnore to function like "prevent: function(el) {)"? So in function we can return true for ignore prefetch or false to allow?
