### ISSUE TITLE
Barba w/gsap > Typescript issue

### ISSUE THREAD

**Issue by cheesyMan** [barbajs/barba#732]
## The problem
When using gsap in transitions - I'm using the example provided in barba docs - there TS issues error.

## Description
I'm new to Barba and I'm trying the basic transition described in Barba Docs
https://barba.js.org/docs/getstarted/basic-transition/

But I'm getting a TS error.

### Expected behaviour
No TS errors.

### Actual behaviour
I get this error:
`Type '(data: ITransitionData) => Tween' is not assignable to type '(data: ITransitionData) => void | Promise<any>'`

### Code To Reproduce Issue [ Good To Have ]
- import barba from '@barba/core';
- set some transition **returning** gsap Tween (as showed in the [Barba.js DOCS](https://barba.js.org/docs/getstarted/basic-transition/))

```
import barba from '@barba/core';

barba.init({
  transitions: [{
    name: 'opacity-transition',
    leave(data) {
      return gsap.to(data.current.container, {
        opacity: 0
      });
    },
    enter(data) {
      return gsap.from(data.next.container, {
        opacity: 0
      });
    }
  }]
});
```

![Snipaste_2024-04-05_18-54-05](https://github.com/barbajs/barba/assets/55018265/7049857f-8db2-4787-ba4d-ec6792b68be7)

![Snipaste_2024-04-05_18-54-29](https://github.com/barbajs/barba/assets/55018265/4ec67fa2-fa16-452a-b74d-7e4b287d1baa)

### Steps to reproduce issue [ Good To Have ]

- use Barba.js in a Typescript project
- return gsap tween in a leave() or enter() method
- get TS error, anyway the animation is working.
- if I omit the **return** keyword (leaving only `gsap.to()`/`gsap.from()`) I've got no more TS errors BUT the animation doesn't work anymore.

## Environment

- Barba version that exhibits the issue: 2.9.7

**Comment by xavierfoucrier** [comment]
Hello 👋 

Sorry for the late reply, good catch 😎 
You are right, this is because **all examples in the docs are "typescript free"**.

By the way, you should write hooks like this to prevent typescript issues:

```js
import barba from '@barba/core';

barba.init({
  transitions: [{
    name: 'opacity-transition',
    leave: (data) => {
      gsap.to(data.current.container, {
        opacity: 0
      });
    },
    enter: (data) => {
      gsap.from(data.next.container, {
        opacity: 0
      });
    }
  }]
});
```

> In addition, see all different ways of writing hooks here:
> https://barba.js.org/docs/advanced/hooks/#Base-hooks.
