### ISSUE TITLE
Back button not working as intended after clicking anywhere on the page

### ISSUE THREAD

**Issue by sanedealer** [barbajs/barba#736]
### What version are you using?

v2.10.0

### What package are you using?

@barba/core

### Describe your issue

So if you go to a new page and click on any empty space and then click on the browser back button, it stays on the same page.  You can see this issue if you go to their official page click on any nav link and then click anywhere else and hit the back button.

**Comment by plsankar** [comment]
Hey all👋,

Just experienced the issue on v2.10.0.

Downgrading to v2.9.7 works.

**Comment by xavierfoucrier** [comment]
Hello everyone 👋 

Thanks for reporting, weird issue as well but anyway an issue.
I will work on it as soon as I can 🚀 😉

**Comment by 1ucay** [comment]
Please look at this.

**Comment by xavierfoucrier** [comment]
@1ucay thanks for bumping, but please be patient, it's open source you know..

>[!NOTE]
> **For your information**
> I am working on a paid private project and currently have no funds for BarbaJS.
> If you are interested in helping me bring more time and effort in it, please sponsor me 👍 
> 
> Read https://github.com/sponsors/xavierfoucrier.

**Comment by xavierfoucrier** [comment]
Closed by https://github.com/barbajs/barba/releases/tag/%40barba%2Fcore%402.10.2 🚀

**Comment by 1ucay** [comment]
Thank you Xavier!

**Comment by 1ucay** [comment]
Sorry for trouble, but I have some issue with checkboxes, I cannot checked them. Prev version is ok.
