### ISSUE TITLE
Remove polyfill.io from documentation

### ISSUE THREAD

**Issue by tdesero** [barbajs/barba#741]
Hey,
I just stumbled across this link https://barba.js.org/docs/getstarted/browser-support/ 
As polyfill.io was just recently compromised I think it is not a good idea to use it anymore as it is obviously a security risk.

**Comment by xavierfoucrier** [comment]
Hi @tdesero 👋 

Thanks for highlighting this critical issue 🔥
I am planning to update the docs accordingly today.

😉
