### ISSUE TITLE
Improve documentation on options to barba.init

### ISSUE THREAD

**Issue by tetz2442** [barbajs/barba#745]
### What version are you using?

2.10.0

### What package are you using?

@barba/core

### Describe your issue

Trying to find what options can be passed to barba when initializing is impossible with the current docs. There aren't any examples or explanations of what they are. There should be an option right after install or markup in the menu that explains each option you can pass. Thanks!

**Comment by xavierfoucrier** [comment]
Hello @tetz2442 👋 

Thanks for opening an issue for that.

Currently we have "Developer API" documentation that list all `barba.init` arguments:
https://barba.js.org/api/classes/core_src.core.html#init.

Of course, it would be nice to have a place in the doc where all are explained as well 😉

**Comment by tetz2442** [comment]
@xavierfoucrier thanks for the link. Even just a mention of that link somewhere would help in the docs. I spent a lot of time trying to figure out what the options were that I could pass 😅

**Comment by xavierfoucrier** [comment]
I can understand 😄 ... sorry about that!
Documentation will be updated accordingly.

**Comment by xavierfoucrier** [comment]
New `options` page is here! 🚀 😎 
https://barba.js.org/docs/advanced/options/
