### ISSUE TITLE
External links, checkboxes and radio buttons are not working anymore

### ISSUE THREAD

**Issue by till-kammertoens** [barbajs/barba#746]
### What version are you using?

2.10.2

### What package are you using?

@barba/core

### Describe your issue

since 2.10.2 external links that are not handled by barba stopped working on one of my sites. nothing happens on click, right click and "open link in new tab" works of course. no error messages in console. downgrading to 2.9.7 fixes the issue, 2.10.0 also works fine.

**Comment by ilimitadostudio** [comment]
Can confirm, same for me on multiple websites. Also using @barba/core.

**Comment by ilimitadostudio** [comment]
Reverting to 2.10.0 resolves.

**Comment by thisisjamessmith** [comment]
@ilimitadostudio  Reverting to 2.10.0 gives us the back button bug... https://github.com/barbajs/barba/issues/736 - maybe the lesser of two evils...

**Comment by kylecraven** [comment]
Same issue for me, checkboxes and radio buttons not working on 2.10.2. They work on 2.10.0.

**Comment by ilimitadostudio** [comment]
@thisisjamessmith 100% the lesser of two evils for us — would rather the start project button work, than the back button. (:

**Comment by xavierfoucrier** [comment]
Thanks for opening an issue.
I will give a look at that this afternoon 👍

**Comment by xavierfoucrier** [comment]
Bug confirmed 🐛

**Comment by itsnabeel** [comment]
Hi @xavierfoucrier, is there a plan to release the fix soon? since I have packaged and send multiple website using @barba/core and they are coming back to me that their websites are broke. 

I will appreciate if this bug fix can be released soon.

BTW Thank you for this great library!

**Comment by jrvanstone** [comment]
+1 on this, I thought I was going insane

**Comment by yasserzakaria** [comment]
Handles external link clicks, The code checks if the link's hostname differs from the current one and handles it accordingly. This worked on my site, and it might help you too.

```
document.addEventListener('click', (e) => {
    const link = e.target.closest('a');

    // Ensure that a link element was clicked
    if (link && link.href && link.href.startsWith('http')) {
        const linkHostname = new URL(link.href).hostname;
        const currentHostname = window.location.hostname;

        // Check if the link points to a different subdomain
        const isExternal = linkHostname !== currentHostname;

        if (isExternal) {
            e.preventDefault();

            if (link.target === '_blank') {
                window.open(link.href, '_blank', 'noopener,noreferrer');
            } else {
                window.location.href = link.href;
            }
        }
    }
});
```

Thank you

**Comment by zizther** [comment]
I can confirm 2.10.3 solved my issue which was related to this issue.
