### ISSUE TITLE
Form submissions broken since 2.10.2

### ISSUE THREAD

**Issue by thisisjamessmith** [barbajs/barba#748]
### What version are you using?

2.10.2

### What package are you using?

@barba/core

### Describe your issue

I can't submit any forms (neither regular forms or ajax-based) since upgrading to 2.10.2. Reverting to 2.9.7 fixes. Didn't try 2.10.0 as I need the back button to work.

**Comment by xavierfoucrier** [comment]
Hello @thisisjamessmith 👋 

May be same issue as #746 🤔 

Is it possible to give a minimal reproductible repo for that?
Or simply wait for the next patched version to be released in order to check 😉

**Comment by xavierfoucrier** [comment]
Duplicate of https://github.com/barbajs/barba/issues/746.
Closing the issue.

**Comment by thisisjamessmith** [comment]
Sorry for the delay, and thanks for the fix, confirmed ok with the new version.
