### ISSUE TITLE
How to disable Barba transition for some routes.

### ISSUE THREAD

**Issue by romain-granai** [barbajs/barba#752]
Hi, I'm using barba js on a Woocommerce website and the least I can say, it's a total nightmare.

The fact that it's unclear what scripts are loaded or triggered on the Woocommerce side, makes me think that the best solution is to disable Barba transition for all Woocommerce pages that have the namespace account, checkout or cart, and thus have a regular page reload as if barba wasn't "installed".

I would like to disable Barba transitions for all page going from OR to any namespace "account", "checkout" or "cart".

I've been using a couple of strategies but it's very dirty and unmanageable and doesn't seem  to work in every situations.

1. `prevent: ({ el }) => el.classList && (el.classList.contains('added_to_cart') || el.classList.contains('wc-block-cart__submit-button')),`
2.
```
{
            namespace: 'cart',
            afterEnter(){
                console.log('AFTER ENTER CART');
                $('a').attr('data-barba-prevent', true);
            }
        },{
            namespace: 'checkout',
            afterEnter(){
                console.log('AFTER ENTER Checkout');
                $('a').attr('data-barba-prevent', true);
            }
        },{
            namespace: 'account',
            afterEnter(){
                console.log('AFTER ENTER Account');
                $('a').attr('data-barba-prevent', true); 
            }
        }
```

3. after enter => preventBarbaOnSomeLinks();

```
    function preventBarbaOnSomeLinks(){
        $('a[href*="cart"], a[href*="checkout"], a[href*="my-account"], a[href*="wp-login"], .add_to_cart_button, .wpml-ls-link, .wpml-ls-item a, .nav--utils a, .mobile-nav__tools a, .wc-block-cart__submit-button').each(function() {
            $(this).attr('data-barba-prevent', true);
        });
    };
```

and 4.

```
                to: {
                    namespace: [
                        'shop',
                        'home',
                        'single-product',
                        'page'
                    ]
                },
                from: {
                    namespace: [
                        'shop',
                        'home',
                        'single-product',
                        'page'
                    ]
                },
```

with the hope that the transition works only between those namespaces/pages, sure it's doesn't trigger the animation but it's not doing any page reload, so if I'm on the cart page, going to the home page, it goes without transition but the page is not reloaded. I'm getting really confused really, I have the feeling all solutions have been tried without full success

Is this doable with just the prevent method, by checking if the next or current namespace is "account", "checkout" or "cart"?

I really would like to find a simple and reliable way to do that.

Thank you.

**Comment by xavierfoucrier** [comment]
Hi @romain-granai,

This issue is more related to **how your code is running** than Barba v2 issue...

For this kind of question/help, please **use the Slack workspace** in order to ask the whole community for support.
Join using the invite link here: https://barba.js.org/docs/getstarted/useful-links/#Developer.
